/* Actor.c generated by valac 0.34.9, the Vala compiler
 * generated from Actor.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define SDX_SCENES_SCENE2D_TYPE_TOUCHABLE (sdx_scenes_scene2d_touchable_get_type ())

#define SDX_SCENES_SCENE2D_TYPE_ACTOR (sdx_scenes_scene2d_actor_get_type ())
#define SDX_SCENES_SCENE2D_ACTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActor))
#define SDX_SCENES_SCENE2D_ACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActorClass))
#define SDX_SCENES_SCENE2D_IS_ACTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_ACTOR))
#define SDX_SCENES_SCENE2D_IS_ACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_SCENES_SCENE2D_TYPE_ACTOR))
#define SDX_SCENES_SCENE2D_ACTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActorClass))

typedef struct _sdxscenesscene2dActor sdxscenesscene2dActor;
typedef struct _sdxscenesscene2dActorClass sdxscenesscene2dActorClass;
typedef struct _sdxscenesscene2dActorPrivate sdxscenesscene2dActorPrivate;

#define SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER (sdx_scenes_scene2d_event_listener_get_type ())
#define SDX_SCENES_SCENE2D_EVENT_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER, sdxscenesscene2dEventListener))
#define SDX_SCENES_SCENE2D_IS_EVENT_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER))
#define SDX_SCENES_SCENE2D_EVENT_LISTENER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER, sdxscenesscene2dEventListenerIface))

typedef struct _sdxscenesscene2dEventListener sdxscenesscene2dEventListener;
typedef struct _sdxscenesscene2dEventListenerIface sdxscenesscene2dEventListenerIface;

#define SDX_SCENES_SCENE2D_TYPE_EVENT (sdx_scenes_scene2d_event_get_type ())
#define SDX_SCENES_SCENE2D_EVENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT, sdxscenesscene2dEvent))
#define SDX_SCENES_SCENE2D_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_SCENES_SCENE2D_TYPE_EVENT, sdxscenesscene2dEventClass))
#define SDX_SCENES_SCENE2D_IS_EVENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT))
#define SDX_SCENES_SCENE2D_IS_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_SCENES_SCENE2D_TYPE_EVENT))
#define SDX_SCENES_SCENE2D_EVENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT, sdxscenesscene2dEventClass))

typedef struct _sdxscenesscene2dEvent sdxscenesscene2dEvent;
typedef struct _sdxscenesscene2dEventClass sdxscenesscene2dEventClass;

#define SDX_SCENES_SCENE2D_TYPE_ACTION (sdx_scenes_scene2d_action_get_type ())
#define SDX_SCENES_SCENE2D_ACTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_ACTION, sdxscenesscene2dAction))
#define SDX_SCENES_SCENE2D_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_SCENES_SCENE2D_TYPE_ACTION, sdxscenesscene2dActionClass))
#define SDX_SCENES_SCENE2D_IS_ACTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_ACTION))
#define SDX_SCENES_SCENE2D_IS_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_SCENES_SCENE2D_TYPE_ACTION))
#define SDX_SCENES_SCENE2D_ACTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_SCENES_SCENE2D_TYPE_ACTION, sdxscenesscene2dActionClass))

typedef struct _sdxscenesscene2dAction sdxscenesscene2dAction;
typedef struct _sdxscenesscene2dActionClass sdxscenesscene2dActionClass;

#define SDX_TYPE_INPUT_ADAPTER (sdx_input_adapter_get_type ())
#define SDX_INPUT_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_INPUT_ADAPTER, sdxInputAdapter))
#define SDX_INPUT_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_TYPE_INPUT_ADAPTER, sdxInputAdapterClass))
#define SDX_IS_INPUT_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_INPUT_ADAPTER))
#define SDX_IS_INPUT_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_TYPE_INPUT_ADAPTER))
#define SDX_INPUT_ADAPTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_TYPE_INPUT_ADAPTER, sdxInputAdapterClass))

typedef struct _sdxInputAdapter sdxInputAdapter;
typedef struct _sdxInputAdapterClass sdxInputAdapterClass;

#define SDX_SCENES_SCENE2D_TYPE_STAGE (sdx_scenes_scene2d_stage_get_type ())
#define SDX_SCENES_SCENE2D_STAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_STAGE, sdxscenesscene2dStage))
#define SDX_SCENES_SCENE2D_STAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_SCENES_SCENE2D_TYPE_STAGE, sdxscenesscene2dStageClass))
#define SDX_SCENES_SCENE2D_IS_STAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_STAGE))
#define SDX_SCENES_SCENE2D_IS_STAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_SCENES_SCENE2D_TYPE_STAGE))
#define SDX_SCENES_SCENE2D_STAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_SCENES_SCENE2D_TYPE_STAGE, sdxscenesscene2dStageClass))

typedef struct _sdxscenesscene2dStage sdxscenesscene2dStage;
typedef struct _sdxscenesscene2dStageClass sdxscenesscene2dStageClass;

#define SDX_SCENES_SCENE2D_TYPE_GROUP (sdx_scenes_scene2d_group_get_type ())
#define SDX_SCENES_SCENE2D_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_GROUP, sdxscenesscene2dGroup))
#define SDX_SCENES_SCENE2D_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_SCENES_SCENE2D_TYPE_GROUP, sdxscenesscene2dGroupClass))
#define SDX_SCENES_SCENE2D_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_GROUP))
#define SDX_SCENES_SCENE2D_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_SCENES_SCENE2D_TYPE_GROUP))
#define SDX_SCENES_SCENE2D_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_SCENES_SCENE2D_TYPE_GROUP, sdxscenesscene2dGroupClass))

typedef struct _sdxscenesscene2dGroup sdxscenesscene2dGroup;
typedef struct _sdxscenesscene2dGroupClass sdxscenesscene2dGroupClass;

#define SDX_GRAPHICS_TYPE_COLOR (sdx_graphics_color_get_type ())
#define SDX_GRAPHICS_COLOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_TYPE_COLOR, sdxgraphicsColor))
#define SDX_GRAPHICS_COLOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_TYPE_COLOR, sdxgraphicsColorClass))
#define SDX_GRAPHICS_IS_COLOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_TYPE_COLOR))
#define SDX_GRAPHICS_IS_COLOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_TYPE_COLOR))
#define SDX_GRAPHICS_COLOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_TYPE_COLOR, sdxgraphicsColorClass))

typedef struct _sdxgraphicsColor sdxgraphicsColor;
typedef struct _sdxgraphicsColorClass sdxgraphicsColorClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define SDX_GRAPHICS_S2D_TYPE_BATCH (sdx_graphics_s2d_batch_get_type ())
#define SDX_GRAPHICS_S2D_BATCH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_S2D_TYPE_BATCH, sdxgraphicss2dBatch))
#define SDX_GRAPHICS_S2D_BATCH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_S2D_TYPE_BATCH, sdxgraphicss2dBatchClass))
#define SDX_GRAPHICS_S2D_IS_BATCH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_S2D_TYPE_BATCH))
#define SDX_GRAPHICS_S2D_IS_BATCH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_S2D_TYPE_BATCH))
#define SDX_GRAPHICS_S2D_BATCH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_S2D_TYPE_BATCH, sdxgraphicss2dBatchClass))

typedef struct _sdxgraphicss2dBatch sdxgraphicss2dBatch;
typedef struct _sdxgraphicss2dBatchClass sdxgraphicss2dBatchClass;

#define SDX_UTILS_TYPE_POOL (sdx_utils_pool_get_type ())
#define SDX_UTILS_POOL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_UTILS_TYPE_POOL, sdxutilsPool))
#define SDX_UTILS_POOL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_UTILS_TYPE_POOL, sdxutilsPoolClass))
#define SDX_UTILS_IS_POOL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_UTILS_TYPE_POOL))
#define SDX_UTILS_IS_POOL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_UTILS_TYPE_POOL))
#define SDX_UTILS_POOL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_UTILS_TYPE_POOL, sdxutilsPoolClass))

typedef struct _sdxutilsPool sdxutilsPool;
typedef struct _sdxutilsPoolClass sdxutilsPoolClass;

#define SDX_MATH_TYPE_VECTOR2 (sdx_math_vector2_get_type ())
#define SDX_MATH_VECTOR2(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_MATH_TYPE_VECTOR2, sdxmathVector2))
#define SDX_MATH_VECTOR2_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_MATH_TYPE_VECTOR2, sdxmathVector2Class))
#define SDX_MATH_IS_VECTOR2(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_MATH_TYPE_VECTOR2))
#define SDX_MATH_IS_VECTOR2_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_MATH_TYPE_VECTOR2))
#define SDX_MATH_VECTOR2_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_MATH_TYPE_VECTOR2, sdxmathVector2Class))

typedef struct _sdxmathVector2 sdxmathVector2;
typedef struct _sdxmathVector2Class sdxmathVector2Class;
typedef struct _sdxmathVector2Private sdxmathVector2Private;

typedef enum  {
	SDX_SCENES_SCENE2D_TOUCHABLE_enabled,
	SDX_SCENES_SCENE2D_TOUCHABLE_disabled,
	SDX_SCENES_SCENE2D_TOUCHABLE_childrenOnly
} sdxscenesscene2dTouchable;

struct _sdxscenesscene2dEventListenerIface {
	GTypeInterface parent_iface;
	gboolean (*handle) (sdxscenesscene2dEventListener* self, sdxscenesscene2dEvent* event);
};

struct _sdxscenesscene2dActor {
	GObject parent_instance;
	sdxscenesscene2dActorPrivate * priv;
	GeeArrayList* listeners;
	GeeArrayList* captureListeners;
	GeeArrayList* actions;
	gboolean visible;
	gdouble x;
	gdouble y;
	gdouble width;
	gdouble height;
	gdouble originX;
	gdouble originY;
	gdouble scaleX;
	gdouble scaleY;
	gdouble rotation;
};

struct _sdxscenesscene2dActorClass {
	GObjectClass parent_class;
};

struct _sdxscenesscene2dActorPrivate {
	sdxscenesscene2dStage* _stage;
	sdxscenesscene2dGroup* _parent;
	sdxscenesscene2dTouchable _touchable;
	GObject* _userObject;
	sdxgraphicsColor* _color;
	gchar* _name;
};

typedef enum  {
	SDX_EXCEPTION_IllegalArgumentException,
	SDX_EXCEPTION_IllegalStateException,
	SDX_EXCEPTION_SdxRuntimeException,
	SDX_EXCEPTION_NullPointerException,
	SDX_EXCEPTION_NoSuchElementException,
	SDX_EXCEPTION_SDLException
} sdxException;
#define SDX_EXCEPTION sdx_exception_quark ()
struct _sdxmathVector2 {
	GObject parent_instance;
	sdxmathVector2Private * priv;
	gdouble x;
	gdouble y;
};

struct _sdxmathVector2Class {
	GObjectClass parent_class;
};


static gpointer sdx_scenes_scene2d_actor_parent_class = NULL;

GType sdx_scenes_scene2d_touchable_get_type (void) G_GNUC_CONST;
#define SDX_SCENES_SCENE2D_PI 3.1415927
#define SDX_SCENES_SCENE2D_degreesToRadians (SDX_SCENES_SCENE2D_PI / 180.0)
GType sdx_scenes_scene2d_actor_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_event_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_event_listener_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_action_get_type (void) G_GNUC_CONST;
GType sdx_input_adapter_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_stage_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_group_get_type (void) G_GNUC_CONST;
GType sdx_graphics_color_get_type (void) G_GNUC_CONST;
#define SDX_SCENES_SCENE2D_ACTOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActorPrivate))
enum  {
	SDX_SCENES_SCENE2D_ACTOR_DUMMY_PROPERTY,
	SDX_SCENES_SCENE2D_ACTOR_STAGE,
	SDX_SCENES_SCENE2D_ACTOR_PARENT,
	SDX_SCENES_SCENE2D_ACTOR_TOUCHABLE,
	SDX_SCENES_SCENE2D_ACTOR_USER_OBJECT,
	SDX_SCENES_SCENE2D_ACTOR_COLOR,
	SDX_SCENES_SCENE2D_ACTOR_NAME
};
gpointer sdx_graphics_s2d_batch_ref (gpointer instance);
void sdx_graphics_s2d_batch_unref (gpointer instance);
GParamSpec* sdx_graphics_s2d_param_spec_batch (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void sdx_graphics_s2d_value_set_batch (GValue* value, gpointer v_object);
void sdx_graphics_s2d_value_take_batch (GValue* value, gpointer v_object);
gpointer sdx_graphics_s2d_value_get_batch (const GValue* value);
GType sdx_graphics_s2d_batch_get_type (void) G_GNUC_CONST;
void sdx_scenes_scene2d_actor_draw (sdxscenesscene2dActor* self, sdxgraphicss2dBatch* batch, gdouble parentAlpha);
void sdx_scenes_scene2d_actor_act (sdxscenesscene2dActor* self, gdouble delta);
gboolean sdx_scenes_scene2d_action_act (sdxscenesscene2dAction* self, gdouble delta);
void sdx_scenes_scene2d_action_set_actor (sdxscenesscene2dAction* self, sdxscenesscene2dActor* value);
gboolean sdx_scenes_scene2d_actor_fire (sdxscenesscene2dActor* self, sdxscenesscene2dEvent* event);
sdxscenesscene2dStage* sdx_scenes_scene2d_event_getStage (sdxscenesscene2dEvent* self);
void sdx_scenes_scene2d_event_setStage (sdxscenesscene2dEvent* self, sdxscenesscene2dStage* stage);
sdxscenesscene2dStage* sdx_scenes_scene2d_actor_get_stage (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_event_setTarget (sdxscenesscene2dEvent* self, sdxscenesscene2dActor* targetActor);
GType sdx_utils_pool_get_type (void) G_GNUC_CONST;
sdxutilsPool* sdx_utils_pools_obtain (GType type);
sdxscenesscene2dGroup* sdx_scenes_scene2d_actor_get_parent (sdxscenesscene2dActor* self);
gboolean sdx_scenes_scene2d_actor_notify (sdxscenesscene2dActor* self, sdxscenesscene2dEvent* event, gboolean capture);
gboolean sdx_scenes_scene2d_event_isStopped (sdxscenesscene2dEvent* self);
gboolean sdx_scenes_scene2d_event_isCancelled (sdxscenesscene2dEvent* self);
gboolean sdx_scenes_scene2d_event_getBubbles (sdxscenesscene2dEvent* self);
sdxscenesscene2dActor* sdx_scenes_scene2d_event_getTarget (sdxscenesscene2dEvent* self);
GQuark sdx_exception_quark (void);
void sdx_scenes_scene2d_event_setListenerActor (sdxscenesscene2dEvent* self, sdxscenesscene2dActor* listenerActor);
void sdx_scenes_scene2d_event_setCapture (sdxscenesscene2dEvent* self, gboolean capture);
gboolean sdx_scenes_scene2d_event_listener_handle (sdxscenesscene2dEventListener* self, sdxscenesscene2dEvent* event);
void sdx_scenes_scene2d_event_handle (sdxscenesscene2dEvent* self);
sdxscenesscene2dActor* sdx_scenes_scene2d_actor_hit (sdxscenesscene2dActor* self, gdouble x, gdouble y, gboolean touchable);
sdxscenesscene2dTouchable sdx_scenes_scene2d_actor_get_touchable (sdxscenesscene2dActor* self);
gboolean sdx_scenes_scene2d_actor_remove (sdxscenesscene2dActor* self);
gboolean sdx_scenes_scene2d_group_removeActor (sdxscenesscene2dGroup* self, sdxscenesscene2dActor* actor, gboolean unfocus);
gboolean sdx_scenes_scene2d_actor_addListener (sdxscenesscene2dActor* self, sdxscenesscene2dEventListener* listener);
gboolean sdx_scenes_scene2d_actor_removeListener (sdxscenesscene2dActor* self, sdxscenesscene2dEventListener* listener);
GeeArrayList* sdx_scenes_scene2d_actor_getListeners (sdxscenesscene2dActor* self);
gboolean sdx_scenes_scene2d_actor_addCaptureListener (sdxscenesscene2dActor* self, sdxscenesscene2dEventListener* listener);
gboolean sdx_scenes_scene2d_actor_removeCaptureListener (sdxscenesscene2dActor* self, sdxscenesscene2dEventListener* listener);
GeeArrayList* sdx_scenes_scene2d_actor_getCaptureListeners (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_addAction (sdxscenesscene2dActor* self, sdxscenesscene2dAction* action);
void sdx_scenes_scene2d_actor_removeAction (sdxscenesscene2dActor* self, sdxscenesscene2dAction* action);
GeeArrayList* sdx_scenes_scene2d_actor_getActions (sdxscenesscene2dActor* self);
gboolean sdx_scenes_scene2d_actor_hasActions (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_clearActions (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_clearListeners (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_clear (sdxscenesscene2dActor* self);
gboolean sdx_scenes_scene2d_actor_isDescendantOf (sdxscenesscene2dActor* self, sdxscenesscene2dActor* actor);
gboolean sdx_scenes_scene2d_actor_isAscendantOf (sdxscenesscene2dActor* self, sdxscenesscene2dActor* actor);
sdxscenesscene2dActor* sdx_scenes_scene2d_actor_firstAscendant (sdxscenesscene2dActor* self, GType type);
gboolean sdx_scenes_scene2d_actor_hasParent (sdxscenesscene2dActor* self);
gboolean sdx_scenes_scene2d_actor_isTouchable (sdxscenesscene2dActor* self);
gboolean sdx_scenes_scene2d_actor_isVisible (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_setVisible (sdxscenesscene2dActor* self, gboolean visible);
gdouble sdx_scenes_scene2d_actor_getX (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_setX (sdxscenesscene2dActor* self, gdouble x);
void sdx_scenes_scene2d_actor_positionChanged (sdxscenesscene2dActor* self);
gdouble sdx_scenes_scene2d_actor_getY (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_setY (sdxscenesscene2dActor* self, gdouble y);
void sdx_scenes_scene2d_actor_setPosition (sdxscenesscene2dActor* self, gdouble x, gdouble y);
void sdx_scenes_scene2d_actor_moveBy (sdxscenesscene2dActor* self, gdouble x, gdouble y);
gdouble sdx_scenes_scene2d_actor_getWidth (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_setWidth (sdxscenesscene2dActor* self, gdouble width);
void sdx_scenes_scene2d_actor_sizeChanged (sdxscenesscene2dActor* self);
gdouble sdx_scenes_scene2d_actor_getHeight (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_setHeight (sdxscenesscene2dActor* self, gdouble height);
gdouble sdx_scenes_scene2d_actor_getTop (sdxscenesscene2dActor* self);
gdouble sdx_scenes_scene2d_actor_getRight (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_rotationChanged (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_setSize (sdxscenesscene2dActor* self, gdouble width, gdouble height);
void sdx_scenes_scene2d_actor_sizeBy (sdxscenesscene2dActor* self, gdouble size);
void sdx_scenes_scene2d_actor_setBounds (sdxscenesscene2dActor* self, gdouble x, gdouble y, gdouble width, gdouble height);
gdouble sdx_scenes_scene2d_actor_getOriginX (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_setOriginX (sdxscenesscene2dActor* self, gdouble originX);
gdouble sdx_scenes_scene2d_actor_getOriginY (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_setOriginY (sdxscenesscene2dActor* self, gdouble originY);
void sdx_scenes_scene2d_actor_setOrigin (sdxscenesscene2dActor* self, gdouble originX, gdouble originY);
gdouble sdx_scenes_scene2d_actor_getScaleX (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_setScaleX (sdxscenesscene2dActor* self, gdouble scaleX);
gdouble sdx_scenes_scene2d_actor_getScaleY (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_setScaleY (sdxscenesscene2dActor* self, gdouble scaleXY);
void sdx_scenes_scene2d_actor_setScale (sdxscenesscene2dActor* self, gdouble scaleX, gdouble scaleY);
void sdx_scenes_scene2d_actor_scaleBy (sdxscenesscene2dActor* self, gdouble scaleX, gdouble scaleY);
gdouble sdx_scenes_scene2d_actor_getRotation (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_setRotation (sdxscenesscene2dActor* self, gdouble degrees);
void sdx_scenes_scene2d_actor_rotateBy (sdxscenesscene2dActor* self, gdouble amountInDegrees);
void sdx_scenes_scene2d_actor_toFront (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_setZIndex (sdxscenesscene2dActor* self, gint index);
void sdx_scenes_scene2d_actor_toBack (sdxscenesscene2dActor* self);
GeeArrayList* sdx_scenes_scene2d_group_get_children (sdxscenesscene2dGroup* self);
gint sdx_scenes_scene2d_actor_getZIndex (sdxscenesscene2dActor* self);
GType sdx_math_vector2_get_type (void) G_GNUC_CONST;
sdxmathVector2* sdx_scenes_scene2d_actor_screenToLocalCoordinates (sdxscenesscene2dActor* self, sdxmathVector2* screenCoords);
sdxmathVector2* sdx_scenes_scene2d_actor_stageToLocalCoordinates (sdxscenesscene2dActor* self, sdxmathVector2* stageCoords);
sdxmathVector2* sdx_scenes_scene2d_stage_screenToStageCoordinates (sdxscenesscene2dStage* self, sdxmathVector2* screenCoords);
sdxmathVector2* sdx_scenes_scene2d_actor_parentToLocalCoordinates (sdxscenesscene2dActor* self, sdxmathVector2* parentCoords);
sdxmathVector2* sdx_scenes_scene2d_actor_localToStageCoordinates (sdxscenesscene2dActor* self, sdxmathVector2* localCoords);
sdxmathVector2* sdx_scenes_scene2d_actor_localToAscendantCoordinates (sdxscenesscene2dActor* self, sdxscenesscene2dActor* ascendant, sdxmathVector2* localCoords);
sdxmathVector2* sdx_scenes_scene2d_actor_localToParentCoordinates (sdxscenesscene2dActor* self, sdxmathVector2* localCoords);
sdxscenesscene2dActor* sdx_scenes_scene2d_actor_new (void);
sdxscenesscene2dActor* sdx_scenes_scene2d_actor_construct (GType object_type);
void sdx_scenes_scene2d_actor_set_stage (sdxscenesscene2dActor* self, sdxscenesscene2dStage* value);
void sdx_scenes_scene2d_actor_set_parent (sdxscenesscene2dActor* self, sdxscenesscene2dGroup* value);
void sdx_scenes_scene2d_actor_set_touchable (sdxscenesscene2dActor* self, sdxscenesscene2dTouchable value);
GObject* sdx_scenes_scene2d_actor_get_userObject (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_set_userObject (sdxscenesscene2dActor* self, GObject* value);
sdxgraphicsColor* sdx_scenes_scene2d_actor_get_color (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_set_color (sdxscenesscene2dActor* self, sdxgraphicsColor* value);
const gchar* sdx_scenes_scene2d_actor_get_name (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_set_name (sdxscenesscene2dActor* self, const gchar* value);
static void sdx_scenes_scene2d_actor_finalize (GObject* obj);
static void _vala_sdx_scenes_scene2d_actor_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_sdx_scenes_scene2d_actor_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GType sdx_scenes_scene2d_touchable_get_type (void) {
	static volatile gsize sdx_scenes_scene2d_touchable_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_scenes_scene2d_touchable_type_id__volatile)) {
		static const GEnumValue values[] = {{SDX_SCENES_SCENE2D_TOUCHABLE_enabled, "SDX_SCENES_SCENE2D_TOUCHABLE_enabled", "enabled"}, {SDX_SCENES_SCENE2D_TOUCHABLE_disabled, "SDX_SCENES_SCENE2D_TOUCHABLE_disabled", "disabled"}, {SDX_SCENES_SCENE2D_TOUCHABLE_childrenOnly, "SDX_SCENES_SCENE2D_TOUCHABLE_childrenOnly", "childrenonly"}, {0, NULL, NULL}};
		GType sdx_scenes_scene2d_touchable_type_id;
		sdx_scenes_scene2d_touchable_type_id = g_enum_register_static ("sdxscenesscene2dTouchable", values);
		g_once_init_leave (&sdx_scenes_scene2d_touchable_type_id__volatile, sdx_scenes_scene2d_touchable_type_id);
	}
	return sdx_scenes_scene2d_touchable_type_id__volatile;
}


/**
         * draw the actor
         */
void sdx_scenes_scene2d_actor_draw (sdxscenesscene2dActor* self, sdxgraphicss2dBatch* batch, gdouble parentAlpha) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (batch != NULL);
}


/**
         * update the actor each frame
         */
void sdx_scenes_scene2d_actor_act (sdxscenesscene2dActor* self, gdouble delta) {
	GeeArrayList* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->actions;
	_tmp1_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ > 0) {
		{
			gint i = 0;
			i = 0;
			{
				gboolean _tmp3_ = FALSE;
				_tmp3_ = TRUE;
				while (TRUE) {
					GeeArrayList* _tmp5_ = NULL;
					gint _tmp6_ = 0;
					gint _tmp7_ = 0;
					sdxscenesscene2dAction* action = NULL;
					GeeArrayList* _tmp8_ = NULL;
					gint _tmp9_ = 0;
					gpointer _tmp10_ = NULL;
					sdxscenesscene2dAction* _tmp11_ = NULL;
					gdouble _tmp12_ = 0.0;
					gboolean _tmp13_ = FALSE;
					if (!_tmp3_) {
						gint _tmp4_ = 0;
						_tmp4_ = i;
						i = _tmp4_ + 1;
					}
					_tmp3_ = FALSE;
					_tmp5_ = self->actions;
					_tmp6_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp5_);
					_tmp7_ = _tmp6_;
					if (!(i <= (_tmp7_ - 1))) {
						break;
					}
					_tmp8_ = self->actions;
					_tmp9_ = i;
					_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
					action = (sdxscenesscene2dAction*) _tmp10_;
					_tmp11_ = action;
					_tmp12_ = delta;
					_tmp13_ = sdx_scenes_scene2d_action_act (_tmp11_, _tmp12_);
					if (_tmp13_) {
						sdxscenesscene2dAction* current = NULL;
						GeeArrayList* _tmp14_ = NULL;
						gint _tmp15_ = 0;
						gpointer _tmp16_ = NULL;
						gint _tmp17_ = 0;
						sdxscenesscene2dAction* _tmp18_ = NULL;
						sdxscenesscene2dAction* _tmp19_ = NULL;
						gint actionIndex = 0;
						gint _tmp24_ = 0;
						_tmp14_ = self->actions;
						_tmp15_ = i;
						_tmp16_ = gee_abstract_list_get ((GeeAbstractList*) _tmp14_, _tmp15_);
						current = (sdxscenesscene2dAction*) _tmp16_;
						_tmp18_ = current;
						_tmp19_ = action;
						if (_tmp18_ == _tmp19_) {
							gint _tmp20_ = 0;
							_tmp20_ = i;
							_tmp17_ = _tmp20_;
						} else {
							GeeArrayList* _tmp21_ = NULL;
							sdxscenesscene2dAction* _tmp22_ = NULL;
							gint _tmp23_ = 0;
							_tmp21_ = self->actions;
							_tmp22_ = action;
							_tmp23_ = gee_abstract_list_index_of ((GeeAbstractList*) _tmp21_, _tmp22_);
							_tmp17_ = _tmp23_;
						}
						actionIndex = _tmp17_;
						_tmp24_ = actionIndex;
						if (_tmp24_ != (-1)) {
							GeeArrayList* _tmp25_ = NULL;
							gint _tmp26_ = 0;
							gpointer _tmp27_ = NULL;
							sdxscenesscene2dAction* _tmp28_ = NULL;
							sdxscenesscene2dAction* _tmp29_ = NULL;
							gint _tmp30_ = 0;
							_tmp25_ = self->actions;
							_tmp26_ = actionIndex;
							_tmp27_ = gee_abstract_list_remove_at ((GeeAbstractList*) _tmp25_, _tmp26_);
							_tmp28_ = (sdxscenesscene2dAction*) _tmp27_;
							_g_object_unref0 (_tmp28_);
							_tmp29_ = action;
							sdx_scenes_scene2d_action_set_actor (_tmp29_, NULL);
							_tmp30_ = i;
							i = _tmp30_ - 1;
						}
						_g_object_unref0 (current);
					}
					_g_object_unref0 (action);
				}
			}
		}
	}
}


/**
         * fire event and propogate up the chain to parent nodes
         */
static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


gboolean sdx_scenes_scene2d_actor_fire (sdxscenesscene2dActor* self, sdxscenesscene2dEvent* event) {
	gboolean result = FALSE;
	sdxscenesscene2dEvent* _tmp0_ = NULL;
	sdxscenesscene2dStage* _tmp1_ = NULL;
	sdxscenesscene2dStage* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	sdxscenesscene2dEvent* _tmp6_ = NULL;
	GeeArrayList* ancestors = NULL;
	sdxutilsPool* _tmp7_ = NULL;
	sdxscenesscene2dGroup* parent = NULL;
	sdxscenesscene2dGroup* _tmp8_ = NULL;
	sdxscenesscene2dGroup* _tmp9_ = NULL;
	sdxscenesscene2dEvent* _tmp30_ = NULL;
	sdxscenesscene2dEvent* _tmp31_ = NULL;
	gboolean _tmp32_ = FALSE;
	sdxscenesscene2dEvent* _tmp35_ = NULL;
	sdxscenesscene2dEvent* _tmp36_ = NULL;
	gboolean _tmp37_ = FALSE;
	sdxscenesscene2dEvent* _tmp40_ = NULL;
	gboolean _tmp41_ = FALSE;
	sdxscenesscene2dEvent* _tmp58_ = NULL;
	gboolean _tmp59_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = event;
	_tmp1_ = sdx_scenes_scene2d_event_getStage (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = _tmp2_ == NULL;
	_g_object_unref0 (_tmp2_);
	if (_tmp3_) {
		sdxscenesscene2dEvent* _tmp4_ = NULL;
		sdxscenesscene2dStage* _tmp5_ = NULL;
		_tmp4_ = event;
		_tmp5_ = self->priv->_stage;
		sdx_scenes_scene2d_event_setStage (_tmp4_, _tmp5_);
	}
	_tmp6_ = event;
	sdx_scenes_scene2d_event_setTarget (_tmp6_, self);
	_tmp7_ = sdx_utils_pools_obtain (GEE_TYPE_ARRAY_LIST);
	ancestors = G_TYPE_CHECK_INSTANCE_CAST (_tmp7_, GEE_TYPE_ARRAY_LIST, GeeArrayList);
	_tmp8_ = self->priv->_parent;
	_tmp9_ = _g_object_ref0 (_tmp8_);
	parent = _tmp9_;
	while (TRUE) {
		sdxscenesscene2dGroup* _tmp10_ = NULL;
		GeeArrayList* _tmp11_ = NULL;
		sdxscenesscene2dGroup* _tmp12_ = NULL;
		sdxscenesscene2dGroup* _tmp13_ = NULL;
		sdxscenesscene2dGroup* _tmp14_ = NULL;
		sdxscenesscene2dGroup* _tmp15_ = NULL;
		_tmp10_ = parent;
		if (!(_tmp10_ != NULL)) {
			break;
		}
		_tmp11_ = ancestors;
		_tmp12_ = parent;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp11_, _tmp12_);
		_tmp13_ = parent;
		_tmp14_ = ((sdxscenesscene2dActor*) _tmp13_)->priv->_parent;
		_tmp15_ = _g_object_ref0 (_tmp14_);
		_g_object_unref0 (parent);
		parent = _tmp15_;
	}
	{
		gint i = 0;
		GeeArrayList* _tmp16_ = NULL;
		gint _tmp17_ = 0;
		gint _tmp18_ = 0;
		_tmp16_ = ancestors;
		_tmp17_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp16_);
		_tmp18_ = _tmp17_;
		i = _tmp18_ - 1;
		{
			gboolean _tmp19_ = FALSE;
			_tmp19_ = TRUE;
			while (TRUE) {
				sdxscenesscene2dGroup* currentTarget = NULL;
				GeeArrayList* _tmp21_ = NULL;
				gint _tmp22_ = 0;
				gpointer _tmp23_ = NULL;
				sdxscenesscene2dGroup* _tmp24_ = NULL;
				sdxscenesscene2dEvent* _tmp25_ = NULL;
				sdxscenesscene2dEvent* _tmp26_ = NULL;
				gboolean _tmp27_ = FALSE;
				if (!_tmp19_) {
					gint _tmp20_ = 0;
					_tmp20_ = i;
					i = _tmp20_ + 1;
				}
				_tmp19_ = FALSE;
				if (!(i <= 0)) {
					break;
				}
				_tmp21_ = ancestors;
				_tmp22_ = i;
				_tmp23_ = gee_abstract_list_get ((GeeAbstractList*) _tmp21_, _tmp22_);
				currentTarget = (sdxscenesscene2dGroup*) _tmp23_;
				_tmp24_ = currentTarget;
				_tmp25_ = event;
				sdx_scenes_scene2d_actor_notify ((sdxscenesscene2dActor*) _tmp24_, _tmp25_, TRUE);
				_tmp26_ = event;
				_tmp27_ = sdx_scenes_scene2d_event_isStopped (_tmp26_);
				if (_tmp27_) {
					sdxscenesscene2dEvent* _tmp28_ = NULL;
					gboolean _tmp29_ = FALSE;
					_tmp28_ = event;
					_tmp29_ = sdx_scenes_scene2d_event_isCancelled (_tmp28_);
					result = _tmp29_;
					_g_object_unref0 (currentTarget);
					_g_object_unref0 (parent);
					_g_object_unref0 (ancestors);
					return result;
				}
				_g_object_unref0 (currentTarget);
			}
		}
	}
	_tmp30_ = event;
	sdx_scenes_scene2d_actor_notify (self, _tmp30_, TRUE);
	_tmp31_ = event;
	_tmp32_ = sdx_scenes_scene2d_event_isStopped (_tmp31_);
	if (_tmp32_) {
		sdxscenesscene2dEvent* _tmp33_ = NULL;
		gboolean _tmp34_ = FALSE;
		_tmp33_ = event;
		_tmp34_ = sdx_scenes_scene2d_event_isCancelled (_tmp33_);
		result = _tmp34_;
		_g_object_unref0 (parent);
		_g_object_unref0 (ancestors);
		return result;
	}
	_tmp35_ = event;
	sdx_scenes_scene2d_actor_notify (self, _tmp35_, FALSE);
	_tmp36_ = event;
	_tmp37_ = sdx_scenes_scene2d_event_getBubbles (_tmp36_);
	if (!_tmp37_) {
		sdxscenesscene2dEvent* _tmp38_ = NULL;
		gboolean _tmp39_ = FALSE;
		_tmp38_ = event;
		_tmp39_ = sdx_scenes_scene2d_event_isCancelled (_tmp38_);
		result = _tmp39_;
		_g_object_unref0 (parent);
		_g_object_unref0 (ancestors);
		return result;
	}
	_tmp40_ = event;
	_tmp41_ = sdx_scenes_scene2d_event_isStopped (_tmp40_);
	if (_tmp41_) {
		sdxscenesscene2dEvent* _tmp42_ = NULL;
		gboolean _tmp43_ = FALSE;
		_tmp42_ = event;
		_tmp43_ = sdx_scenes_scene2d_event_isCancelled (_tmp42_);
		result = _tmp43_;
		_g_object_unref0 (parent);
		_g_object_unref0 (ancestors);
		return result;
	}
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp44_ = FALSE;
			_tmp44_ = TRUE;
			while (TRUE) {
				GeeArrayList* _tmp46_ = NULL;
				gint _tmp47_ = 0;
				gint _tmp48_ = 0;
				GeeArrayList* _tmp49_ = NULL;
				gint _tmp50_ = 0;
				gpointer _tmp51_ = NULL;
				sdxscenesscene2dGroup* _tmp52_ = NULL;
				sdxscenesscene2dEvent* _tmp53_ = NULL;
				sdxscenesscene2dEvent* _tmp54_ = NULL;
				gboolean _tmp55_ = FALSE;
				if (!_tmp44_) {
					gint _tmp45_ = 0;
					_tmp45_ = i;
					i = _tmp45_ + 1;
				}
				_tmp44_ = FALSE;
				_tmp46_ = ancestors;
				_tmp47_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp46_);
				_tmp48_ = _tmp47_;
				if (!(i <= (_tmp48_ - 1))) {
					break;
				}
				_tmp49_ = ancestors;
				_tmp50_ = i;
				_tmp51_ = gee_abstract_list_get ((GeeAbstractList*) _tmp49_, _tmp50_);
				_tmp52_ = (sdxscenesscene2dGroup*) _tmp51_;
				_tmp53_ = event;
				sdx_scenes_scene2d_actor_notify ((sdxscenesscene2dActor*) _tmp52_, _tmp53_, FALSE);
				_g_object_unref0 (_tmp52_);
				_tmp54_ = event;
				_tmp55_ = sdx_scenes_scene2d_event_isStopped (_tmp54_);
				if (_tmp55_) {
					sdxscenesscene2dEvent* _tmp56_ = NULL;
					gboolean _tmp57_ = FALSE;
					_tmp56_ = event;
					_tmp57_ = sdx_scenes_scene2d_event_isCancelled (_tmp56_);
					result = _tmp57_;
					_g_object_unref0 (parent);
					_g_object_unref0 (ancestors);
					return result;
				}
			}
		}
	}
	_tmp58_ = event;
	_tmp59_ = sdx_scenes_scene2d_event_isCancelled (_tmp58_);
	result = _tmp59_;
	_g_object_unref0 (parent);
	_g_object_unref0 (ancestors);
	return result;
}


/**
         * notify listeners
         */
gboolean sdx_scenes_scene2d_actor_notify (sdxscenesscene2dActor* self, sdxscenesscene2dEvent* event, gboolean capture) {
	gboolean result = FALSE;
	sdxscenesscene2dEvent* _tmp0_ = NULL;
	sdxscenesscene2dActor* _tmp1_ = NULL;
	sdxscenesscene2dActor* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	GeeArrayList* _tmp6_ = NULL;
	gboolean _tmp7_ = FALSE;
	GeeArrayList* listeners = NULL;
	GeeArrayList* _tmp10_ = NULL;
	GeeArrayList* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	gint _tmp13_ = 0;
	sdxscenesscene2dEvent* _tmp16_ = NULL;
	sdxscenesscene2dEvent* _tmp17_ = NULL;
	gboolean _tmp18_ = FALSE;
	sdxscenesscene2dEvent* _tmp19_ = NULL;
	sdxscenesscene2dStage* _tmp20_ = NULL;
	sdxscenesscene2dStage* _tmp21_ = NULL;
	gboolean _tmp22_ = FALSE;
	sdxscenesscene2dEvent* _tmp37_ = NULL;
	gboolean _tmp38_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = event;
	_tmp1_ = sdx_scenes_scene2d_event_getTarget (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = _tmp2_ == NULL;
	_g_object_unref0 (_tmp2_);
	if (_tmp3_) {
		GError* _tmp4_ = NULL;
		gboolean _tmp5_ = FALSE;
		_tmp4_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_IllegalArgumentException, "The event target cannot be null.");
		_inner_error_ = _tmp4_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return _tmp5_;
	}
	_tmp7_ = capture;
	if (_tmp7_) {
		GeeArrayList* _tmp8_ = NULL;
		_tmp8_ = self->captureListeners;
		_tmp6_ = _tmp8_;
	} else {
		GeeArrayList* _tmp9_ = NULL;
		_tmp9_ = self->listeners;
		_tmp6_ = _tmp9_;
	}
	_tmp10_ = _g_object_ref0 (_tmp6_);
	listeners = _tmp10_;
	_tmp11_ = listeners;
	_tmp12_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp11_);
	_tmp13_ = _tmp12_;
	if (_tmp13_ == 0) {
		sdxscenesscene2dEvent* _tmp14_ = NULL;
		gboolean _tmp15_ = FALSE;
		_tmp14_ = event;
		_tmp15_ = sdx_scenes_scene2d_event_isCancelled (_tmp14_);
		result = _tmp15_;
		_g_object_unref0 (listeners);
		return result;
	}
	_tmp16_ = event;
	sdx_scenes_scene2d_event_setListenerActor (_tmp16_, self);
	_tmp17_ = event;
	_tmp18_ = capture;
	sdx_scenes_scene2d_event_setCapture (_tmp17_, _tmp18_);
	_tmp19_ = event;
	_tmp20_ = sdx_scenes_scene2d_event_getStage (_tmp19_);
	_tmp21_ = _tmp20_;
	_tmp22_ = _tmp21_ == NULL;
	_g_object_unref0 (_tmp21_);
	if (_tmp22_) {
		sdxscenesscene2dEvent* _tmp23_ = NULL;
		sdxscenesscene2dStage* _tmp24_ = NULL;
		_tmp23_ = event;
		_tmp24_ = self->priv->_stage;
		sdx_scenes_scene2d_event_setStage (_tmp23_, _tmp24_);
	}
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp25_ = FALSE;
			_tmp25_ = TRUE;
			while (TRUE) {
				GeeArrayList* _tmp27_ = NULL;
				gint _tmp28_ = 0;
				gint _tmp29_ = 0;
				sdxscenesscene2dEventListener* listener = NULL;
				GeeArrayList* _tmp30_ = NULL;
				gint _tmp31_ = 0;
				gpointer _tmp32_ = NULL;
				sdxscenesscene2dEventListener* _tmp33_ = NULL;
				sdxscenesscene2dEvent* _tmp34_ = NULL;
				gboolean _tmp35_ = FALSE;
				if (!_tmp25_) {
					gint _tmp26_ = 0;
					_tmp26_ = i;
					i = _tmp26_ + 1;
				}
				_tmp25_ = FALSE;
				_tmp27_ = listeners;
				_tmp28_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp27_);
				_tmp29_ = _tmp28_;
				if (!(i <= (_tmp29_ - 1))) {
					break;
				}
				_tmp30_ = listeners;
				_tmp31_ = i;
				_tmp32_ = gee_abstract_list_get ((GeeAbstractList*) _tmp30_, _tmp31_);
				listener = (sdxscenesscene2dEventListener*) _tmp32_;
				_tmp33_ = listener;
				_tmp34_ = event;
				_tmp35_ = sdx_scenes_scene2d_event_listener_handle (_tmp33_, _tmp34_);
				if (_tmp35_) {
					sdxscenesscene2dEvent* _tmp36_ = NULL;
					_tmp36_ = event;
					sdx_scenes_scene2d_event_handle (_tmp36_);
				}
				_g_object_unref0 (listener);
			}
		}
	}
	_tmp37_ = event;
	_tmp38_ = sdx_scenes_scene2d_event_isCancelled (_tmp37_);
	result = _tmp38_;
	_g_object_unref0 (listeners);
	return result;
}


/**
         * hit - does the actor contain (x,y)
         */
sdxscenesscene2dActor* sdx_scenes_scene2d_actor_hit (sdxscenesscene2dActor* self, gdouble x, gdouble y, gboolean touchable) {
	sdxscenesscene2dActor* result = NULL;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	sdxscenesscene2dActor* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp5_ = FALSE;
	gboolean _tmp6_ = FALSE;
	gdouble _tmp7_ = 0.0;
	sdxscenesscene2dActor* _tmp13_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = touchable;
	if (_tmp1_) {
		sdxscenesscene2dTouchable _tmp2_ = 0;
		_tmp2_ = self->priv->_touchable;
		_tmp0_ = _tmp2_ != SDX_SCENES_SCENE2D_TOUCHABLE_enabled;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		result = NULL;
		return result;
	}
	_tmp7_ = x;
	if (_tmp7_ >= ((gdouble) 0)) {
		gdouble _tmp8_ = 0.0;
		gdouble _tmp9_ = 0.0;
		_tmp8_ = x;
		_tmp9_ = self->width;
		_tmp6_ = _tmp8_ < _tmp9_;
	} else {
		_tmp6_ = FALSE;
	}
	if (_tmp6_) {
		gdouble _tmp10_ = 0.0;
		_tmp10_ = y;
		_tmp5_ = _tmp10_ >= ((gdouble) 0);
	} else {
		_tmp5_ = FALSE;
	}
	if (_tmp5_) {
		gdouble _tmp11_ = 0.0;
		gdouble _tmp12_ = 0.0;
		_tmp11_ = y;
		_tmp12_ = self->height;
		_tmp4_ = _tmp11_ < _tmp12_;
	} else {
		_tmp4_ = FALSE;
	}
	if (_tmp4_) {
		_tmp3_ = self;
	} else {
		_tmp3_ = NULL;
	}
	_tmp13_ = _g_object_ref0 (_tmp3_);
	result = _tmp13_;
	return result;
}


gboolean sdx_scenes_scene2d_actor_remove (sdxscenesscene2dActor* self) {
	gboolean result = FALSE;
	sdxscenesscene2dGroup* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_parent;
	if (_tmp0_ != NULL) {
		sdxscenesscene2dGroup* _tmp1_ = NULL;
		gboolean _tmp2_ = FALSE;
		_tmp1_ = self->priv->_parent;
		_tmp2_ = sdx_scenes_scene2d_group_removeActor (_tmp1_, self, TRUE);
		result = _tmp2_;
		return result;
	}
	result = FALSE;
	return result;
}


gboolean sdx_scenes_scene2d_actor_addListener (sdxscenesscene2dActor* self, sdxscenesscene2dEventListener* listener) {
	gboolean result = FALSE;
	sdxscenesscene2dEventListener* _tmp0_ = NULL;
	GeeArrayList* _tmp3_ = NULL;
	sdxscenesscene2dEventListener* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (listener != NULL, FALSE);
	_tmp0_ = listener;
	if (_tmp0_ == NULL) {
		GError* _tmp1_ = NULL;
		gboolean _tmp2_ = FALSE;
		_tmp1_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_IllegalArgumentException, "listener cannot be null.");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return _tmp2_;
	}
	_tmp3_ = self->listeners;
	_tmp4_ = listener;
	_tmp5_ = gee_abstract_collection_contains ((GeeAbstractCollection*) _tmp3_, _tmp4_);
	if (!_tmp5_) {
		GeeArrayList* _tmp6_ = NULL;
		sdxscenesscene2dEventListener* _tmp7_ = NULL;
		_tmp6_ = self->listeners;
		_tmp7_ = listener;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp6_, _tmp7_);
		result = TRUE;
		return result;
	}
	result = FALSE;
	return result;
}


gboolean sdx_scenes_scene2d_actor_removeListener (sdxscenesscene2dActor* self, sdxscenesscene2dEventListener* listener) {
	gboolean result = FALSE;
	sdxscenesscene2dEventListener* _tmp0_ = NULL;
	GeeArrayList* _tmp3_ = NULL;
	sdxscenesscene2dEventListener* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (listener != NULL, FALSE);
	_tmp0_ = listener;
	if (_tmp0_ == NULL) {
		GError* _tmp1_ = NULL;
		gboolean _tmp2_ = FALSE;
		_tmp1_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_IllegalArgumentException, "listener cannot be null.");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return _tmp2_;
	}
	_tmp3_ = self->listeners;
	_tmp4_ = listener;
	_tmp5_ = gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp3_, _tmp4_);
	result = _tmp5_;
	return result;
}


GeeArrayList* sdx_scenes_scene2d_actor_getListeners (sdxscenesscene2dActor* self) {
	GeeArrayList* result = NULL;
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->listeners;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


gboolean sdx_scenes_scene2d_actor_addCaptureListener (sdxscenesscene2dActor* self, sdxscenesscene2dEventListener* listener) {
	gboolean result = FALSE;
	sdxscenesscene2dEventListener* _tmp0_ = NULL;
	GeeArrayList* _tmp3_ = NULL;
	sdxscenesscene2dEventListener* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (listener != NULL, FALSE);
	_tmp0_ = listener;
	if (_tmp0_ == NULL) {
		GError* _tmp1_ = NULL;
		gboolean _tmp2_ = FALSE;
		_tmp1_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_IllegalArgumentException, "listener cannot be null.");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return _tmp2_;
	}
	_tmp3_ = self->captureListeners;
	_tmp4_ = listener;
	_tmp5_ = gee_abstract_collection_contains ((GeeAbstractCollection*) _tmp3_, _tmp4_);
	if (!_tmp5_) {
		GeeArrayList* _tmp6_ = NULL;
		sdxscenesscene2dEventListener* _tmp7_ = NULL;
		_tmp6_ = self->captureListeners;
		_tmp7_ = listener;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp6_, _tmp7_);
	}
	result = TRUE;
	return result;
}


gboolean sdx_scenes_scene2d_actor_removeCaptureListener (sdxscenesscene2dActor* self, sdxscenesscene2dEventListener* listener) {
	gboolean result = FALSE;
	sdxscenesscene2dEventListener* _tmp0_ = NULL;
	GeeArrayList* _tmp3_ = NULL;
	sdxscenesscene2dEventListener* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (listener != NULL, FALSE);
	_tmp0_ = listener;
	if (_tmp0_ == NULL) {
		GError* _tmp1_ = NULL;
		gboolean _tmp2_ = FALSE;
		_tmp1_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_IllegalArgumentException, "listener cannot be null.");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return _tmp2_;
	}
	_tmp3_ = self->captureListeners;
	_tmp4_ = listener;
	_tmp5_ = gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp3_, _tmp4_);
	result = _tmp5_;
	return result;
}


GeeArrayList* sdx_scenes_scene2d_actor_getCaptureListeners (sdxscenesscene2dActor* self) {
	GeeArrayList* result = NULL;
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->captureListeners;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


void sdx_scenes_scene2d_actor_addAction (sdxscenesscene2dActor* self, sdxscenesscene2dAction* action) {
	sdxscenesscene2dAction* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	sdxscenesscene2dAction* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (action != NULL);
	_tmp0_ = action;
	sdx_scenes_scene2d_action_set_actor (_tmp0_, self);
	_tmp1_ = self->actions;
	_tmp2_ = action;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp1_, _tmp2_);
}


void sdx_scenes_scene2d_actor_removeAction (sdxscenesscene2dActor* self, sdxscenesscene2dAction* action) {
	GeeArrayList* _tmp0_ = NULL;
	sdxscenesscene2dAction* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (action != NULL);
	_tmp0_ = self->actions;
	_tmp1_ = action;
	_tmp2_ = gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp0_, _tmp1_);
	if (_tmp2_) {
		sdxscenesscene2dAction* _tmp3_ = NULL;
		_tmp3_ = action;
		sdx_scenes_scene2d_action_set_actor (_tmp3_, NULL);
	}
}


GeeArrayList* sdx_scenes_scene2d_actor_getActions (sdxscenesscene2dActor* self) {
	GeeArrayList* result = NULL;
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->actions;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


gboolean sdx_scenes_scene2d_actor_hasActions (sdxscenesscene2dActor* self) {
	gboolean result = FALSE;
	GeeArrayList* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->actions;
	_tmp1_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_ > 0;
	return result;
}


void sdx_scenes_scene2d_actor_clearActions (sdxscenesscene2dActor* self) {
	GeeArrayList* _tmp12_ = NULL;
	g_return_if_fail (self != NULL);
	{
		GeeArrayList* _action_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _action_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _action_index = 0;
		_tmp0_ = self->actions;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_action_list = _tmp1_;
		_tmp2_ = _action_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_action_size = _tmp4_;
		_action_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			sdxscenesscene2dAction* action = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			sdxscenesscene2dAction* _tmp11_ = NULL;
			_tmp5_ = _action_index;
			_action_index = _tmp5_ + 1;
			_tmp6_ = _action_index;
			_tmp7_ = _action_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _action_list;
			_tmp9_ = _action_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			action = (sdxscenesscene2dAction*) _tmp10_;
			_tmp11_ = action;
			sdx_scenes_scene2d_action_set_actor (_tmp11_, NULL);
			_g_object_unref0 (action);
		}
		_g_object_unref0 (_action_list);
	}
	_tmp12_ = self->actions;
	gee_abstract_collection_clear ((GeeAbstractCollection*) _tmp12_);
}


void sdx_scenes_scene2d_actor_clearListeners (sdxscenesscene2dActor* self) {
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->listeners;
	gee_abstract_collection_clear ((GeeAbstractCollection*) _tmp0_);
	_tmp1_ = self->captureListeners;
	gee_abstract_collection_clear ((GeeAbstractCollection*) _tmp1_);
}


void sdx_scenes_scene2d_actor_clear (sdxscenesscene2dActor* self) {
	g_return_if_fail (self != NULL);
	sdx_scenes_scene2d_actor_clearActions (self);
	sdx_scenes_scene2d_actor_clearListeners (self);
}


gboolean sdx_scenes_scene2d_actor_isDescendantOf (sdxscenesscene2dActor* self, sdxscenesscene2dActor* actor) {
	gboolean result = FALSE;
	sdxscenesscene2dActor* _tmp0_ = NULL;
	sdxscenesscene2dActor* parent = NULL;
	sdxscenesscene2dActor* _tmp3_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (actor != NULL, FALSE);
	_tmp0_ = actor;
	if (_tmp0_ == NULL) {
		GError* _tmp1_ = NULL;
		gboolean _tmp2_ = FALSE;
		_tmp1_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_IllegalArgumentException, "actor cannot be null.");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return _tmp2_;
	}
	_tmp3_ = _g_object_ref0 (self);
	parent = _tmp3_;
	while (TRUE) {
		sdxscenesscene2dActor* _tmp4_ = NULL;
		sdxscenesscene2dActor* _tmp5_ = NULL;
		sdxscenesscene2dActor* _tmp6_ = NULL;
		sdxscenesscene2dActor* _tmp7_ = NULL;
		sdxscenesscene2dGroup* _tmp8_ = NULL;
		sdxscenesscene2dActor* _tmp9_ = NULL;
		_tmp4_ = parent;
		if (_tmp4_ == NULL) {
			result = FALSE;
			_g_object_unref0 (parent);
			return result;
		}
		_tmp5_ = parent;
		_tmp6_ = actor;
		if (_tmp5_ == _tmp6_) {
			result = TRUE;
			_g_object_unref0 (parent);
			return result;
		}
		_tmp7_ = parent;
		_tmp8_ = _tmp7_->priv->_parent;
		_tmp9_ = _g_object_ref0 ((sdxscenesscene2dActor*) _tmp8_);
		_g_object_unref0 (parent);
		parent = _tmp9_;
	}
	_g_object_unref0 (parent);
}


gboolean sdx_scenes_scene2d_actor_isAscendantOf (sdxscenesscene2dActor* self, sdxscenesscene2dActor* actor) {
	gboolean result = FALSE;
	sdxscenesscene2dActor* _tmp0_ = NULL;
	sdxscenesscene2dActor* parent = NULL;
	sdxscenesscene2dActor* _tmp3_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (actor != NULL, FALSE);
	_tmp0_ = actor;
	if (_tmp0_ == NULL) {
		GError* _tmp1_ = NULL;
		gboolean _tmp2_ = FALSE;
		_tmp1_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_IllegalArgumentException, "actor cannot be null.");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return _tmp2_;
	}
	_tmp3_ = _g_object_ref0 (self);
	parent = _tmp3_;
	while (TRUE) {
		sdxscenesscene2dActor* _tmp4_ = NULL;
		sdxscenesscene2dActor* _tmp5_ = NULL;
		sdxscenesscene2dActor* _tmp6_ = NULL;
		sdxscenesscene2dGroup* _tmp7_ = NULL;
		sdxscenesscene2dActor* _tmp8_ = NULL;
		_tmp4_ = actor;
		if (_tmp4_ == NULL) {
			result = FALSE;
			_g_object_unref0 (parent);
			return result;
		}
		_tmp5_ = actor;
		if (_tmp5_ == self) {
			result = TRUE;
			_g_object_unref0 (parent);
			return result;
		}
		_tmp6_ = parent;
		_tmp7_ = _tmp6_->priv->_parent;
		_tmp8_ = _g_object_ref0 ((sdxscenesscene2dActor*) _tmp7_);
		_g_object_unref0 (parent);
		parent = _tmp8_;
	}
	_g_object_unref0 (parent);
}


sdxscenesscene2dActor* sdx_scenes_scene2d_actor_firstAscendant (sdxscenesscene2dActor* self, GType type) {
	sdxscenesscene2dActor* result = NULL;
	sdxscenesscene2dActor* actor = NULL;
	sdxscenesscene2dActor* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = _g_object_ref0 (self);
	actor = _tmp0_;
	{
		gboolean _tmp1_ = FALSE;
		_tmp1_ = TRUE;
		while (TRUE) {
			sdxscenesscene2dActor* _tmp3_ = NULL;
			GType _tmp4_ = 0UL;
			GType _tmp5_ = 0UL;
			sdxscenesscene2dActor* _tmp6_ = NULL;
			sdxscenesscene2dGroup* _tmp7_ = NULL;
			sdxscenesscene2dActor* _tmp8_ = NULL;
			if (!_tmp1_) {
				sdxscenesscene2dActor* _tmp2_ = NULL;
				_tmp2_ = actor;
				if (!(_tmp2_ != NULL)) {
					break;
				}
			}
			_tmp1_ = FALSE;
			_tmp3_ = actor;
			_tmp4_ = G_TYPE_FROM_INSTANCE ((GObject*) _tmp3_);
			_tmp5_ = type;
			if (_tmp4_ == _tmp5_) {
				result = actor;
				return result;
			}
			_tmp6_ = actor;
			_tmp7_ = _tmp6_->priv->_parent;
			_tmp8_ = _g_object_ref0 ((sdxscenesscene2dActor*) _tmp7_);
			_g_object_unref0 (actor);
			actor = _tmp8_;
		}
	}
	result = NULL;
	_g_object_unref0 (actor);
	return result;
}


gboolean sdx_scenes_scene2d_actor_hasParent (sdxscenesscene2dActor* self) {
	gboolean result = FALSE;
	sdxscenesscene2dGroup* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_parent;
	result = _tmp0_ != NULL;
	return result;
}


gboolean sdx_scenes_scene2d_actor_isTouchable (sdxscenesscene2dActor* self) {
	gboolean result = FALSE;
	sdxscenesscene2dTouchable _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_touchable;
	result = _tmp0_ == SDX_SCENES_SCENE2D_TOUCHABLE_enabled;
	return result;
}


gboolean sdx_scenes_scene2d_actor_isVisible (sdxscenesscene2dActor* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->visible;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_setVisible (sdxscenesscene2dActor* self, gboolean visible) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = visible;
	self->visible = _tmp0_;
}


gdouble sdx_scenes_scene2d_actor_getX (sdxscenesscene2dActor* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->x;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_setX (sdxscenesscene2dActor* self, gdouble x) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->x;
	_tmp1_ = x;
	if (_tmp0_ != _tmp1_) {
		gdouble _tmp2_ = 0.0;
		_tmp2_ = x;
		self->x = _tmp2_;
		sdx_scenes_scene2d_actor_positionChanged (self);
	}
}


gdouble sdx_scenes_scene2d_actor_getY (sdxscenesscene2dActor* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->y;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_setY (sdxscenesscene2dActor* self, gdouble y) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->y;
	_tmp1_ = y;
	if (_tmp0_ != _tmp1_) {
		gdouble _tmp2_ = 0.0;
		_tmp2_ = y;
		self->y = _tmp2_;
		sdx_scenes_scene2d_actor_positionChanged (self);
	}
}


void sdx_scenes_scene2d_actor_setPosition (sdxscenesscene2dActor* self, gdouble x, gdouble y) {
	gboolean _tmp0_ = FALSE;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp1_ = self->x;
	_tmp2_ = x;
	if (_tmp1_ != _tmp2_) {
		gdouble _tmp3_ = 0.0;
		gdouble _tmp4_ = 0.0;
		_tmp3_ = self->y;
		_tmp4_ = y;
		_tmp0_ = _tmp3_ != _tmp4_;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		gdouble _tmp5_ = 0.0;
		gdouble _tmp6_ = 0.0;
		_tmp5_ = x;
		self->x = _tmp5_;
		_tmp6_ = y;
		self->y = _tmp6_;
		sdx_scenes_scene2d_actor_positionChanged (self);
	}
}


void sdx_scenes_scene2d_actor_moveBy (sdxscenesscene2dActor* self, gdouble x, gdouble y) {
	gboolean _tmp0_ = FALSE;
	gdouble _tmp1_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp1_ = x;
	if (_tmp1_ != ((gdouble) 0)) {
		_tmp0_ = TRUE;
	} else {
		gdouble _tmp2_ = 0.0;
		_tmp2_ = y;
		_tmp0_ = _tmp2_ != ((gdouble) 0);
	}
	if (_tmp0_) {
		gdouble _tmp3_ = 0.0;
		gdouble _tmp4_ = 0.0;
		gdouble _tmp5_ = 0.0;
		gdouble _tmp6_ = 0.0;
		_tmp3_ = self->x;
		_tmp4_ = x;
		self->x = _tmp3_ + _tmp4_;
		_tmp5_ = self->y;
		_tmp6_ = y;
		self->y = _tmp5_ + _tmp6_;
		sdx_scenes_scene2d_actor_positionChanged (self);
	}
}


gdouble sdx_scenes_scene2d_actor_getWidth (sdxscenesscene2dActor* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->width;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_setWidth (sdxscenesscene2dActor* self, gdouble width) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->width;
	_tmp1_ = width;
	if (_tmp0_ != _tmp1_) {
		gdouble _tmp2_ = 0.0;
		_tmp2_ = width;
		self->width = _tmp2_;
		sdx_scenes_scene2d_actor_sizeChanged (self);
	}
}


gdouble sdx_scenes_scene2d_actor_getHeight (sdxscenesscene2dActor* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->height;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_setHeight (sdxscenesscene2dActor* self, gdouble height) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->height;
	_tmp1_ = height;
	if (_tmp0_ != _tmp1_) {
		gdouble _tmp2_ = 0.0;
		_tmp2_ = height;
		self->height = _tmp2_;
		sdx_scenes_scene2d_actor_sizeChanged (self);
	}
}


gdouble sdx_scenes_scene2d_actor_getTop (sdxscenesscene2dActor* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->y;
	_tmp1_ = self->height;
	result = _tmp0_ + _tmp1_;
	return result;
}


gdouble sdx_scenes_scene2d_actor_getRight (sdxscenesscene2dActor* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->x;
	_tmp1_ = self->width;
	result = _tmp0_ + _tmp1_;
	return result;
}


void sdx_scenes_scene2d_actor_positionChanged (sdxscenesscene2dActor* self) {
	g_return_if_fail (self != NULL);
}


void sdx_scenes_scene2d_actor_sizeChanged (sdxscenesscene2dActor* self) {
	g_return_if_fail (self != NULL);
}


void sdx_scenes_scene2d_actor_rotationChanged (sdxscenesscene2dActor* self) {
	g_return_if_fail (self != NULL);
}


void sdx_scenes_scene2d_actor_setSize (sdxscenesscene2dActor* self, gdouble width, gdouble height) {
	gboolean _tmp0_ = FALSE;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp1_ = self->width;
	_tmp2_ = width;
	if (_tmp1_ != _tmp2_) {
		_tmp0_ = TRUE;
	} else {
		gdouble _tmp3_ = 0.0;
		gdouble _tmp4_ = 0.0;
		_tmp3_ = self->height;
		_tmp4_ = height;
		_tmp0_ = _tmp3_ != _tmp4_;
	}
	if (_tmp0_) {
		gdouble _tmp5_ = 0.0;
		gdouble _tmp6_ = 0.0;
		_tmp5_ = width;
		self->width = _tmp5_;
		_tmp6_ = height;
		self->height = _tmp6_;
		sdx_scenes_scene2d_actor_sizeChanged (self);
	}
}


void sdx_scenes_scene2d_actor_sizeBy (sdxscenesscene2dActor* self, gdouble size) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = size;
	if (_tmp0_ != ((gdouble) 0)) {
		gdouble _tmp1_ = 0.0;
		gdouble _tmp2_ = 0.0;
		gdouble _tmp3_ = 0.0;
		gdouble _tmp4_ = 0.0;
		_tmp1_ = self->width;
		_tmp2_ = size;
		self->width = _tmp1_ + _tmp2_;
		_tmp3_ = self->height;
		_tmp4_ = size;
		self->height = _tmp3_ + _tmp4_;
		sdx_scenes_scene2d_actor_sizeChanged (self);
	}
}


void sdx_scenes_scene2d_actor_setBounds (sdxscenesscene2dActor* self, gdouble x, gdouble y, gdouble width, gdouble height) {
	gboolean _tmp0_ = FALSE;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gboolean _tmp7_ = FALSE;
	gdouble _tmp8_ = 0.0;
	gdouble _tmp9_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp1_ = self->x;
	_tmp2_ = x;
	if (_tmp1_ != _tmp2_) {
		gdouble _tmp3_ = 0.0;
		gdouble _tmp4_ = 0.0;
		_tmp3_ = self->y;
		_tmp4_ = y;
		_tmp0_ = _tmp3_ != _tmp4_;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		gdouble _tmp5_ = 0.0;
		gdouble _tmp6_ = 0.0;
		_tmp5_ = x;
		self->x = _tmp5_;
		_tmp6_ = y;
		self->y = _tmp6_;
		sdx_scenes_scene2d_actor_positionChanged (self);
	}
	_tmp8_ = self->width;
	_tmp9_ = width;
	if (_tmp8_ != _tmp9_) {
		_tmp7_ = TRUE;
	} else {
		gdouble _tmp10_ = 0.0;
		gdouble _tmp11_ = 0.0;
		_tmp10_ = self->height;
		_tmp11_ = height;
		_tmp7_ = _tmp10_ != _tmp11_;
	}
	if (_tmp7_) {
		gdouble _tmp12_ = 0.0;
		gdouble _tmp13_ = 0.0;
		_tmp12_ = width;
		self->width = _tmp12_;
		_tmp13_ = height;
		self->height = _tmp13_;
		sdx_scenes_scene2d_actor_sizeChanged (self);
	}
}


gdouble sdx_scenes_scene2d_actor_getOriginX (sdxscenesscene2dActor* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->originX;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_setOriginX (sdxscenesscene2dActor* self, gdouble originX) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = originX;
	self->originX = _tmp0_;
}


gdouble sdx_scenes_scene2d_actor_getOriginY (sdxscenesscene2dActor* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->originY;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_setOriginY (sdxscenesscene2dActor* self, gdouble originY) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = originY;
	self->originY = _tmp0_;
}


void sdx_scenes_scene2d_actor_setOrigin (sdxscenesscene2dActor* self, gdouble originX, gdouble originY) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = originX;
	self->originX = _tmp0_;
	_tmp1_ = originY;
	self->originY = _tmp1_;
}


gdouble sdx_scenes_scene2d_actor_getScaleX (sdxscenesscene2dActor* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->scaleX;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_setScaleX (sdxscenesscene2dActor* self, gdouble scaleX) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = scaleX;
	self->scaleX = _tmp0_;
}


gdouble sdx_scenes_scene2d_actor_getScaleY (sdxscenesscene2dActor* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->scaleY;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_setScaleY (sdxscenesscene2dActor* self, gdouble scaleXY) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = scaleXY;
	self->scaleX = _tmp0_;
	_tmp1_ = scaleXY;
	self->scaleY = _tmp1_;
}


void sdx_scenes_scene2d_actor_setScale (sdxscenesscene2dActor* self, gdouble scaleX, gdouble scaleY) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = scaleY;
	if (_tmp0_ == ((gdouble) 0)) {
		gdouble _tmp1_ = 0.0;
		_tmp1_ = scaleX;
		scaleY = _tmp1_;
	}
	_tmp2_ = scaleX;
	self->scaleX = _tmp2_;
	_tmp3_ = scaleY;
	self->scaleY = _tmp3_;
}


void sdx_scenes_scene2d_actor_scaleBy (sdxscenesscene2dActor* self, gdouble scaleX, gdouble scaleY) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->scaleX;
	_tmp1_ = scaleX;
	self->scaleX = _tmp0_ + _tmp1_;
	_tmp2_ = self->scaleY;
	_tmp3_ = scaleY;
	self->scaleY = _tmp2_ + _tmp3_;
}


gdouble sdx_scenes_scene2d_actor_getRotation (sdxscenesscene2dActor* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->rotation;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_setRotation (sdxscenesscene2dActor* self, gdouble degrees) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->rotation;
	_tmp1_ = degrees;
	if (_tmp0_ != _tmp1_) {
		gdouble _tmp2_ = 0.0;
		_tmp2_ = degrees;
		self->rotation = _tmp2_;
	}
	sdx_scenes_scene2d_actor_rotationChanged (self);
}


void sdx_scenes_scene2d_actor_rotateBy (sdxscenesscene2dActor* self, gdouble amountInDegrees) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = amountInDegrees;
	if (_tmp0_ != ((gdouble) 0)) {
		gdouble _tmp1_ = 0.0;
		gdouble _tmp2_ = 0.0;
		_tmp1_ = self->rotation;
		_tmp2_ = amountInDegrees;
		self->rotation = _tmp1_ + _tmp2_;
		sdx_scenes_scene2d_actor_rotationChanged (self);
	}
}


void sdx_scenes_scene2d_actor_toFront (sdxscenesscene2dActor* self) {
	g_return_if_fail (self != NULL);
	sdx_scenes_scene2d_actor_setZIndex (self, G_MAXINT);
}


void sdx_scenes_scene2d_actor_toBack (sdxscenesscene2dActor* self) {
	g_return_if_fail (self != NULL);
	sdx_scenes_scene2d_actor_setZIndex (self, 0);
}


void sdx_scenes_scene2d_actor_setZIndex (sdxscenesscene2dActor* self, gint index) {
	gint _tmp0_ = 0;
	sdxscenesscene2dGroup* _tmp2_ = NULL;
	GeeArrayList* children = NULL;
	sdxscenesscene2dGroup* _tmp3_ = NULL;
	GeeArrayList* _tmp4_ = NULL;
	GeeArrayList* _tmp5_ = NULL;
	GeeArrayList* _tmp6_ = NULL;
	GeeArrayList* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	GeeArrayList* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	gint _tmp13_ = 0;
	gdouble _tmp14_ = 0.0;
	GeeArrayList* _tmp15_ = NULL;
	gint _tmp16_ = 0;
	gpointer _tmp17_ = NULL;
	sdxscenesscene2dActor* _tmp18_ = NULL;
	gboolean _tmp19_ = FALSE;
	GeeArrayList* _tmp20_ = NULL;
	gboolean _tmp21_ = FALSE;
	GeeArrayList* _tmp22_ = NULL;
	gint _tmp23_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = index;
	if (_tmp0_ < 0) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_IllegalArgumentException, "ZIndex cannot be < 0.");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = self->priv->_parent;
	if (_tmp2_ == NULL) {
		return;
	}
	_tmp3_ = self->priv->_parent;
	_tmp4_ = sdx_scenes_scene2d_group_get_children (_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = _g_object_ref0 (_tmp5_);
	children = _tmp6_;
	_tmp7_ = children;
	_tmp8_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp7_);
	_tmp9_ = _tmp8_;
	if (_tmp9_ == 1) {
		_g_object_unref0 (children);
		return;
	}
	_tmp10_ = index;
	_tmp11_ = children;
	_tmp12_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp11_);
	_tmp13_ = _tmp12_;
	_tmp14_ = fmin ((gdouble) _tmp10_, (gdouble) (_tmp13_ - 1));
	index = (gint) _tmp14_;
	_tmp15_ = children;
	_tmp16_ = index;
	_tmp17_ = gee_abstract_list_get ((GeeAbstractList*) _tmp15_, _tmp16_);
	_tmp18_ = (sdxscenesscene2dActor*) _tmp17_;
	_tmp19_ = _tmp18_ == self;
	_g_object_unref0 (_tmp18_);
	if (_tmp19_) {
		_g_object_unref0 (children);
		return;
	}
	_tmp20_ = children;
	_tmp21_ = gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp20_, self);
	if (!_tmp21_) {
		_g_object_unref0 (children);
		return;
	}
	_tmp22_ = children;
	_tmp23_ = index;
	gee_abstract_list_insert ((GeeAbstractList*) _tmp22_, _tmp23_, self);
	_g_object_unref0 (children);
}


gint sdx_scenes_scene2d_actor_getZIndex (sdxscenesscene2dActor* self) {
	gint result = 0;
	sdxscenesscene2dGroup* _tmp0_ = NULL;
	sdxscenesscene2dGroup* _tmp1_ = NULL;
	GeeArrayList* _tmp2_ = NULL;
	GeeArrayList* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_parent;
	if (_tmp0_ == NULL) {
		result = -1;
		return result;
	}
	_tmp1_ = self->priv->_parent;
	_tmp2_ = sdx_scenes_scene2d_group_get_children (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = gee_abstract_list_index_of ((GeeAbstractList*) _tmp3_, self);
	result = _tmp4_;
	return result;
}


sdxmathVector2* sdx_scenes_scene2d_actor_screenToLocalCoordinates (sdxscenesscene2dActor* self, sdxmathVector2* screenCoords) {
	sdxmathVector2* result = NULL;
	sdxscenesscene2dStage* _tmp0_ = NULL;
	sdxscenesscene2dStage* _tmp3_ = NULL;
	sdxmathVector2* _tmp4_ = NULL;
	sdxmathVector2* _tmp5_ = NULL;
	sdxmathVector2* _tmp6_ = NULL;
	sdxmathVector2* _tmp7_ = NULL;
	sdxmathVector2* _tmp8_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (screenCoords != NULL, NULL);
	_tmp0_ = self->priv->_stage;
	if (_tmp0_ == NULL) {
		sdxmathVector2* _tmp1_ = NULL;
		sdxmathVector2* _tmp2_ = NULL;
		_tmp1_ = screenCoords;
		_tmp2_ = _g_object_ref0 (_tmp1_);
		result = _tmp2_;
		return result;
	}
	_tmp3_ = self->priv->_stage;
	_tmp4_ = screenCoords;
	_tmp5_ = sdx_scenes_scene2d_stage_screenToStageCoordinates (_tmp3_, _tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = sdx_scenes_scene2d_actor_stageToLocalCoordinates (self, _tmp6_);
	_tmp8_ = _tmp7_;
	_g_object_unref0 (_tmp6_);
	result = _tmp8_;
	return result;
}


sdxmathVector2* sdx_scenes_scene2d_actor_stageToLocalCoordinates (sdxscenesscene2dActor* self, sdxmathVector2* stageCoords) {
	sdxmathVector2* result = NULL;
	sdxscenesscene2dGroup* _tmp0_ = NULL;
	sdxmathVector2* _tmp5_ = NULL;
	sdxmathVector2* _tmp6_ = NULL;
	sdxmathVector2* _tmp7_ = NULL;
	sdxmathVector2* _tmp8_ = NULL;
	sdxmathVector2* _tmp9_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (stageCoords != NULL, NULL);
	_tmp0_ = self->priv->_parent;
	if (_tmp0_ != NULL) {
		sdxscenesscene2dGroup* _tmp1_ = NULL;
		sdxmathVector2* _tmp2_ = NULL;
		sdxmathVector2* _tmp3_ = NULL;
		sdxmathVector2* _tmp4_ = NULL;
		_tmp1_ = self->priv->_parent;
		_tmp2_ = stageCoords;
		_tmp3_ = sdx_scenes_scene2d_actor_stageToLocalCoordinates ((sdxscenesscene2dActor*) _tmp1_, _tmp2_);
		_tmp4_ = _tmp3_;
		_g_object_unref0 (_tmp4_);
	}
	_tmp5_ = stageCoords;
	_tmp6_ = sdx_scenes_scene2d_actor_parentToLocalCoordinates (self, _tmp5_);
	_tmp7_ = _tmp6_;
	_g_object_unref0 (_tmp7_);
	_tmp8_ = stageCoords;
	_tmp9_ = _g_object_ref0 (_tmp8_);
	result = _tmp9_;
	return result;
}


sdxmathVector2* sdx_scenes_scene2d_actor_localToStageCoordinates (sdxscenesscene2dActor* self, sdxmathVector2* localCoords) {
	sdxmathVector2* result = NULL;
	sdxmathVector2* _tmp0_ = NULL;
	sdxmathVector2* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (localCoords != NULL, NULL);
	_tmp0_ = localCoords;
	_tmp1_ = sdx_scenes_scene2d_actor_localToAscendantCoordinates (self, NULL, _tmp0_);
	result = _tmp1_;
	return result;
}


sdxmathVector2* sdx_scenes_scene2d_actor_localToParentCoordinates (sdxscenesscene2dActor* self, sdxmathVector2* localCoords) {
	sdxmathVector2* result = NULL;
	gdouble _tmp0_ = 0.0;
	sdxmathVector2* _tmp52_ = NULL;
	sdxmathVector2* _tmp53_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (localCoords != NULL, NULL);
	_tmp0_ = self->rotation;
	if (_tmp0_ == ((gdouble) 0)) {
		gboolean _tmp1_ = FALSE;
		gdouble _tmp2_ = 0.0;
		_tmp2_ = self->scaleX;
		if (_tmp2_ == ((gdouble) 1)) {
			gdouble _tmp3_ = 0.0;
			_tmp3_ = self->scaleY;
			_tmp1_ = _tmp3_ == ((gdouble) 1);
		} else {
			_tmp1_ = FALSE;
		}
		if (_tmp1_) {
			sdxmathVector2* _tmp4_ = NULL;
			sdxmathVector2* _tmp5_ = NULL;
			gdouble _tmp6_ = 0.0;
			gdouble _tmp7_ = 0.0;
			sdxmathVector2* _tmp8_ = NULL;
			sdxmathVector2* _tmp9_ = NULL;
			gdouble _tmp10_ = 0.0;
			gdouble _tmp11_ = 0.0;
			_tmp4_ = localCoords;
			_tmp5_ = localCoords;
			_tmp6_ = _tmp5_->x;
			_tmp7_ = self->x;
			_tmp5_->x = _tmp6_ + _tmp7_;
			_tmp8_ = localCoords;
			_tmp9_ = localCoords;
			_tmp10_ = _tmp9_->y;
			_tmp11_ = self->y;
			_tmp9_->y = _tmp10_ + _tmp11_;
		} else {
			sdxmathVector2* _tmp12_ = NULL;
			sdxmathVector2* _tmp13_ = NULL;
			gdouble _tmp14_ = 0.0;
			gdouble _tmp15_ = 0.0;
			gdouble _tmp16_ = 0.0;
			gdouble _tmp17_ = 0.0;
			gdouble _tmp18_ = 0.0;
			sdxmathVector2* _tmp19_ = NULL;
			sdxmathVector2* _tmp20_ = NULL;
			gdouble _tmp21_ = 0.0;
			gdouble _tmp22_ = 0.0;
			gdouble _tmp23_ = 0.0;
			gdouble _tmp24_ = 0.0;
			gdouble _tmp25_ = 0.0;
			_tmp12_ = localCoords;
			_tmp13_ = localCoords;
			_tmp14_ = _tmp13_->x;
			_tmp15_ = self->originX;
			_tmp16_ = self->scaleX;
			_tmp17_ = self->originX;
			_tmp18_ = self->x;
			_tmp12_->x = (((_tmp14_ - _tmp15_) * _tmp16_) + _tmp17_) + _tmp18_;
			_tmp19_ = localCoords;
			_tmp20_ = localCoords;
			_tmp21_ = _tmp20_->y;
			_tmp22_ = self->originY;
			_tmp23_ = self->scaleY;
			_tmp24_ = self->originY;
			_tmp25_ = self->y;
			_tmp19_->y = (((_tmp21_ - _tmp22_) * _tmp23_) + _tmp24_) + _tmp25_;
		}
	} else {
		gdouble cos1 = 0.0;
		gdouble _tmp26_ = 0.0;
		gdouble _tmp27_ = 0.0;
		gdouble sin1 = 0.0;
		gdouble _tmp28_ = 0.0;
		gdouble _tmp29_ = 0.0;
		gdouble tox = 0.0;
		sdxmathVector2* _tmp30_ = NULL;
		gdouble _tmp31_ = 0.0;
		gdouble _tmp32_ = 0.0;
		gdouble _tmp33_ = 0.0;
		gdouble toy = 0.0;
		sdxmathVector2* _tmp34_ = NULL;
		gdouble _tmp35_ = 0.0;
		gdouble _tmp36_ = 0.0;
		gdouble _tmp37_ = 0.0;
		sdxmathVector2* _tmp38_ = NULL;
		gdouble _tmp39_ = 0.0;
		gdouble _tmp40_ = 0.0;
		gdouble _tmp41_ = 0.0;
		gdouble _tmp42_ = 0.0;
		gdouble _tmp43_ = 0.0;
		gdouble _tmp44_ = 0.0;
		sdxmathVector2* _tmp45_ = NULL;
		gdouble _tmp46_ = 0.0;
		gdouble _tmp47_ = 0.0;
		gdouble _tmp48_ = 0.0;
		gdouble _tmp49_ = 0.0;
		gdouble _tmp50_ = 0.0;
		gdouble _tmp51_ = 0.0;
		_tmp26_ = self->rotation;
		_tmp27_ = cos (_tmp26_ * SDX_SCENES_SCENE2D_degreesToRadians);
		cos1 = _tmp27_;
		_tmp28_ = self->rotation;
		_tmp29_ = sin (_tmp28_ * SDX_SCENES_SCENE2D_degreesToRadians);
		sin1 = _tmp29_;
		_tmp30_ = localCoords;
		_tmp31_ = _tmp30_->x;
		_tmp32_ = self->originX;
		_tmp33_ = self->scaleX;
		tox = (_tmp31_ - _tmp32_) * _tmp33_;
		_tmp34_ = localCoords;
		_tmp35_ = _tmp34_->y;
		_tmp36_ = self->originY;
		_tmp37_ = self->scaleY;
		toy = (_tmp35_ - _tmp36_) * _tmp37_;
		_tmp38_ = localCoords;
		_tmp39_ = tox;
		_tmp40_ = cos1;
		_tmp41_ = toy;
		_tmp42_ = sin1;
		_tmp43_ = self->originX;
		_tmp44_ = self->x;
		_tmp38_->x = (((_tmp39_ * _tmp40_) + (_tmp41_ * _tmp42_)) + _tmp43_) + _tmp44_;
		_tmp45_ = localCoords;
		_tmp46_ = tox;
		_tmp47_ = sin1;
		_tmp48_ = toy;
		_tmp49_ = cos1;
		_tmp50_ = self->originY;
		_tmp51_ = self->y;
		_tmp45_->y = (((_tmp46_ * (-_tmp47_)) + (_tmp48_ * _tmp49_)) + _tmp50_) + _tmp51_;
	}
	_tmp52_ = localCoords;
	_tmp53_ = _g_object_ref0 (_tmp52_);
	result = _tmp53_;
	return result;
}


sdxmathVector2* sdx_scenes_scene2d_actor_localToAscendantCoordinates (sdxscenesscene2dActor* self, sdxscenesscene2dActor* ascendant, sdxmathVector2* localCoords) {
	sdxmathVector2* result = NULL;
	sdxscenesscene2dActor* actor = NULL;
	sdxscenesscene2dActor* _tmp0_ = NULL;
	sdxmathVector2* _tmp11_ = NULL;
	sdxmathVector2* _tmp12_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (ascendant != NULL, NULL);
	g_return_val_if_fail (localCoords != NULL, NULL);
	_tmp0_ = _g_object_ref0 (self);
	actor = _tmp0_;
	while (TRUE) {
		sdxscenesscene2dActor* _tmp1_ = NULL;
		sdxscenesscene2dActor* _tmp2_ = NULL;
		sdxmathVector2* _tmp3_ = NULL;
		sdxmathVector2* _tmp4_ = NULL;
		sdxmathVector2* _tmp5_ = NULL;
		sdxscenesscene2dActor* _tmp6_ = NULL;
		sdxscenesscene2dGroup* _tmp7_ = NULL;
		sdxscenesscene2dActor* _tmp8_ = NULL;
		sdxscenesscene2dActor* _tmp9_ = NULL;
		sdxscenesscene2dActor* _tmp10_ = NULL;
		_tmp1_ = actor;
		if (!(_tmp1_ != NULL)) {
			break;
		}
		_tmp2_ = actor;
		_tmp3_ = localCoords;
		_tmp4_ = sdx_scenes_scene2d_actor_localToParentCoordinates (_tmp2_, _tmp3_);
		_tmp5_ = _tmp4_;
		_g_object_unref0 (_tmp5_);
		_tmp6_ = actor;
		_tmp7_ = _tmp6_->priv->_parent;
		_tmp8_ = _g_object_ref0 ((sdxscenesscene2dActor*) _tmp7_);
		_g_object_unref0 (actor);
		actor = _tmp8_;
		_tmp9_ = actor;
		_tmp10_ = ascendant;
		if (_tmp9_ == _tmp10_) {
			break;
		}
	}
	_tmp11_ = localCoords;
	_tmp12_ = _g_object_ref0 (_tmp11_);
	result = _tmp12_;
	_g_object_unref0 (actor);
	return result;
}


sdxmathVector2* sdx_scenes_scene2d_actor_parentToLocalCoordinates (sdxscenesscene2dActor* self, sdxmathVector2* parentCoords) {
	sdxmathVector2* result = NULL;
	gdouble childX = 0.0;
	gdouble _tmp0_ = 0.0;
	gdouble childY = 0.0;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	sdxmathVector2* _tmp54_ = NULL;
	sdxmathVector2* _tmp55_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (parentCoords != NULL, NULL);
	_tmp0_ = self->x;
	childX = _tmp0_;
	_tmp1_ = self->y;
	childY = _tmp1_;
	_tmp2_ = self->rotation;
	if (_tmp2_ == ((gdouble) 0)) {
		gboolean _tmp3_ = FALSE;
		gdouble _tmp4_ = 0.0;
		_tmp4_ = self->scaleX;
		if (_tmp4_ == ((gdouble) 1)) {
			gdouble _tmp5_ = 0.0;
			_tmp5_ = self->scaleY;
			_tmp3_ = _tmp5_ == ((gdouble) 1);
		} else {
			_tmp3_ = FALSE;
		}
		if (_tmp3_) {
			sdxmathVector2* _tmp6_ = NULL;
			sdxmathVector2* _tmp7_ = NULL;
			gdouble _tmp8_ = 0.0;
			gdouble _tmp9_ = 0.0;
			sdxmathVector2* _tmp10_ = NULL;
			sdxmathVector2* _tmp11_ = NULL;
			gdouble _tmp12_ = 0.0;
			gdouble _tmp13_ = 0.0;
			_tmp6_ = parentCoords;
			_tmp7_ = parentCoords;
			_tmp8_ = _tmp7_->x;
			_tmp9_ = childX;
			_tmp7_->x = _tmp8_ - _tmp9_;
			_tmp10_ = parentCoords;
			_tmp11_ = parentCoords;
			_tmp12_ = _tmp11_->y;
			_tmp13_ = childY;
			_tmp11_->y = _tmp12_ - _tmp13_;
		} else {
			sdxmathVector2* _tmp14_ = NULL;
			sdxmathVector2* _tmp15_ = NULL;
			gdouble _tmp16_ = 0.0;
			gdouble _tmp17_ = 0.0;
			gdouble _tmp18_ = 0.0;
			gdouble _tmp19_ = 0.0;
			gdouble _tmp20_ = 0.0;
			sdxmathVector2* _tmp21_ = NULL;
			sdxmathVector2* _tmp22_ = NULL;
			gdouble _tmp23_ = 0.0;
			gdouble _tmp24_ = 0.0;
			gdouble _tmp25_ = 0.0;
			gdouble _tmp26_ = 0.0;
			gdouble _tmp27_ = 0.0;
			_tmp14_ = parentCoords;
			_tmp15_ = parentCoords;
			_tmp16_ = _tmp15_->x;
			_tmp17_ = childX;
			_tmp18_ = self->originX;
			_tmp19_ = self->scaleX;
			_tmp20_ = self->originX;
			_tmp14_->x = (((_tmp16_ - _tmp17_) - _tmp18_) / _tmp19_) + _tmp20_;
			_tmp21_ = parentCoords;
			_tmp22_ = parentCoords;
			_tmp23_ = _tmp22_->y;
			_tmp24_ = childY;
			_tmp25_ = self->originY;
			_tmp26_ = self->scaleY;
			_tmp27_ = self->originY;
			_tmp21_->y = (((_tmp23_ - _tmp24_) - _tmp25_) / _tmp26_) + _tmp27_;
		}
	} else {
		gdouble cos1 = 0.0;
		gdouble _tmp28_ = 0.0;
		gdouble _tmp29_ = 0.0;
		gdouble sin1 = 0.0;
		gdouble _tmp30_ = 0.0;
		gdouble _tmp31_ = 0.0;
		gdouble tox = 0.0;
		sdxmathVector2* _tmp32_ = NULL;
		gdouble _tmp33_ = 0.0;
		gdouble _tmp34_ = 0.0;
		gdouble _tmp35_ = 0.0;
		gdouble toy = 0.0;
		sdxmathVector2* _tmp36_ = NULL;
		gdouble _tmp37_ = 0.0;
		gdouble _tmp38_ = 0.0;
		gdouble _tmp39_ = 0.0;
		sdxmathVector2* _tmp40_ = NULL;
		gdouble _tmp41_ = 0.0;
		gdouble _tmp42_ = 0.0;
		gdouble _tmp43_ = 0.0;
		gdouble _tmp44_ = 0.0;
		gdouble _tmp45_ = 0.0;
		gdouble _tmp46_ = 0.0;
		sdxmathVector2* _tmp47_ = NULL;
		gdouble _tmp48_ = 0.0;
		gdouble _tmp49_ = 0.0;
		gdouble _tmp50_ = 0.0;
		gdouble _tmp51_ = 0.0;
		gdouble _tmp52_ = 0.0;
		gdouble _tmp53_ = 0.0;
		_tmp28_ = self->rotation;
		_tmp29_ = cos (_tmp28_ * SDX_SCENES_SCENE2D_degreesToRadians);
		cos1 = _tmp29_;
		_tmp30_ = self->rotation;
		_tmp31_ = sin (_tmp30_ * SDX_SCENES_SCENE2D_degreesToRadians);
		sin1 = _tmp31_;
		_tmp32_ = parentCoords;
		_tmp33_ = _tmp32_->x;
		_tmp34_ = childX;
		_tmp35_ = self->originX;
		tox = (_tmp33_ - _tmp34_) - _tmp35_;
		_tmp36_ = parentCoords;
		_tmp37_ = _tmp36_->y;
		_tmp38_ = childY;
		_tmp39_ = self->originY;
		toy = (_tmp37_ - _tmp38_) - _tmp39_;
		_tmp40_ = parentCoords;
		_tmp41_ = tox;
		_tmp42_ = cos1;
		_tmp43_ = toy;
		_tmp44_ = sin1;
		_tmp45_ = self->scaleX;
		_tmp46_ = self->originX;
		_tmp40_->x = (((_tmp41_ * _tmp42_) + (_tmp43_ * _tmp44_)) / _tmp45_) + _tmp46_;
		_tmp47_ = parentCoords;
		_tmp48_ = tox;
		_tmp49_ = sin1;
		_tmp50_ = toy;
		_tmp51_ = cos1;
		_tmp52_ = self->scaleY;
		_tmp53_ = self->originY;
		_tmp47_->y = (((_tmp48_ * (-_tmp49_)) + (_tmp50_ * _tmp51_)) / _tmp52_) + _tmp53_;
	}
	_tmp54_ = parentCoords;
	_tmp55_ = _g_object_ref0 (_tmp54_);
	result = _tmp55_;
	return result;
}


sdxscenesscene2dActor* sdx_scenes_scene2d_actor_construct (GType object_type) {
	sdxscenesscene2dActor * self = NULL;
	self = (sdxscenesscene2dActor*) g_object_new (object_type, NULL);
	return self;
}


sdxscenesscene2dActor* sdx_scenes_scene2d_actor_new (void) {
	return sdx_scenes_scene2d_actor_construct (SDX_SCENES_SCENE2D_TYPE_ACTOR);
}


sdxscenesscene2dStage* sdx_scenes_scene2d_actor_get_stage (sdxscenesscene2dActor* self) {
	sdxscenesscene2dStage* result;
	sdxscenesscene2dStage* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_stage;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_set_stage (sdxscenesscene2dActor* self, sdxscenesscene2dStage* value) {
	sdxscenesscene2dStage* _tmp0_ = NULL;
	sdxscenesscene2dStage* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_stage);
	self->priv->_stage = _tmp1_;
	g_object_notify ((GObject *) self, "stage");
}


sdxscenesscene2dGroup* sdx_scenes_scene2d_actor_get_parent (sdxscenesscene2dActor* self) {
	sdxscenesscene2dGroup* result;
	sdxscenesscene2dGroup* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_parent;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_set_parent (sdxscenesscene2dActor* self, sdxscenesscene2dGroup* value) {
	sdxscenesscene2dGroup* _tmp0_ = NULL;
	sdxscenesscene2dGroup* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_parent);
	self->priv->_parent = _tmp1_;
	g_object_notify ((GObject *) self, "parent");
}


sdxscenesscene2dTouchable sdx_scenes_scene2d_actor_get_touchable (sdxscenesscene2dActor* self) {
	sdxscenesscene2dTouchable result;
	sdxscenesscene2dTouchable _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_touchable;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_set_touchable (sdxscenesscene2dActor* self, sdxscenesscene2dTouchable value) {
	sdxscenesscene2dTouchable _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_touchable = _tmp0_;
	g_object_notify ((GObject *) self, "touchable");
}


GObject* sdx_scenes_scene2d_actor_get_userObject (sdxscenesscene2dActor* self) {
	GObject* result;
	GObject* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_userObject;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_set_userObject (sdxscenesscene2dActor* self, GObject* value) {
	GObject* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_userObject);
	self->priv->_userObject = _tmp1_;
	g_object_notify ((GObject *) self, "userObject");
}


sdxgraphicsColor* sdx_scenes_scene2d_actor_get_color (sdxscenesscene2dActor* self) {
	sdxgraphicsColor* result;
	sdxgraphicsColor* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_color;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_set_color (sdxscenesscene2dActor* self, sdxgraphicsColor* value) {
	sdxgraphicsColor* _tmp0_ = NULL;
	sdxgraphicsColor* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_color);
	self->priv->_color = _tmp1_;
	g_object_notify ((GObject *) self, "color");
}


const gchar* sdx_scenes_scene2d_actor_get_name (sdxscenesscene2dActor* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_actor_set_name (sdxscenesscene2dActor* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp1_;
	g_object_notify ((GObject *) self, "name");
}


static void sdx_scenes_scene2d_actor_class_init (sdxscenesscene2dActorClass * klass) {
	sdx_scenes_scene2d_actor_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (sdxscenesscene2dActorPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_sdx_scenes_scene2d_actor_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_sdx_scenes_scene2d_actor_set_property;
	G_OBJECT_CLASS (klass)->finalize = sdx_scenes_scene2d_actor_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_SCENES_SCENE2D_ACTOR_STAGE, g_param_spec_object ("stage", "stage", "stage", SDX_SCENES_SCENE2D_TYPE_STAGE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_SCENES_SCENE2D_ACTOR_PARENT, g_param_spec_object ("parent", "parent", "parent", SDX_SCENES_SCENE2D_TYPE_GROUP, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_SCENES_SCENE2D_ACTOR_TOUCHABLE, g_param_spec_enum ("touchable", "touchable", "touchable", SDX_SCENES_SCENE2D_TYPE_TOUCHABLE, SDX_SCENES_SCENE2D_TOUCHABLE_enabled, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_SCENES_SCENE2D_ACTOR_USER_OBJECT, g_param_spec_object ("userObject", "userObject", "userObject", G_TYPE_OBJECT, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_SCENES_SCENE2D_ACTOR_COLOR, g_param_spec_object ("color", "color", "color", SDX_GRAPHICS_TYPE_COLOR, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_SCENES_SCENE2D_ACTOR_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void sdx_scenes_scene2d_actor_instance_init (sdxscenesscene2dActor * self) {
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	GeeArrayList* _tmp2_ = NULL;
	self->priv = SDX_SCENES_SCENE2D_ACTOR_GET_PRIVATE (self);
	self->priv->_touchable = SDX_SCENES_SCENE2D_TOUCHABLE_enabled;
	_tmp0_ = gee_array_list_new (SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
	self->listeners = _tmp0_;
	_tmp1_ = gee_array_list_new (SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
	self->captureListeners = _tmp1_;
	_tmp2_ = gee_array_list_new (SDX_SCENES_SCENE2D_TYPE_ACTION, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
	self->actions = _tmp2_;
	self->visible = TRUE;
	self->scaleX = (gdouble) 1;
	self->scaleY = (gdouble) 1;
}


static void sdx_scenes_scene2d_actor_finalize (GObject* obj) {
	sdxscenesscene2dActor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActor);
	_g_object_unref0 (self->priv->_stage);
	_g_object_unref0 (self->priv->_parent);
	_g_object_unref0 (self->priv->_userObject);
	_g_object_unref0 (self->priv->_color);
	_g_free0 (self->priv->_name);
	_g_object_unref0 (self->listeners);
	_g_object_unref0 (self->captureListeners);
	_g_object_unref0 (self->actions);
	G_OBJECT_CLASS (sdx_scenes_scene2d_actor_parent_class)->finalize (obj);
}


GType sdx_scenes_scene2d_actor_get_type (void) {
	static volatile gsize sdx_scenes_scene2d_actor_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_scenes_scene2d_actor_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (sdxscenesscene2dActorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sdx_scenes_scene2d_actor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (sdxscenesscene2dActor), 0, (GInstanceInitFunc) sdx_scenes_scene2d_actor_instance_init, NULL };
		GType sdx_scenes_scene2d_actor_type_id;
		sdx_scenes_scene2d_actor_type_id = g_type_register_static (G_TYPE_OBJECT, "sdxscenesscene2dActor", &g_define_type_info, 0);
		g_once_init_leave (&sdx_scenes_scene2d_actor_type_id__volatile, sdx_scenes_scene2d_actor_type_id);
	}
	return sdx_scenes_scene2d_actor_type_id__volatile;
}


static void _vala_sdx_scenes_scene2d_actor_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	sdxscenesscene2dActor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActor);
	switch (property_id) {
		case SDX_SCENES_SCENE2D_ACTOR_STAGE:
		g_value_set_object (value, sdx_scenes_scene2d_actor_get_stage (self));
		break;
		case SDX_SCENES_SCENE2D_ACTOR_PARENT:
		g_value_set_object (value, sdx_scenes_scene2d_actor_get_parent (self));
		break;
		case SDX_SCENES_SCENE2D_ACTOR_TOUCHABLE:
		g_value_set_enum (value, sdx_scenes_scene2d_actor_get_touchable (self));
		break;
		case SDX_SCENES_SCENE2D_ACTOR_USER_OBJECT:
		g_value_set_object (value, sdx_scenes_scene2d_actor_get_userObject (self));
		break;
		case SDX_SCENES_SCENE2D_ACTOR_COLOR:
		g_value_set_object (value, sdx_scenes_scene2d_actor_get_color (self));
		break;
		case SDX_SCENES_SCENE2D_ACTOR_NAME:
		g_value_set_string (value, sdx_scenes_scene2d_actor_get_name (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_sdx_scenes_scene2d_actor_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	sdxscenesscene2dActor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActor);
	switch (property_id) {
		case SDX_SCENES_SCENE2D_ACTOR_STAGE:
		sdx_scenes_scene2d_actor_set_stage (self, g_value_get_object (value));
		break;
		case SDX_SCENES_SCENE2D_ACTOR_PARENT:
		sdx_scenes_scene2d_actor_set_parent (self, g_value_get_object (value));
		break;
		case SDX_SCENES_SCENE2D_ACTOR_TOUCHABLE:
		sdx_scenes_scene2d_actor_set_touchable (self, g_value_get_enum (value));
		break;
		case SDX_SCENES_SCENE2D_ACTOR_USER_OBJECT:
		sdx_scenes_scene2d_actor_set_userObject (self, g_value_get_object (value));
		break;
		case SDX_SCENES_SCENE2D_ACTOR_COLOR:
		sdx_scenes_scene2d_actor_set_color (self, g_value_get_object (value));
		break;
		case SDX_SCENES_SCENE2D_ACTOR_NAME:
		sdx_scenes_scene2d_actor_set_name (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



