/* Group.c generated by valac 0.34.9, the Vala compiler
 * generated from Group.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>


#define SDX_SCENES_SCENE2D_TYPE_CULLABLE (sdx_scenes_scene2d_cullable_get_type ())
#define SDX_SCENES_SCENE2D_CULLABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_CULLABLE, sdxscenesscene2dCullable))
#define SDX_SCENES_SCENE2D_IS_CULLABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_CULLABLE))
#define SDX_SCENES_SCENE2D_CULLABLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SDX_SCENES_SCENE2D_TYPE_CULLABLE, sdxscenesscene2dCullableIface))

typedef struct _sdxscenesscene2dCullable sdxscenesscene2dCullable;
typedef struct _sdxscenesscene2dCullableIface sdxscenesscene2dCullableIface;

#define SDX_MATH_TYPE_RECTANGLE (sdx_math_rectangle_get_type ())
#define SDX_MATH_RECTANGLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_MATH_TYPE_RECTANGLE, sdxmathRectangle))
#define SDX_MATH_RECTANGLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_MATH_TYPE_RECTANGLE, sdxmathRectangleClass))
#define SDX_MATH_IS_RECTANGLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_MATH_TYPE_RECTANGLE))
#define SDX_MATH_IS_RECTANGLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_MATH_TYPE_RECTANGLE))
#define SDX_MATH_RECTANGLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_MATH_TYPE_RECTANGLE, sdxmathRectangleClass))

typedef struct _sdxmathRectangle sdxmathRectangle;
typedef struct _sdxmathRectangleClass sdxmathRectangleClass;

#define SDX_SCENES_SCENE2D_TYPE_ACTOR (sdx_scenes_scene2d_actor_get_type ())
#define SDX_SCENES_SCENE2D_ACTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActor))
#define SDX_SCENES_SCENE2D_ACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActorClass))
#define SDX_SCENES_SCENE2D_IS_ACTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_ACTOR))
#define SDX_SCENES_SCENE2D_IS_ACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_SCENES_SCENE2D_TYPE_ACTOR))
#define SDX_SCENES_SCENE2D_ACTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActorClass))

typedef struct _sdxscenesscene2dActor sdxscenesscene2dActor;
typedef struct _sdxscenesscene2dActorClass sdxscenesscene2dActorClass;
typedef struct _sdxscenesscene2dActorPrivate sdxscenesscene2dActorPrivate;

#define SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER (sdx_scenes_scene2d_event_listener_get_type ())
#define SDX_SCENES_SCENE2D_EVENT_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER, sdxscenesscene2dEventListener))
#define SDX_SCENES_SCENE2D_IS_EVENT_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER))
#define SDX_SCENES_SCENE2D_EVENT_LISTENER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER, sdxscenesscene2dEventListenerIface))

typedef struct _sdxscenesscene2dEventListener sdxscenesscene2dEventListener;
typedef struct _sdxscenesscene2dEventListenerIface sdxscenesscene2dEventListenerIface;

#define SDX_SCENES_SCENE2D_TYPE_EVENT (sdx_scenes_scene2d_event_get_type ())
#define SDX_SCENES_SCENE2D_EVENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT, sdxscenesscene2dEvent))
#define SDX_SCENES_SCENE2D_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_SCENES_SCENE2D_TYPE_EVENT, sdxscenesscene2dEventClass))
#define SDX_SCENES_SCENE2D_IS_EVENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT))
#define SDX_SCENES_SCENE2D_IS_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_SCENES_SCENE2D_TYPE_EVENT))
#define SDX_SCENES_SCENE2D_EVENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT, sdxscenesscene2dEventClass))

typedef struct _sdxscenesscene2dEvent sdxscenesscene2dEvent;
typedef struct _sdxscenesscene2dEventClass sdxscenesscene2dEventClass;

#define SDX_SCENES_SCENE2D_TYPE_ACTION (sdx_scenes_scene2d_action_get_type ())
#define SDX_SCENES_SCENE2D_ACTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_ACTION, sdxscenesscene2dAction))
#define SDX_SCENES_SCENE2D_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_SCENES_SCENE2D_TYPE_ACTION, sdxscenesscene2dActionClass))
#define SDX_SCENES_SCENE2D_IS_ACTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_ACTION))
#define SDX_SCENES_SCENE2D_IS_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_SCENES_SCENE2D_TYPE_ACTION))
#define SDX_SCENES_SCENE2D_ACTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_SCENES_SCENE2D_TYPE_ACTION, sdxscenesscene2dActionClass))

typedef struct _sdxscenesscene2dAction sdxscenesscene2dAction;
typedef struct _sdxscenesscene2dActionClass sdxscenesscene2dActionClass;

#define SDX_SCENES_SCENE2D_TYPE_GROUP (sdx_scenes_scene2d_group_get_type ())
#define SDX_SCENES_SCENE2D_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_GROUP, sdxscenesscene2dGroup))
#define SDX_SCENES_SCENE2D_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_SCENES_SCENE2D_TYPE_GROUP, sdxscenesscene2dGroupClass))
#define SDX_SCENES_SCENE2D_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_GROUP))
#define SDX_SCENES_SCENE2D_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_SCENES_SCENE2D_TYPE_GROUP))
#define SDX_SCENES_SCENE2D_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_SCENES_SCENE2D_TYPE_GROUP, sdxscenesscene2dGroupClass))

typedef struct _sdxscenesscene2dGroup sdxscenesscene2dGroup;
typedef struct _sdxscenesscene2dGroupClass sdxscenesscene2dGroupClass;
typedef struct _sdxscenesscene2dGroupPrivate sdxscenesscene2dGroupPrivate;

#define SDX_TYPE_INPUT_ADAPTER (sdx_input_adapter_get_type ())
#define SDX_INPUT_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_INPUT_ADAPTER, sdxInputAdapter))
#define SDX_INPUT_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_TYPE_INPUT_ADAPTER, sdxInputAdapterClass))
#define SDX_IS_INPUT_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_INPUT_ADAPTER))
#define SDX_IS_INPUT_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_TYPE_INPUT_ADAPTER))
#define SDX_INPUT_ADAPTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_TYPE_INPUT_ADAPTER, sdxInputAdapterClass))

typedef struct _sdxInputAdapter sdxInputAdapter;
typedef struct _sdxInputAdapterClass sdxInputAdapterClass;

#define SDX_SCENES_SCENE2D_TYPE_STAGE (sdx_scenes_scene2d_stage_get_type ())
#define SDX_SCENES_SCENE2D_STAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_STAGE, sdxscenesscene2dStage))
#define SDX_SCENES_SCENE2D_STAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_SCENES_SCENE2D_TYPE_STAGE, sdxscenesscene2dStageClass))
#define SDX_SCENES_SCENE2D_IS_STAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_STAGE))
#define SDX_SCENES_SCENE2D_IS_STAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_SCENES_SCENE2D_TYPE_STAGE))
#define SDX_SCENES_SCENE2D_STAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_SCENES_SCENE2D_TYPE_STAGE, sdxscenesscene2dStageClass))

typedef struct _sdxscenesscene2dStage sdxscenesscene2dStage;
typedef struct _sdxscenesscene2dStageClass sdxscenesscene2dStageClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define SDX_GRAPHICS_S2D_TYPE_BATCH (sdx_graphics_s2d_batch_get_type ())
#define SDX_GRAPHICS_S2D_BATCH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_S2D_TYPE_BATCH, sdxgraphicss2dBatch))
#define SDX_GRAPHICS_S2D_BATCH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_S2D_TYPE_BATCH, sdxgraphicss2dBatchClass))
#define SDX_GRAPHICS_S2D_IS_BATCH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_S2D_TYPE_BATCH))
#define SDX_GRAPHICS_S2D_IS_BATCH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_S2D_TYPE_BATCH))
#define SDX_GRAPHICS_S2D_BATCH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_S2D_TYPE_BATCH, sdxgraphicss2dBatchClass))

typedef struct _sdxgraphicss2dBatch sdxgraphicss2dBatch;
typedef struct _sdxgraphicss2dBatchClass sdxgraphicss2dBatchClass;

#define SDX_SCENES_SCENE2D_TYPE_TOUCHABLE (sdx_scenes_scene2d_touchable_get_type ())

#define SDX_MATH_TYPE_VECTOR2 (sdx_math_vector2_get_type ())
#define SDX_MATH_VECTOR2(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_MATH_TYPE_VECTOR2, sdxmathVector2))
#define SDX_MATH_VECTOR2_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_MATH_TYPE_VECTOR2, sdxmathVector2Class))
#define SDX_MATH_IS_VECTOR2(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_MATH_TYPE_VECTOR2))
#define SDX_MATH_IS_VECTOR2_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_MATH_TYPE_VECTOR2))
#define SDX_MATH_VECTOR2_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_MATH_TYPE_VECTOR2, sdxmathVector2Class))

typedef struct _sdxmathVector2 sdxmathVector2;
typedef struct _sdxmathVector2Class sdxmathVector2Class;
typedef struct _sdxmathVector2Private sdxmathVector2Private;

struct _sdxscenesscene2dCullableIface {
	GTypeInterface parent_iface;
	void (*setCullingArea) (sdxscenesscene2dCullable* self, sdxmathRectangle* cullingArea);
};

struct _sdxscenesscene2dEventListenerIface {
	GTypeInterface parent_iface;
	gboolean (*handle) (sdxscenesscene2dEventListener* self, sdxscenesscene2dEvent* event);
};

struct _sdxscenesscene2dActor {
	GObject parent_instance;
	sdxscenesscene2dActorPrivate * priv;
	GeeArrayList* listeners;
	GeeArrayList* captureListeners;
	GeeArrayList* actions;
	gboolean visible;
	gdouble x;
	gdouble y;
	gdouble width;
	gdouble height;
	gdouble originX;
	gdouble originY;
	gdouble scaleX;
	gdouble scaleY;
	gdouble rotation;
};

struct _sdxscenesscene2dActorClass {
	GObjectClass parent_class;
};

struct _sdxscenesscene2dGroup {
	sdxscenesscene2dActor parent_instance;
	sdxscenesscene2dGroupPrivate * priv;
};

struct _sdxscenesscene2dGroupClass {
	sdxscenesscene2dActorClass parent_class;
};

struct _sdxscenesscene2dGroupPrivate {
	GeeArrayList* _children;
	sdxscenesscene2dStage* _stage;
	sdxmathRectangle* cullingArea;
	gboolean transform;
};

typedef enum  {
	SDX_SCENES_SCENE2D_TOUCHABLE_enabled,
	SDX_SCENES_SCENE2D_TOUCHABLE_disabled,
	SDX_SCENES_SCENE2D_TOUCHABLE_childrenOnly
} sdxscenesscene2dTouchable;

struct _sdxmathVector2 {
	GObject parent_instance;
	sdxmathVector2Private * priv;
	gdouble x;
	gdouble y;
};

struct _sdxmathVector2Class {
	GObjectClass parent_class;
};

typedef enum  {
	SDX_EXCEPTION_IllegalArgumentException,
	SDX_EXCEPTION_IllegalStateException,
	SDX_EXCEPTION_SdxRuntimeException,
	SDX_EXCEPTION_NullPointerException,
	SDX_EXCEPTION_NoSuchElementException,
	SDX_EXCEPTION_SDLException
} sdxException;
#define SDX_EXCEPTION sdx_exception_quark ()

static gpointer sdx_scenes_scene2d_group_parent_class = NULL;
static sdxscenesscene2dCullableIface* sdx_scenes_scene2d_group_sdx_scenes_scene2d_cullable_parent_iface = NULL;

GType sdx_math_rectangle_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_cullable_get_type (void) G_GNUC_CONST;
void sdx_scenes_scene2d_cullable_setCullingArea (sdxscenesscene2dCullable* self, sdxmathRectangle* cullingArea);
GType sdx_scenes_scene2d_actor_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_event_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_event_listener_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_action_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_group_get_type (void) G_GNUC_CONST;
GType sdx_input_adapter_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_stage_get_type (void) G_GNUC_CONST;
#define SDX_SCENES_SCENE2D_GROUP_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SDX_SCENES_SCENE2D_TYPE_GROUP, sdxscenesscene2dGroupPrivate))
enum  {
	SDX_SCENES_SCENE2D_GROUP_DUMMY_PROPERTY,
	SDX_SCENES_SCENE2D_GROUP_CHILDREN,
	SDX_SCENES_SCENE2D_GROUP_STAGE
};
void sdx_scenes_scene2d_group_act (sdxscenesscene2dGroup* self, gdouble delta);
void sdx_scenes_scene2d_actor_act (sdxscenesscene2dActor* self, gdouble delta);
GeeArrayList* sdx_scenes_scene2d_group_get_children (sdxscenesscene2dGroup* self);
gpointer sdx_graphics_s2d_batch_ref (gpointer instance);
void sdx_graphics_s2d_batch_unref (gpointer instance);
GParamSpec* sdx_graphics_s2d_param_spec_batch (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void sdx_graphics_s2d_value_set_batch (GValue* value, gpointer v_object);
void sdx_graphics_s2d_value_take_batch (GValue* value, gpointer v_object);
gpointer sdx_graphics_s2d_value_get_batch (const GValue* value);
GType sdx_graphics_s2d_batch_get_type (void) G_GNUC_CONST;
void sdx_scenes_scene2d_group_draw (sdxscenesscene2dGroup* self, sdxgraphicss2dBatch* batch, gdouble parentAlpha);
void sdx_scenes_scene2d_group_drawChildren (sdxscenesscene2dGroup* self, sdxgraphicss2dBatch* batch, gdouble parentAlpha);
gboolean sdx_scenes_scene2d_actor_isVisible (sdxscenesscene2dActor* self);
void sdx_scenes_scene2d_actor_draw (sdxscenesscene2dActor* self, sdxgraphicss2dBatch* batch, gdouble parentAlpha);
static void sdx_scenes_scene2d_group_real_setCullingArea (sdxscenesscene2dCullable* base, sdxmathRectangle* cullingArea);
sdxmathRectangle* sdx_scenes_scene2d_group_getCullingArea (sdxscenesscene2dGroup* self);
sdxscenesscene2dActor* sdx_scenes_scene2d_group_hit (sdxscenesscene2dGroup* self, gdouble x, gdouble y, gboolean touchable);
GType sdx_scenes_scene2d_touchable_get_type (void) G_GNUC_CONST;
sdxscenesscene2dTouchable sdx_scenes_scene2d_actor_get_touchable (sdxscenesscene2dActor* self);
GType sdx_math_vector2_get_type (void) G_GNUC_CONST;
sdxmathVector2* sdx_math_vector2_new (gdouble x, gdouble y);
sdxmathVector2* sdx_math_vector2_construct (GType object_type, gdouble x, gdouble y);
sdxmathVector2* sdx_scenes_scene2d_actor_parentToLocalCoordinates (sdxscenesscene2dActor* self, sdxmathVector2* parentCoords);
sdxscenesscene2dActor* sdx_scenes_scene2d_actor_hit (sdxscenesscene2dActor* self, gdouble x, gdouble y, gboolean touchable);
void sdx_scenes_scene2d_group_childrenChanged (sdxscenesscene2dGroup* self);
void sdx_scenes_scene2d_group_addActor (sdxscenesscene2dGroup* self, sdxscenesscene2dActor* actor);
sdxscenesscene2dGroup* sdx_scenes_scene2d_actor_get_parent (sdxscenesscene2dActor* self);
gboolean sdx_scenes_scene2d_group_removeActor (sdxscenesscene2dGroup* self, sdxscenesscene2dActor* actor, gboolean unfocus);
void sdx_scenes_scene2d_actor_set_parent (sdxscenesscene2dActor* self, sdxscenesscene2dGroup* value);
sdxscenesscene2dStage* sdx_scenes_scene2d_group_get_stage (sdxscenesscene2dGroup* self);
void sdx_scenes_scene2d_actor_set_stage (sdxscenesscene2dActor* self, sdxscenesscene2dStage* value);
void sdx_scenes_scene2d_group_addActorAt (sdxscenesscene2dGroup* self, gint index, sdxscenesscene2dActor* actor);
void sdx_scenes_scene2d_group_addActorBefore (sdxscenesscene2dGroup* self, sdxscenesscene2dActor* actorBefore, sdxscenesscene2dActor* actor);
void sdx_scenes_scene2d_group_addActorAfter (sdxscenesscene2dGroup* self, sdxscenesscene2dActor* actorAfter, sdxscenesscene2dActor* actor);
void sdx_scenes_scene2d_group_clearChildren (sdxscenesscene2dGroup* self);
void sdx_scenes_scene2d_group_clear (sdxscenesscene2dGroup* self);
void sdx_scenes_scene2d_actor_clear (sdxscenesscene2dActor* self);
sdxscenesscene2dActor* sdx_scenes_scene2d_group_findActor (sdxscenesscene2dGroup* self, const gchar* name);
const gchar* sdx_scenes_scene2d_actor_get_name (sdxscenesscene2dActor* self);
gboolean sdx_scenes_scene2d_group_hasChildren (sdxscenesscene2dGroup* self);
void sdx_scenes_scene2d_group_setTransform (sdxscenesscene2dGroup* self, gboolean transform);
gboolean sdx_scenes_scene2d_group_isTransform (sdxscenesscene2dGroup* self);
sdxmathVector2* sdx_scenes_scene2d_group_localToDescendantCoordinates (sdxscenesscene2dGroup* self, sdxscenesscene2dActor* descendant, sdxmathVector2* localCoords);
GQuark sdx_exception_quark (void);
sdxscenesscene2dGroup* sdx_scenes_scene2d_group_new (void);
sdxscenesscene2dGroup* sdx_scenes_scene2d_group_construct (GType object_type);
sdxscenesscene2dActor* sdx_scenes_scene2d_actor_new (void);
sdxscenesscene2dActor* sdx_scenes_scene2d_actor_construct (GType object_type);
void sdx_scenes_scene2d_group_set_children (sdxscenesscene2dGroup* self, GeeArrayList* value);
void sdx_scenes_scene2d_group_set_stage (sdxscenesscene2dGroup* self, sdxscenesscene2dStage* value);
static void sdx_scenes_scene2d_group_finalize (GObject* obj);
static void _vala_sdx_scenes_scene2d_group_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_sdx_scenes_scene2d_group_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


void sdx_scenes_scene2d_cullable_setCullingArea (sdxscenesscene2dCullable* self, sdxmathRectangle* cullingArea) {
	g_return_if_fail (self != NULL);
	SDX_SCENES_SCENE2D_CULLABLE_GET_INTERFACE (self)->setCullingArea (self, cullingArea);
}


static void sdx_scenes_scene2d_cullable_base_init (sdxscenesscene2dCullableIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType sdx_scenes_scene2d_cullable_get_type (void) {
	static volatile gsize sdx_scenes_scene2d_cullable_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_scenes_scene2d_cullable_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (sdxscenesscene2dCullableIface), (GBaseInitFunc) sdx_scenes_scene2d_cullable_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType sdx_scenes_scene2d_cullable_type_id;
		sdx_scenes_scene2d_cullable_type_id = g_type_register_static (G_TYPE_INTERFACE, "sdxscenesscene2dCullable", &g_define_type_info, 0);
		g_once_init_leave (&sdx_scenes_scene2d_cullable_type_id__volatile, sdx_scenes_scene2d_cullable_type_id);
	}
	return sdx_scenes_scene2d_cullable_type_id__volatile;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void sdx_scenes_scene2d_group_act (sdxscenesscene2dGroup* self, gdouble delta) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = delta;
	sdx_scenes_scene2d_actor_act (G_TYPE_CHECK_INSTANCE_CAST (self, SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActor), _tmp0_);
	{
		GeeArrayList* _child_list = NULL;
		GeeArrayList* _tmp1_ = NULL;
		GeeArrayList* _tmp2_ = NULL;
		gint _child_size = 0;
		GeeArrayList* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		gint _child_index = 0;
		_tmp1_ = self->priv->_children;
		_tmp2_ = _g_object_ref0 (_tmp1_);
		_child_list = _tmp2_;
		_tmp3_ = _child_list;
		_tmp4_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp3_);
		_tmp5_ = _tmp4_;
		_child_size = _tmp5_;
		_child_index = -1;
		while (TRUE) {
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			gint _tmp8_ = 0;
			sdxscenesscene2dActor* child = NULL;
			GeeArrayList* _tmp9_ = NULL;
			gint _tmp10_ = 0;
			gpointer _tmp11_ = NULL;
			sdxscenesscene2dActor* _tmp12_ = NULL;
			gdouble _tmp13_ = 0.0;
			_tmp6_ = _child_index;
			_child_index = _tmp6_ + 1;
			_tmp7_ = _child_index;
			_tmp8_ = _child_size;
			if (!(_tmp7_ < _tmp8_)) {
				break;
			}
			_tmp9_ = _child_list;
			_tmp10_ = _child_index;
			_tmp11_ = gee_abstract_list_get ((GeeAbstractList*) _tmp9_, _tmp10_);
			child = (sdxscenesscene2dActor*) _tmp11_;
			_tmp12_ = child;
			_tmp13_ = delta;
			sdx_scenes_scene2d_actor_act (_tmp12_, _tmp13_);
			_g_object_unref0 (child);
		}
		_g_object_unref0 (_child_list);
	}
}


void sdx_scenes_scene2d_group_draw (sdxscenesscene2dGroup* self, sdxgraphicss2dBatch* batch, gdouble parentAlpha) {
	sdxgraphicss2dBatch* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (batch != NULL);
	_tmp0_ = batch;
	_tmp1_ = parentAlpha;
	sdx_scenes_scene2d_group_drawChildren (self, _tmp0_, _tmp1_);
}


void sdx_scenes_scene2d_group_drawChildren (sdxscenesscene2dGroup* self, sdxgraphicss2dBatch* batch, gdouble parentAlpha) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (batch != NULL);
	_tmp0_ = self->priv->transform;
	if (_tmp0_) {
		{
			GeeArrayList* _child_list = NULL;
			GeeArrayList* _tmp1_ = NULL;
			GeeArrayList* _tmp2_ = NULL;
			gint _child_size = 0;
			GeeArrayList* _tmp3_ = NULL;
			gint _tmp4_ = 0;
			gint _tmp5_ = 0;
			gint _child_index = 0;
			_tmp1_ = self->priv->_children;
			_tmp2_ = _g_object_ref0 (_tmp1_);
			_child_list = _tmp2_;
			_tmp3_ = _child_list;
			_tmp4_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp3_);
			_tmp5_ = _tmp4_;
			_child_size = _tmp5_;
			_child_index = -1;
			while (TRUE) {
				gint _tmp6_ = 0;
				gint _tmp7_ = 0;
				gint _tmp8_ = 0;
				sdxscenesscene2dActor* child = NULL;
				GeeArrayList* _tmp9_ = NULL;
				gint _tmp10_ = 0;
				gpointer _tmp11_ = NULL;
				sdxscenesscene2dActor* _tmp12_ = NULL;
				gboolean _tmp13_ = FALSE;
				_tmp6_ = _child_index;
				_child_index = _tmp6_ + 1;
				_tmp7_ = _child_index;
				_tmp8_ = _child_size;
				if (!(_tmp7_ < _tmp8_)) {
					break;
				}
				_tmp9_ = _child_list;
				_tmp10_ = _child_index;
				_tmp11_ = gee_abstract_list_get ((GeeAbstractList*) _tmp9_, _tmp10_);
				child = (sdxscenesscene2dActor*) _tmp11_;
				_tmp12_ = child;
				_tmp13_ = sdx_scenes_scene2d_actor_isVisible (_tmp12_);
				if (_tmp13_) {
					sdxscenesscene2dActor* _tmp14_ = NULL;
					sdxgraphicss2dBatch* _tmp15_ = NULL;
					gdouble _tmp16_ = 0.0;
					_tmp14_ = child;
					_tmp15_ = batch;
					_tmp16_ = parentAlpha;
					sdx_scenes_scene2d_actor_draw (_tmp14_, _tmp15_, _tmp16_);
				}
				_g_object_unref0 (child);
			}
			_g_object_unref0 (_child_list);
		}
	} else {
		gdouble offsetX = 0.0;
		gdouble _tmp17_ = 0.0;
		gdouble offsetY = 0.0;
		gdouble _tmp18_ = 0.0;
		gdouble _tmp49_ = 0.0;
		gdouble _tmp50_ = 0.0;
		_tmp17_ = ((sdxscenesscene2dActor*) self)->x;
		offsetX = _tmp17_;
		_tmp18_ = ((sdxscenesscene2dActor*) self)->y;
		offsetY = _tmp18_;
		((sdxscenesscene2dActor*) self)->x = (gdouble) 0;
		((sdxscenesscene2dActor*) self)->y = (gdouble) 0;
		{
			GeeArrayList* _child_list = NULL;
			GeeArrayList* _tmp19_ = NULL;
			GeeArrayList* _tmp20_ = NULL;
			gint _child_size = 0;
			GeeArrayList* _tmp21_ = NULL;
			gint _tmp22_ = 0;
			gint _tmp23_ = 0;
			gint _child_index = 0;
			_tmp19_ = self->priv->_children;
			_tmp20_ = _g_object_ref0 (_tmp19_);
			_child_list = _tmp20_;
			_tmp21_ = _child_list;
			_tmp22_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp21_);
			_tmp23_ = _tmp22_;
			_child_size = _tmp23_;
			_child_index = -1;
			while (TRUE) {
				gint _tmp24_ = 0;
				gint _tmp25_ = 0;
				gint _tmp26_ = 0;
				sdxscenesscene2dActor* child = NULL;
				GeeArrayList* _tmp27_ = NULL;
				gint _tmp28_ = 0;
				gpointer _tmp29_ = NULL;
				sdxscenesscene2dActor* _tmp30_ = NULL;
				gboolean _tmp31_ = FALSE;
				gdouble cx = 0.0;
				sdxscenesscene2dActor* _tmp32_ = NULL;
				gdouble _tmp33_ = 0.0;
				gdouble cy = 0.0;
				sdxscenesscene2dActor* _tmp34_ = NULL;
				gdouble _tmp35_ = 0.0;
				sdxscenesscene2dActor* _tmp36_ = NULL;
				gdouble _tmp37_ = 0.0;
				gdouble _tmp38_ = 0.0;
				sdxscenesscene2dActor* _tmp39_ = NULL;
				gdouble _tmp40_ = 0.0;
				gdouble _tmp41_ = 0.0;
				sdxscenesscene2dActor* _tmp42_ = NULL;
				sdxgraphicss2dBatch* _tmp43_ = NULL;
				gdouble _tmp44_ = 0.0;
				sdxscenesscene2dActor* _tmp45_ = NULL;
				gdouble _tmp46_ = 0.0;
				sdxscenesscene2dActor* _tmp47_ = NULL;
				gdouble _tmp48_ = 0.0;
				_tmp24_ = _child_index;
				_child_index = _tmp24_ + 1;
				_tmp25_ = _child_index;
				_tmp26_ = _child_size;
				if (!(_tmp25_ < _tmp26_)) {
					break;
				}
				_tmp27_ = _child_list;
				_tmp28_ = _child_index;
				_tmp29_ = gee_abstract_list_get ((GeeAbstractList*) _tmp27_, _tmp28_);
				child = (sdxscenesscene2dActor*) _tmp29_;
				_tmp30_ = child;
				_tmp31_ = sdx_scenes_scene2d_actor_isVisible (_tmp30_);
				if (!(!_tmp31_)) {
					_g_object_unref0 (child);
					continue;
				}
				_tmp32_ = child;
				_tmp33_ = _tmp32_->x;
				cx = _tmp33_;
				_tmp34_ = child;
				_tmp35_ = _tmp34_->y;
				cy = _tmp35_;
				_tmp36_ = child;
				_tmp37_ = cx;
				_tmp38_ = offsetX;
				_tmp36_->x = _tmp37_ + _tmp38_;
				_tmp39_ = child;
				_tmp40_ = cy;
				_tmp41_ = offsetY;
				_tmp39_->y = _tmp40_ + _tmp41_;
				_tmp42_ = child;
				_tmp43_ = batch;
				_tmp44_ = parentAlpha;
				sdx_scenes_scene2d_actor_draw (_tmp42_, _tmp43_, _tmp44_);
				_tmp45_ = child;
				_tmp46_ = cx;
				_tmp45_->x = _tmp46_;
				_tmp47_ = child;
				_tmp48_ = cy;
				_tmp47_->y = _tmp48_;
				_g_object_unref0 (child);
			}
			_g_object_unref0 (_child_list);
		}
		_tmp49_ = offsetX;
		((sdxscenesscene2dActor*) self)->x = _tmp49_;
		_tmp50_ = offsetY;
		((sdxscenesscene2dActor*) self)->y = _tmp50_;
	}
}


static void sdx_scenes_scene2d_group_real_setCullingArea (sdxscenesscene2dCullable* base, sdxmathRectangle* cullingArea) {
	sdxscenesscene2dGroup * self;
	self = (sdxscenesscene2dGroup*) base;
	g_return_if_fail (cullingArea != NULL);
}


sdxmathRectangle* sdx_scenes_scene2d_group_getCullingArea (sdxscenesscene2dGroup* self) {
	sdxmathRectangle* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = NULL;
	return result;
}


sdxscenesscene2dActor* sdx_scenes_scene2d_group_hit (sdxscenesscene2dGroup* self, gdouble x, gdouble y, gboolean touchable) {
	sdxscenesscene2dActor* result = NULL;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	sdxmathVector2* v = NULL;
	gdouble _tmp4_ = 0.0;
	gdouble _tmp5_ = 0.0;
	sdxmathVector2* _tmp6_ = NULL;
	gdouble _tmp32_ = 0.0;
	gdouble _tmp33_ = 0.0;
	gboolean _tmp34_ = FALSE;
	sdxscenesscene2dActor* _tmp35_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = touchable;
	if (_tmp1_) {
		sdxscenesscene2dTouchable _tmp2_ = 0;
		sdxscenesscene2dTouchable _tmp3_ = 0;
		_tmp2_ = sdx_scenes_scene2d_actor_get_touchable ((sdxscenesscene2dActor*) self);
		_tmp3_ = _tmp2_;
		_tmp0_ = _tmp3_ == SDX_SCENES_SCENE2D_TOUCHABLE_disabled;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		result = NULL;
		return result;
	}
	_tmp4_ = x;
	_tmp5_ = y;
	_tmp6_ = sdx_math_vector2_new (_tmp4_, _tmp5_);
	v = _tmp6_;
	{
		GeeArrayList* _child_list = NULL;
		GeeArrayList* _tmp7_ = NULL;
		GeeArrayList* _tmp8_ = NULL;
		gint _child_size = 0;
		GeeArrayList* _tmp9_ = NULL;
		gint _tmp10_ = 0;
		gint _tmp11_ = 0;
		gint _child_index = 0;
		_tmp7_ = self->priv->_children;
		_tmp8_ = _g_object_ref0 (_tmp7_);
		_child_list = _tmp8_;
		_tmp9_ = _child_list;
		_tmp10_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp9_);
		_tmp11_ = _tmp10_;
		_child_size = _tmp11_;
		_child_index = -1;
		while (TRUE) {
			gint _tmp12_ = 0;
			gint _tmp13_ = 0;
			gint _tmp14_ = 0;
			sdxscenesscene2dActor* child = NULL;
			GeeArrayList* _tmp15_ = NULL;
			gint _tmp16_ = 0;
			gpointer _tmp17_ = NULL;
			sdxscenesscene2dActor* _tmp18_ = NULL;
			gboolean _tmp19_ = FALSE;
			sdxscenesscene2dActor* _tmp20_ = NULL;
			sdxmathVector2* _tmp21_ = NULL;
			sdxmathVector2* _tmp22_ = NULL;
			sdxmathVector2* _tmp23_ = NULL;
			sdxscenesscene2dActor* ahit = NULL;
			sdxscenesscene2dActor* _tmp24_ = NULL;
			sdxmathVector2* _tmp25_ = NULL;
			gdouble _tmp26_ = 0.0;
			sdxmathVector2* _tmp27_ = NULL;
			gdouble _tmp28_ = 0.0;
			gboolean _tmp29_ = FALSE;
			sdxscenesscene2dActor* _tmp30_ = NULL;
			sdxscenesscene2dActor* _tmp31_ = NULL;
			_tmp12_ = _child_index;
			_child_index = _tmp12_ + 1;
			_tmp13_ = _child_index;
			_tmp14_ = _child_size;
			if (!(_tmp13_ < _tmp14_)) {
				break;
			}
			_tmp15_ = _child_list;
			_tmp16_ = _child_index;
			_tmp17_ = gee_abstract_list_get ((GeeAbstractList*) _tmp15_, _tmp16_);
			child = (sdxscenesscene2dActor*) _tmp17_;
			_tmp18_ = child;
			_tmp19_ = sdx_scenes_scene2d_actor_isVisible (_tmp18_);
			if (!_tmp19_) {
				_g_object_unref0 (child);
				continue;
			}
			_tmp20_ = child;
			_tmp21_ = v;
			_tmp22_ = sdx_scenes_scene2d_actor_parentToLocalCoordinates (_tmp20_, _tmp21_);
			_tmp23_ = _tmp22_;
			_g_object_unref0 (_tmp23_);
			_tmp24_ = child;
			_tmp25_ = v;
			_tmp26_ = _tmp25_->x;
			_tmp27_ = v;
			_tmp28_ = _tmp27_->y;
			_tmp29_ = touchable;
			_tmp30_ = sdx_scenes_scene2d_actor_hit (_tmp24_, _tmp26_, _tmp28_, _tmp29_);
			ahit = _tmp30_;
			_tmp31_ = ahit;
			if (_tmp31_ != NULL) {
				result = ahit;
				_g_object_unref0 (child);
				_g_object_unref0 (_child_list);
				_g_object_unref0 (v);
				return result;
			}
			_g_object_unref0 (ahit);
			_g_object_unref0 (child);
		}
		_g_object_unref0 (_child_list);
	}
	_tmp32_ = x;
	_tmp33_ = y;
	_tmp34_ = touchable;
	_tmp35_ = sdx_scenes_scene2d_actor_hit (G_TYPE_CHECK_INSTANCE_CAST (self, SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActor), _tmp32_, _tmp33_, _tmp34_);
	result = _tmp35_;
	_g_object_unref0 (v);
	return result;
}


void sdx_scenes_scene2d_group_childrenChanged (sdxscenesscene2dGroup* self) {
	g_return_if_fail (self != NULL);
}


void sdx_scenes_scene2d_group_addActor (sdxscenesscene2dGroup* self, sdxscenesscene2dActor* actor) {
	sdxscenesscene2dActor* _tmp0_ = NULL;
	sdxscenesscene2dGroup* _tmp1_ = NULL;
	sdxscenesscene2dGroup* _tmp2_ = NULL;
	GeeArrayList* _tmp10_ = NULL;
	sdxscenesscene2dActor* _tmp11_ = NULL;
	sdxscenesscene2dActor* _tmp12_ = NULL;
	sdxscenesscene2dActor* _tmp13_ = NULL;
	sdxscenesscene2dStage* _tmp14_ = NULL;
	sdxscenesscene2dStage* _tmp15_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (actor != NULL);
	_tmp0_ = actor;
	_tmp1_ = sdx_scenes_scene2d_actor_get_parent (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ != NULL) {
		sdxscenesscene2dActor* _tmp3_ = NULL;
		sdxscenesscene2dGroup* _tmp4_ = NULL;
		sdxscenesscene2dGroup* _tmp5_ = NULL;
		sdxscenesscene2dActor* _tmp6_ = NULL;
		sdxscenesscene2dGroup* _tmp7_ = NULL;
		sdxscenesscene2dGroup* _tmp8_ = NULL;
		sdxscenesscene2dActor* _tmp9_ = NULL;
		_tmp3_ = actor;
		_tmp4_ = sdx_scenes_scene2d_actor_get_parent (_tmp3_);
		_tmp5_ = _tmp4_;
		if (_tmp5_ == self) {
			return;
		}
		_tmp6_ = actor;
		_tmp7_ = sdx_scenes_scene2d_actor_get_parent (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = actor;
		sdx_scenes_scene2d_group_removeActor (_tmp8_, _tmp9_, FALSE);
	}
	_tmp10_ = self->priv->_children;
	_tmp11_ = actor;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp10_, _tmp11_);
	_tmp12_ = actor;
	sdx_scenes_scene2d_actor_set_parent (_tmp12_, self);
	_tmp13_ = actor;
	_tmp14_ = sdx_scenes_scene2d_group_get_stage (self);
	_tmp15_ = _tmp14_;
	sdx_scenes_scene2d_actor_set_stage (_tmp13_, _tmp15_);
	sdx_scenes_scene2d_group_childrenChanged (self);
}


void sdx_scenes_scene2d_group_addActorAt (sdxscenesscene2dGroup* self, gint index, sdxscenesscene2dActor* actor) {
	sdxscenesscene2dActor* _tmp0_ = NULL;
	sdxscenesscene2dGroup* _tmp1_ = NULL;
	sdxscenesscene2dGroup* _tmp2_ = NULL;
	gint _tmp10_ = 0;
	GeeArrayList* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	gint _tmp13_ = 0;
	sdxscenesscene2dActor* _tmp19_ = NULL;
	sdxscenesscene2dActor* _tmp20_ = NULL;
	sdxscenesscene2dStage* _tmp21_ = NULL;
	sdxscenesscene2dStage* _tmp22_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (actor != NULL);
	_tmp0_ = actor;
	_tmp1_ = sdx_scenes_scene2d_actor_get_parent (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ != NULL) {
		sdxscenesscene2dActor* _tmp3_ = NULL;
		sdxscenesscene2dGroup* _tmp4_ = NULL;
		sdxscenesscene2dGroup* _tmp5_ = NULL;
		sdxscenesscene2dActor* _tmp6_ = NULL;
		sdxscenesscene2dGroup* _tmp7_ = NULL;
		sdxscenesscene2dGroup* _tmp8_ = NULL;
		sdxscenesscene2dActor* _tmp9_ = NULL;
		_tmp3_ = actor;
		_tmp4_ = sdx_scenes_scene2d_actor_get_parent (_tmp3_);
		_tmp5_ = _tmp4_;
		if (_tmp5_ == self) {
			return;
		}
		_tmp6_ = actor;
		_tmp7_ = sdx_scenes_scene2d_actor_get_parent (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = actor;
		sdx_scenes_scene2d_group_removeActor (_tmp8_, _tmp9_, FALSE);
	}
	_tmp10_ = index;
	_tmp11_ = self->priv->_children;
	_tmp12_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp11_);
	_tmp13_ = _tmp12_;
	if (_tmp10_ >= _tmp13_) {
		GeeArrayList* _tmp14_ = NULL;
		sdxscenesscene2dActor* _tmp15_ = NULL;
		_tmp14_ = self->priv->_children;
		_tmp15_ = actor;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp14_, _tmp15_);
	} else {
		GeeArrayList* _tmp16_ = NULL;
		gint _tmp17_ = 0;
		sdxscenesscene2dActor* _tmp18_ = NULL;
		_tmp16_ = self->priv->_children;
		_tmp17_ = index;
		_tmp18_ = actor;
		gee_abstract_list_insert ((GeeAbstractList*) _tmp16_, _tmp17_, _tmp18_);
	}
	_tmp19_ = actor;
	sdx_scenes_scene2d_actor_set_parent (_tmp19_, self);
	_tmp20_ = actor;
	_tmp21_ = sdx_scenes_scene2d_group_get_stage (self);
	_tmp22_ = _tmp21_;
	sdx_scenes_scene2d_actor_set_stage (_tmp20_, _tmp22_);
	sdx_scenes_scene2d_group_childrenChanged (self);
}


void sdx_scenes_scene2d_group_addActorBefore (sdxscenesscene2dGroup* self, sdxscenesscene2dActor* actorBefore, sdxscenesscene2dActor* actor) {
	sdxscenesscene2dActor* _tmp0_ = NULL;
	sdxscenesscene2dGroup* _tmp1_ = NULL;
	sdxscenesscene2dGroup* _tmp2_ = NULL;
	gint index = 0;
	GeeArrayList* _tmp10_ = NULL;
	sdxscenesscene2dActor* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	GeeArrayList* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	sdxscenesscene2dActor* _tmp15_ = NULL;
	sdxscenesscene2dActor* _tmp16_ = NULL;
	sdxscenesscene2dActor* _tmp17_ = NULL;
	sdxscenesscene2dStage* _tmp18_ = NULL;
	sdxscenesscene2dStage* _tmp19_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (actorBefore != NULL);
	g_return_if_fail (actor != NULL);
	_tmp0_ = actor;
	_tmp1_ = sdx_scenes_scene2d_actor_get_parent (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ != NULL) {
		sdxscenesscene2dActor* _tmp3_ = NULL;
		sdxscenesscene2dGroup* _tmp4_ = NULL;
		sdxscenesscene2dGroup* _tmp5_ = NULL;
		sdxscenesscene2dActor* _tmp6_ = NULL;
		sdxscenesscene2dGroup* _tmp7_ = NULL;
		sdxscenesscene2dGroup* _tmp8_ = NULL;
		sdxscenesscene2dActor* _tmp9_ = NULL;
		_tmp3_ = actor;
		_tmp4_ = sdx_scenes_scene2d_actor_get_parent (_tmp3_);
		_tmp5_ = _tmp4_;
		if (_tmp5_ == self) {
			return;
		}
		_tmp6_ = actor;
		_tmp7_ = sdx_scenes_scene2d_actor_get_parent (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = actor;
		sdx_scenes_scene2d_group_removeActor (_tmp8_, _tmp9_, FALSE);
	}
	_tmp10_ = self->priv->_children;
	_tmp11_ = actorBefore;
	_tmp12_ = gee_abstract_list_index_of ((GeeAbstractList*) _tmp10_, _tmp11_);
	index = _tmp12_;
	_tmp13_ = self->priv->_children;
	_tmp14_ = index;
	_tmp15_ = actor;
	gee_abstract_list_insert ((GeeAbstractList*) _tmp13_, _tmp14_, _tmp15_);
	_tmp16_ = actor;
	sdx_scenes_scene2d_actor_set_parent (_tmp16_, self);
	_tmp17_ = actor;
	_tmp18_ = sdx_scenes_scene2d_group_get_stage (self);
	_tmp19_ = _tmp18_;
	sdx_scenes_scene2d_actor_set_stage (_tmp17_, _tmp19_);
	sdx_scenes_scene2d_group_childrenChanged (self);
}


void sdx_scenes_scene2d_group_addActorAfter (sdxscenesscene2dGroup* self, sdxscenesscene2dActor* actorAfter, sdxscenesscene2dActor* actor) {
	sdxscenesscene2dActor* _tmp0_ = NULL;
	sdxscenesscene2dGroup* _tmp1_ = NULL;
	sdxscenesscene2dGroup* _tmp2_ = NULL;
	gint index = 0;
	GeeArrayList* _tmp10_ = NULL;
	sdxscenesscene2dActor* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	gint _tmp13_ = 0;
	GeeArrayList* _tmp14_ = NULL;
	gint _tmp15_ = 0;
	gint _tmp16_ = 0;
	sdxscenesscene2dActor* _tmp22_ = NULL;
	sdxscenesscene2dActor* _tmp23_ = NULL;
	sdxscenesscene2dStage* _tmp24_ = NULL;
	sdxscenesscene2dStage* _tmp25_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (actorAfter != NULL);
	g_return_if_fail (actor != NULL);
	_tmp0_ = actor;
	_tmp1_ = sdx_scenes_scene2d_actor_get_parent (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ != NULL) {
		sdxscenesscene2dActor* _tmp3_ = NULL;
		sdxscenesscene2dGroup* _tmp4_ = NULL;
		sdxscenesscene2dGroup* _tmp5_ = NULL;
		sdxscenesscene2dActor* _tmp6_ = NULL;
		sdxscenesscene2dGroup* _tmp7_ = NULL;
		sdxscenesscene2dGroup* _tmp8_ = NULL;
		sdxscenesscene2dActor* _tmp9_ = NULL;
		_tmp3_ = actor;
		_tmp4_ = sdx_scenes_scene2d_actor_get_parent (_tmp3_);
		_tmp5_ = _tmp4_;
		if (_tmp5_ == self) {
			return;
		}
		_tmp6_ = actor;
		_tmp7_ = sdx_scenes_scene2d_actor_get_parent (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = actor;
		sdx_scenes_scene2d_group_removeActor (_tmp8_, _tmp9_, FALSE);
	}
	_tmp10_ = self->priv->_children;
	_tmp11_ = actorAfter;
	_tmp12_ = gee_abstract_list_index_of ((GeeAbstractList*) _tmp10_, _tmp11_);
	index = _tmp12_;
	_tmp13_ = index;
	_tmp14_ = self->priv->_children;
	_tmp15_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp14_);
	_tmp16_ = _tmp15_;
	if (_tmp13_ == _tmp16_) {
		GeeArrayList* _tmp17_ = NULL;
		sdxscenesscene2dActor* _tmp18_ = NULL;
		_tmp17_ = self->priv->_children;
		_tmp18_ = actor;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp17_, _tmp18_);
	} else {
		GeeArrayList* _tmp19_ = NULL;
		gint _tmp20_ = 0;
		sdxscenesscene2dActor* _tmp21_ = NULL;
		_tmp19_ = self->priv->_children;
		_tmp20_ = index;
		_tmp21_ = actor;
		gee_abstract_list_insert ((GeeAbstractList*) _tmp19_, _tmp20_ + 1, _tmp21_);
	}
	_tmp22_ = actor;
	sdx_scenes_scene2d_actor_set_parent (_tmp22_, self);
	_tmp23_ = actor;
	_tmp24_ = sdx_scenes_scene2d_group_get_stage (self);
	_tmp25_ = _tmp24_;
	sdx_scenes_scene2d_actor_set_stage (_tmp23_, _tmp25_);
	sdx_scenes_scene2d_group_childrenChanged (self);
}


gboolean sdx_scenes_scene2d_group_removeActor (sdxscenesscene2dGroup* self, sdxscenesscene2dActor* actor, gboolean unfocus) {
	gboolean result = FALSE;
	GeeArrayList* _tmp0_ = NULL;
	sdxscenesscene2dActor* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	sdxscenesscene2dActor* _tmp3_ = NULL;
	sdxscenesscene2dActor* _tmp4_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (actor != NULL, FALSE);
	_tmp0_ = self->priv->_children;
	_tmp1_ = actor;
	_tmp2_ = gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp0_, _tmp1_);
	if (!_tmp2_) {
		result = FALSE;
		return result;
	}
	_tmp3_ = actor;
	sdx_scenes_scene2d_actor_set_parent (_tmp3_, NULL);
	_tmp4_ = actor;
	sdx_scenes_scene2d_actor_set_stage (_tmp4_, NULL);
	sdx_scenes_scene2d_group_childrenChanged (self);
	result = TRUE;
	return result;
}


void sdx_scenes_scene2d_group_clearChildren (sdxscenesscene2dGroup* self) {
	GeeArrayList* _tmp13_ = NULL;
	g_return_if_fail (self != NULL);
	{
		GeeArrayList* _child_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _child_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _child_index = 0;
		_tmp0_ = self->priv->_children;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_child_list = _tmp1_;
		_tmp2_ = _child_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_child_size = _tmp4_;
		_child_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			sdxscenesscene2dActor* child = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			sdxscenesscene2dActor* _tmp11_ = NULL;
			sdxscenesscene2dActor* _tmp12_ = NULL;
			_tmp5_ = _child_index;
			_child_index = _tmp5_ + 1;
			_tmp6_ = _child_index;
			_tmp7_ = _child_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _child_list;
			_tmp9_ = _child_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			child = (sdxscenesscene2dActor*) _tmp10_;
			_tmp11_ = child;
			sdx_scenes_scene2d_actor_set_parent (_tmp11_, NULL);
			_tmp12_ = child;
			sdx_scenes_scene2d_actor_set_stage (_tmp12_, NULL);
			_g_object_unref0 (child);
		}
		_g_object_unref0 (_child_list);
	}
	_tmp13_ = self->priv->_children;
	gee_abstract_collection_clear ((GeeAbstractCollection*) _tmp13_);
	sdx_scenes_scene2d_group_childrenChanged (self);
}


void sdx_scenes_scene2d_group_clear (sdxscenesscene2dGroup* self) {
	g_return_if_fail (self != NULL);
	sdx_scenes_scene2d_actor_clear (G_TYPE_CHECK_INSTANCE_CAST (self, SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActor));
	sdx_scenes_scene2d_group_clearChildren (self);
}


sdxscenesscene2dActor* sdx_scenes_scene2d_group_findActor (sdxscenesscene2dGroup* self, const gchar* name) {
	sdxscenesscene2dActor* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	{
		GeeArrayList* _child_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _child_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _child_index = 0;
		_tmp0_ = self->priv->_children;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_child_list = _tmp1_;
		_tmp2_ = _child_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_child_size = _tmp4_;
		_child_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			sdxscenesscene2dActor* child = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			const gchar* _tmp11_ = NULL;
			sdxscenesscene2dActor* _tmp12_ = NULL;
			const gchar* _tmp13_ = NULL;
			const gchar* _tmp14_ = NULL;
			_tmp5_ = _child_index;
			_child_index = _tmp5_ + 1;
			_tmp6_ = _child_index;
			_tmp7_ = _child_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _child_list;
			_tmp9_ = _child_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			child = (sdxscenesscene2dActor*) _tmp10_;
			_tmp11_ = name;
			_tmp12_ = child;
			_tmp13_ = sdx_scenes_scene2d_actor_get_name (_tmp12_);
			_tmp14_ = _tmp13_;
			if (g_strcmp0 (_tmp11_, _tmp14_) == 0) {
				result = child;
				_g_object_unref0 (_child_list);
				return result;
			}
			_g_object_unref0 (child);
		}
		_g_object_unref0 (_child_list);
	}
	{
		GeeArrayList* _child_list = NULL;
		GeeArrayList* _tmp15_ = NULL;
		GeeArrayList* _tmp16_ = NULL;
		gint _child_size = 0;
		GeeArrayList* _tmp17_ = NULL;
		gint _tmp18_ = 0;
		gint _tmp19_ = 0;
		gint _child_index = 0;
		_tmp15_ = self->priv->_children;
		_tmp16_ = _g_object_ref0 (_tmp15_);
		_child_list = _tmp16_;
		_tmp17_ = _child_list;
		_tmp18_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp17_);
		_tmp19_ = _tmp18_;
		_child_size = _tmp19_;
		_child_index = -1;
		while (TRUE) {
			gint _tmp20_ = 0;
			gint _tmp21_ = 0;
			gint _tmp22_ = 0;
			sdxscenesscene2dActor* child = NULL;
			GeeArrayList* _tmp23_ = NULL;
			gint _tmp24_ = 0;
			gpointer _tmp25_ = NULL;
			sdxscenesscene2dActor* _tmp26_ = NULL;
			_tmp20_ = _child_index;
			_child_index = _tmp20_ + 1;
			_tmp21_ = _child_index;
			_tmp22_ = _child_size;
			if (!(_tmp21_ < _tmp22_)) {
				break;
			}
			_tmp23_ = _child_list;
			_tmp24_ = _child_index;
			_tmp25_ = gee_abstract_list_get ((GeeAbstractList*) _tmp23_, _tmp24_);
			child = (sdxscenesscene2dActor*) _tmp25_;
			_tmp26_ = child;
			if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp26_, SDX_SCENES_SCENE2D_TYPE_GROUP)) {
				sdxscenesscene2dGroup* group = NULL;
				sdxscenesscene2dActor* _tmp27_ = NULL;
				sdxscenesscene2dGroup* _tmp28_ = NULL;
				sdxscenesscene2dActor* actor = NULL;
				sdxscenesscene2dGroup* _tmp29_ = NULL;
				const gchar* _tmp30_ = NULL;
				sdxscenesscene2dActor* _tmp31_ = NULL;
				sdxscenesscene2dActor* _tmp32_ = NULL;
				_tmp27_ = child;
				_tmp28_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp27_, SDX_SCENES_SCENE2D_TYPE_GROUP, sdxscenesscene2dGroup));
				group = _tmp28_;
				_tmp29_ = group;
				_tmp30_ = name;
				_tmp31_ = sdx_scenes_scene2d_group_findActor (_tmp29_, _tmp30_);
				actor = _tmp31_;
				_tmp32_ = actor;
				if (_tmp32_ != NULL) {
					result = actor;
					_g_object_unref0 (group);
					_g_object_unref0 (child);
					_g_object_unref0 (_child_list);
					return result;
				}
				_g_object_unref0 (actor);
				_g_object_unref0 (group);
			}
			_g_object_unref0 (child);
		}
		_g_object_unref0 (_child_list);
	}
	result = NULL;
	return result;
}


gboolean sdx_scenes_scene2d_group_hasChildren (sdxscenesscene2dGroup* self) {
	gboolean result = FALSE;
	GeeArrayList* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_children;
	_tmp1_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_ > 0;
	return result;
}


void sdx_scenes_scene2d_group_setTransform (sdxscenesscene2dGroup* self, gboolean transform) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = transform;
	self->priv->transform = _tmp0_;
}


gboolean sdx_scenes_scene2d_group_isTransform (sdxscenesscene2dGroup* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->transform;
	result = _tmp0_;
	return result;
}


sdxmathVector2* sdx_scenes_scene2d_group_localToDescendantCoordinates (sdxscenesscene2dGroup* self, sdxscenesscene2dActor* descendant, sdxmathVector2* localCoords) {
	sdxmathVector2* result = NULL;
	sdxscenesscene2dActor* _tmp0_ = NULL;
	sdxscenesscene2dGroup* _tmp1_ = NULL;
	sdxscenesscene2dGroup* _tmp2_ = NULL;
	sdxscenesscene2dActor* _tmp7_ = NULL;
	sdxscenesscene2dGroup* _tmp8_ = NULL;
	sdxscenesscene2dGroup* _tmp9_ = NULL;
	sdxscenesscene2dActor* _tmp16_ = NULL;
	sdxmathVector2* _tmp17_ = NULL;
	sdxmathVector2* _tmp18_ = NULL;
	sdxmathVector2* _tmp19_ = NULL;
	sdxmathVector2* _tmp20_ = NULL;
	sdxmathVector2* _tmp21_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (descendant != NULL, NULL);
	g_return_val_if_fail (localCoords != NULL, NULL);
	_tmp0_ = descendant;
	_tmp1_ = sdx_scenes_scene2d_actor_get_parent (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ == NULL) {
		sdxscenesscene2dActor* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
		GError* _tmp6_ = NULL;
		_tmp3_ = descendant;
		_tmp4_ = sdx_scenes_scene2d_actor_get_name (_tmp3_);
		_tmp5_ = _tmp4_;
		_tmp6_ = g_error_new (SDX_EXCEPTION, SDX_EXCEPTION_IllegalArgumentException, "Child is not a descendant %s", _tmp5_);
		_inner_error_ = _tmp6_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp7_ = descendant;
	_tmp8_ = sdx_scenes_scene2d_actor_get_parent (_tmp7_);
	_tmp9_ = _tmp8_;
	if (_tmp9_ != self) {
		sdxscenesscene2dActor* _tmp10_ = NULL;
		sdxscenesscene2dGroup* _tmp11_ = NULL;
		sdxscenesscene2dGroup* _tmp12_ = NULL;
		sdxmathVector2* _tmp13_ = NULL;
		sdxmathVector2* _tmp14_ = NULL;
		sdxmathVector2* _tmp15_ = NULL;
		_tmp10_ = descendant;
		_tmp11_ = sdx_scenes_scene2d_actor_get_parent (_tmp10_);
		_tmp12_ = _tmp11_;
		_tmp13_ = localCoords;
		_tmp14_ = sdx_scenes_scene2d_group_localToDescendantCoordinates (self, (sdxscenesscene2dActor*) _tmp12_, _tmp13_);
		_tmp15_ = _tmp14_;
		_g_object_unref0 (_tmp15_);
	}
	_tmp16_ = descendant;
	_tmp17_ = localCoords;
	_tmp18_ = sdx_scenes_scene2d_actor_parentToLocalCoordinates (_tmp16_, _tmp17_);
	_tmp19_ = _tmp18_;
	_g_object_unref0 (_tmp19_);
	_tmp20_ = localCoords;
	_tmp21_ = _g_object_ref0 (_tmp20_);
	result = _tmp21_;
	return result;
}


sdxscenesscene2dGroup* sdx_scenes_scene2d_group_construct (GType object_type) {
	sdxscenesscene2dGroup * self = NULL;
	self = (sdxscenesscene2dGroup*) sdx_scenes_scene2d_actor_construct (object_type);
	return self;
}


sdxscenesscene2dGroup* sdx_scenes_scene2d_group_new (void) {
	return sdx_scenes_scene2d_group_construct (SDX_SCENES_SCENE2D_TYPE_GROUP);
}


GeeArrayList* sdx_scenes_scene2d_group_get_children (sdxscenesscene2dGroup* self) {
	GeeArrayList* result;
	GeeArrayList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_children;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_group_set_children (sdxscenesscene2dGroup* self, GeeArrayList* value) {
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_children);
	self->priv->_children = _tmp1_;
	g_object_notify ((GObject *) self, "children");
}


sdxscenesscene2dStage* sdx_scenes_scene2d_group_get_stage (sdxscenesscene2dGroup* self) {
	sdxscenesscene2dStage* result;
	sdxscenesscene2dStage* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_stage;
	result = _tmp0_;
	return result;
}


void sdx_scenes_scene2d_group_set_stage (sdxscenesscene2dGroup* self, sdxscenesscene2dStage* value) {
	sdxscenesscene2dStage* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	{
		GeeArrayList* _child_list = NULL;
		GeeArrayList* _tmp1_ = NULL;
		GeeArrayList* _tmp2_ = NULL;
		gint _child_size = 0;
		GeeArrayList* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		gint _child_index = 0;
		_tmp1_ = self->priv->_children;
		_tmp2_ = _g_object_ref0 (_tmp1_);
		_child_list = _tmp2_;
		_tmp3_ = _child_list;
		_tmp4_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp3_);
		_tmp5_ = _tmp4_;
		_child_size = _tmp5_;
		_child_index = -1;
		while (TRUE) {
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			gint _tmp8_ = 0;
			sdxscenesscene2dActor* child = NULL;
			GeeArrayList* _tmp9_ = NULL;
			gint _tmp10_ = 0;
			gpointer _tmp11_ = NULL;
			sdxscenesscene2dActor* _tmp12_ = NULL;
			sdxscenesscene2dStage* _tmp13_ = NULL;
			_tmp6_ = _child_index;
			_child_index = _tmp6_ + 1;
			_tmp7_ = _child_index;
			_tmp8_ = _child_size;
			if (!(_tmp7_ < _tmp8_)) {
				break;
			}
			_tmp9_ = _child_list;
			_tmp10_ = _child_index;
			_tmp11_ = gee_abstract_list_get ((GeeAbstractList*) _tmp9_, _tmp10_);
			child = (sdxscenesscene2dActor*) _tmp11_;
			_tmp12_ = child;
			_tmp13_ = value;
			sdx_scenes_scene2d_actor_set_stage (_tmp12_, _tmp13_);
			_g_object_unref0 (child);
		}
		_g_object_unref0 (_child_list);
	}
	g_object_notify ((GObject *) self, "stage");
}


static void sdx_scenes_scene2d_group_class_init (sdxscenesscene2dGroupClass * klass) {
	sdx_scenes_scene2d_group_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (sdxscenesscene2dGroupPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_sdx_scenes_scene2d_group_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_sdx_scenes_scene2d_group_set_property;
	G_OBJECT_CLASS (klass)->finalize = sdx_scenes_scene2d_group_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_SCENES_SCENE2D_GROUP_CHILDREN, g_param_spec_object ("children", "children", "children", GEE_TYPE_ARRAY_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_SCENES_SCENE2D_GROUP_STAGE, g_param_spec_object ("stage", "stage", "stage", SDX_SCENES_SCENE2D_TYPE_STAGE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void sdx_scenes_scene2d_group_sdx_scenes_scene2d_cullable_interface_init (sdxscenesscene2dCullableIface * iface) {
	sdx_scenes_scene2d_group_sdx_scenes_scene2d_cullable_parent_iface = g_type_interface_peek_parent (iface);
	iface->setCullingArea = (void (*)(sdxscenesscene2dCullable*, sdxmathRectangle*)) sdx_scenes_scene2d_group_real_setCullingArea;
}


static void sdx_scenes_scene2d_group_instance_init (sdxscenesscene2dGroup * self) {
	GeeArrayList* _tmp0_ = NULL;
	self->priv = SDX_SCENES_SCENE2D_GROUP_GET_PRIVATE (self);
	_tmp0_ = gee_array_list_new (SDX_SCENES_SCENE2D_TYPE_ACTOR, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
	self->priv->_children = _tmp0_;
	self->priv->transform = TRUE;
}


static void sdx_scenes_scene2d_group_finalize (GObject* obj) {
	sdxscenesscene2dGroup * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SDX_SCENES_SCENE2D_TYPE_GROUP, sdxscenesscene2dGroup);
	_g_object_unref0 (self->priv->_children);
	_g_object_unref0 (self->priv->_stage);
	_g_object_unref0 (self->priv->cullingArea);
	G_OBJECT_CLASS (sdx_scenes_scene2d_group_parent_class)->finalize (obj);
}


GType sdx_scenes_scene2d_group_get_type (void) {
	static volatile gsize sdx_scenes_scene2d_group_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_scenes_scene2d_group_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (sdxscenesscene2dGroupClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sdx_scenes_scene2d_group_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (sdxscenesscene2dGroup), 0, (GInstanceInitFunc) sdx_scenes_scene2d_group_instance_init, NULL };
		static const GInterfaceInfo sdx_scenes_scene2d_cullable_info = { (GInterfaceInitFunc) sdx_scenes_scene2d_group_sdx_scenes_scene2d_cullable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType sdx_scenes_scene2d_group_type_id;
		sdx_scenes_scene2d_group_type_id = g_type_register_static (SDX_SCENES_SCENE2D_TYPE_ACTOR, "sdxscenesscene2dGroup", &g_define_type_info, 0);
		g_type_add_interface_static (sdx_scenes_scene2d_group_type_id, SDX_SCENES_SCENE2D_TYPE_CULLABLE, &sdx_scenes_scene2d_cullable_info);
		g_once_init_leave (&sdx_scenes_scene2d_group_type_id__volatile, sdx_scenes_scene2d_group_type_id);
	}
	return sdx_scenes_scene2d_group_type_id__volatile;
}


static void _vala_sdx_scenes_scene2d_group_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	sdxscenesscene2dGroup * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SDX_SCENES_SCENE2D_TYPE_GROUP, sdxscenesscene2dGroup);
	switch (property_id) {
		case SDX_SCENES_SCENE2D_GROUP_CHILDREN:
		g_value_set_object (value, sdx_scenes_scene2d_group_get_children (self));
		break;
		case SDX_SCENES_SCENE2D_GROUP_STAGE:
		g_value_set_object (value, sdx_scenes_scene2d_group_get_stage (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_sdx_scenes_scene2d_group_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	sdxscenesscene2dGroup * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SDX_SCENES_SCENE2D_TYPE_GROUP, sdxscenesscene2dGroup);
	switch (property_id) {
		case SDX_SCENES_SCENE2D_GROUP_CHILDREN:
		sdx_scenes_scene2d_group_set_children (self, g_value_get_object (value));
		break;
		case SDX_SCENES_SCENE2D_GROUP_STAGE:
		sdx_scenes_scene2d_group_set_stage (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



