/* FocusListener.c generated by valac 0.36.4-dirty, the Vala compiler
 * generated from FocusListener.gs, do not modify */


#include <glib.h>
#include <glib-object.h>


#define SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER (sdx_scenes_scene2d_event_listener_get_type ())
#define SDX_SCENES_SCENE2D_EVENT_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER, sdxscenesscene2dEventListener))
#define SDX_SCENES_SCENE2D_IS_EVENT_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER))
#define SDX_SCENES_SCENE2D_EVENT_LISTENER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER, sdxscenesscene2dEventListenerIface))

typedef struct _sdxscenesscene2dEventListener sdxscenesscene2dEventListener;
typedef struct _sdxscenesscene2dEventListenerIface sdxscenesscene2dEventListenerIface;

#define SDX_SCENES_SCENE2D_TYPE_EVENT (sdx_scenes_scene2d_event_get_type ())
#define SDX_SCENES_SCENE2D_EVENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT, sdxscenesscene2dEvent))
#define SDX_SCENES_SCENE2D_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_SCENES_SCENE2D_TYPE_EVENT, sdxscenesscene2dEventClass))
#define SDX_SCENES_SCENE2D_IS_EVENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT))
#define SDX_SCENES_SCENE2D_IS_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_SCENES_SCENE2D_TYPE_EVENT))
#define SDX_SCENES_SCENE2D_EVENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_SCENES_SCENE2D_TYPE_EVENT, sdxscenesscene2dEventClass))

typedef struct _sdxscenesscene2dEvent sdxscenesscene2dEvent;
typedef struct _sdxscenesscene2dEventClass sdxscenesscene2dEventClass;

#define SDX_SCENES_SCENE2D_UTILS_TYPE_FOCUS_LISTENER (sdx_scenes_scene2d_utils_focus_listener_get_type ())
#define SDX_SCENES_SCENE2D_UTILS_FOCUS_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_UTILS_TYPE_FOCUS_LISTENER, sdxscenesscene2dutilsFocusListener))
#define SDX_SCENES_SCENE2D_UTILS_FOCUS_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_SCENES_SCENE2D_UTILS_TYPE_FOCUS_LISTENER, sdxscenesscene2dutilsFocusListenerClass))
#define SDX_SCENES_SCENE2D_UTILS_IS_FOCUS_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_UTILS_TYPE_FOCUS_LISTENER))
#define SDX_SCENES_SCENE2D_UTILS_IS_FOCUS_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_SCENES_SCENE2D_UTILS_TYPE_FOCUS_LISTENER))
#define SDX_SCENES_SCENE2D_UTILS_FOCUS_LISTENER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_SCENES_SCENE2D_UTILS_TYPE_FOCUS_LISTENER, sdxscenesscene2dutilsFocusListenerClass))

typedef struct _sdxscenesscene2dutilsFocusListener sdxscenesscene2dutilsFocusListener;
typedef struct _sdxscenesscene2dutilsFocusListenerClass sdxscenesscene2dutilsFocusListenerClass;
typedef struct _sdxscenesscene2dutilsFocusListenerPrivate sdxscenesscene2dutilsFocusListenerPrivate;

#define SDX_SCENES_SCENE2D_UTILS_TYPE_FOCUS_EVENT (sdx_scenes_scene2d_utils_focus_event_get_type ())
#define SDX_SCENES_SCENE2D_UTILS_FOCUS_EVENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_UTILS_TYPE_FOCUS_EVENT, sdxscenesscene2dutilsFocusEvent))
#define SDX_SCENES_SCENE2D_UTILS_FOCUS_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_SCENES_SCENE2D_UTILS_TYPE_FOCUS_EVENT, sdxscenesscene2dutilsFocusEventClass))
#define SDX_SCENES_SCENE2D_UTILS_IS_FOCUS_EVENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_UTILS_TYPE_FOCUS_EVENT))
#define SDX_SCENES_SCENE2D_UTILS_IS_FOCUS_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_SCENES_SCENE2D_UTILS_TYPE_FOCUS_EVENT))
#define SDX_SCENES_SCENE2D_UTILS_FOCUS_EVENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_SCENES_SCENE2D_UTILS_TYPE_FOCUS_EVENT, sdxscenesscene2dutilsFocusEventClass))

typedef struct _sdxscenesscene2dutilsFocusEvent sdxscenesscene2dutilsFocusEvent;
typedef struct _sdxscenesscene2dutilsFocusEventClass sdxscenesscene2dutilsFocusEventClass;

#define SDX_SCENES_SCENE2D_TYPE_ACTOR (sdx_scenes_scene2d_actor_get_type ())
#define SDX_SCENES_SCENE2D_ACTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActor))
#define SDX_SCENES_SCENE2D_ACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActorClass))
#define SDX_SCENES_SCENE2D_IS_ACTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_SCENES_SCENE2D_TYPE_ACTOR))
#define SDX_SCENES_SCENE2D_IS_ACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_SCENES_SCENE2D_TYPE_ACTOR))
#define SDX_SCENES_SCENE2D_ACTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_SCENES_SCENE2D_TYPE_ACTOR, sdxscenesscene2dActorClass))

typedef struct _sdxscenesscene2dActor sdxscenesscene2dActor;
typedef struct _sdxscenesscene2dActorClass sdxscenesscene2dActorClass;

#define SDX_SCENES_SCENE2D_UTILS_FOCUS_EVENT_TYPE_FOCUS_EVENT_TYPE (sdx_scenes_scene2d_utils_focus_event_focus_event_type_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _sdxscenesscene2dEventListenerIface {
	GTypeInterface parent_iface;
	gboolean (*handle) (sdxscenesscene2dEventListener* self, sdxscenesscene2dEvent* event);
};

struct _sdxscenesscene2dutilsFocusListener {
	GObject parent_instance;
	sdxscenesscene2dutilsFocusListenerPrivate * priv;
};

struct _sdxscenesscene2dutilsFocusListenerClass {
	GObjectClass parent_class;
	void (*keyboardFocusChanged) (sdxscenesscene2dutilsFocusListener* self, sdxscenesscene2dutilsFocusEvent* event, sdxscenesscene2dActor* actor, gboolean focused);
	void (*scrollFocusChanged) (sdxscenesscene2dutilsFocusListener* self, sdxscenesscene2dutilsFocusEvent* event, sdxscenesscene2dActor* actor, gboolean focused);
};

typedef enum  {
	SDX_SCENES_SCENE2D_UTILS_FOCUS_EVENT_FOCUS_EVENT_TYPE_keyboard,
	SDX_SCENES_SCENE2D_UTILS_FOCUS_EVENT_FOCUS_EVENT_TYPE_scroll
} sdxscenesscene2dutilsFocusEventFocusEventType;


static gpointer sdx_scenes_scene2d_utils_focus_listener_parent_class = NULL;
static sdxscenesscene2dEventListenerIface * sdx_scenes_scene2d_utils_focus_listener_sdx_scenes_scene2d_event_listener_parent_iface = NULL;

GType sdx_scenes_scene2d_event_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_event_listener_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_utils_focus_listener_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_utils_focus_event_get_type (void) G_GNUC_CONST;
GType sdx_scenes_scene2d_actor_get_type (void) G_GNUC_CONST;
enum  {
	SDX_SCENES_SCENE2D_UTILS_FOCUS_LISTENER_DUMMY_PROPERTY
};
static gboolean sdx_scenes_scene2d_utils_focus_listener_real_handle (sdxscenesscene2dEventListener* base, sdxscenesscene2dEvent* e);
GType sdx_scenes_scene2d_utils_focus_event_focus_event_type_get_type (void) G_GNUC_CONST;
sdxscenesscene2dutilsFocusEventFocusEventType sdx_scenes_scene2d_utils_focus_event_getType (sdxscenesscene2dutilsFocusEvent* self);
void sdx_scenes_scene2d_utils_focus_listener_keyboardFocusChanged (sdxscenesscene2dutilsFocusListener* self, sdxscenesscene2dutilsFocusEvent* event, sdxscenesscene2dActor* actor, gboolean focused);
sdxscenesscene2dActor* sdx_scenes_scene2d_event_getTarget (sdxscenesscene2dEvent* self);
gboolean sdx_scenes_scene2d_utils_focus_event_isFocused (sdxscenesscene2dutilsFocusEvent* self);
void sdx_scenes_scene2d_utils_focus_listener_scrollFocusChanged (sdxscenesscene2dutilsFocusListener* self, sdxscenesscene2dutilsFocusEvent* event, sdxscenesscene2dActor* actor, gboolean focused);
static void sdx_scenes_scene2d_utils_focus_listener_real_keyboardFocusChanged (sdxscenesscene2dutilsFocusListener* self, sdxscenesscene2dutilsFocusEvent* event, sdxscenesscene2dActor* actor, gboolean focused);
static void sdx_scenes_scene2d_utils_focus_listener_real_scrollFocusChanged (sdxscenesscene2dutilsFocusListener* self, sdxscenesscene2dutilsFocusEvent* event, sdxscenesscene2dActor* actor, gboolean focused);
sdxscenesscene2dutilsFocusListener* sdx_scenes_scene2d_utils_focus_listener_construct (GType object_type);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gboolean sdx_scenes_scene2d_utils_focus_listener_real_handle (sdxscenesscene2dEventListener* base, sdxscenesscene2dEvent* e) {
	sdxscenesscene2dutilsFocusListener * self;
	gboolean result = FALSE;
	sdxscenesscene2dutilsFocusEvent* event = NULL;
	sdxscenesscene2dEvent* _tmp0_;
	sdxscenesscene2dutilsFocusEvent* _tmp1_;
	sdxscenesscene2dutilsFocusEvent* _tmp2_;
	self = (sdxscenesscene2dutilsFocusListener*) base;
	g_return_val_if_fail (e != NULL, FALSE);
	_tmp0_ = e;
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, SDX_SCENES_SCENE2D_UTILS_TYPE_FOCUS_EVENT) ? ((sdxscenesscene2dutilsFocusEvent*) _tmp0_) : NULL);
	event = _tmp1_;
	_tmp2_ = event;
	if (_tmp2_ != NULL) {
		sdxscenesscene2dutilsFocusEvent* _tmp3_;
		sdxscenesscene2dutilsFocusEventFocusEventType _tmp4_;
		_tmp3_ = event;
		_tmp4_ = sdx_scenes_scene2d_utils_focus_event_getType (_tmp3_);
		switch (_tmp4_) {
			case SDX_SCENES_SCENE2D_UTILS_FOCUS_EVENT_FOCUS_EVENT_TYPE_keyboard:
			{
				{
					sdxscenesscene2dutilsFocusEvent* _tmp5_;
					sdxscenesscene2dutilsFocusEvent* _tmp6_;
					sdxscenesscene2dActor* _tmp7_;
					sdxscenesscene2dActor* _tmp8_;
					sdxscenesscene2dutilsFocusEvent* _tmp9_;
					gboolean _tmp10_;
					_tmp5_ = event;
					_tmp6_ = event;
					_tmp7_ = sdx_scenes_scene2d_event_getTarget ((sdxscenesscene2dEvent*) _tmp6_);
					_tmp8_ = _tmp7_;
					_tmp9_ = event;
					_tmp10_ = sdx_scenes_scene2d_utils_focus_event_isFocused (_tmp9_);
					sdx_scenes_scene2d_utils_focus_listener_keyboardFocusChanged (self, _tmp5_, _tmp8_, _tmp10_);
					_g_object_unref0 (_tmp8_);
				}
				break;
			}
			case SDX_SCENES_SCENE2D_UTILS_FOCUS_EVENT_FOCUS_EVENT_TYPE_scroll:
			{
				{
					sdxscenesscene2dutilsFocusEvent* _tmp11_;
					sdxscenesscene2dutilsFocusEvent* _tmp12_;
					sdxscenesscene2dActor* _tmp13_;
					sdxscenesscene2dActor* _tmp14_;
					sdxscenesscene2dutilsFocusEvent* _tmp15_;
					gboolean _tmp16_;
					_tmp11_ = event;
					_tmp12_ = event;
					_tmp13_ = sdx_scenes_scene2d_event_getTarget ((sdxscenesscene2dEvent*) _tmp12_);
					_tmp14_ = _tmp13_;
					_tmp15_ = event;
					_tmp16_ = sdx_scenes_scene2d_utils_focus_event_isFocused (_tmp15_);
					sdx_scenes_scene2d_utils_focus_listener_scrollFocusChanged (self, _tmp11_, _tmp14_, _tmp16_);
					_g_object_unref0 (_tmp14_);
				}
				break;
			}
			default:
			break;
		}
	}
	result = FALSE;
	_g_object_unref0 (event);
	return result;
}


static void sdx_scenes_scene2d_utils_focus_listener_real_keyboardFocusChanged (sdxscenesscene2dutilsFocusListener* self, sdxscenesscene2dutilsFocusEvent* event, sdxscenesscene2dActor* actor, gboolean focused) {
	g_critical ("Type `%s' does not implement abstract method `sdx_scenes_scene2d_utils_focus_listener_keyboardFocusChanged'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void sdx_scenes_scene2d_utils_focus_listener_keyboardFocusChanged (sdxscenesscene2dutilsFocusListener* self, sdxscenesscene2dutilsFocusEvent* event, sdxscenesscene2dActor* actor, gboolean focused) {
	g_return_if_fail (self != NULL);
	SDX_SCENES_SCENE2D_UTILS_FOCUS_LISTENER_GET_CLASS (self)->keyboardFocusChanged (self, event, actor, focused);
}


static void sdx_scenes_scene2d_utils_focus_listener_real_scrollFocusChanged (sdxscenesscene2dutilsFocusListener* self, sdxscenesscene2dutilsFocusEvent* event, sdxscenesscene2dActor* actor, gboolean focused) {
	g_critical ("Type `%s' does not implement abstract method `sdx_scenes_scene2d_utils_focus_listener_scrollFocusChanged'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void sdx_scenes_scene2d_utils_focus_listener_scrollFocusChanged (sdxscenesscene2dutilsFocusListener* self, sdxscenesscene2dutilsFocusEvent* event, sdxscenesscene2dActor* actor, gboolean focused) {
	g_return_if_fail (self != NULL);
	SDX_SCENES_SCENE2D_UTILS_FOCUS_LISTENER_GET_CLASS (self)->scrollFocusChanged (self, event, actor, focused);
}


sdxscenesscene2dutilsFocusListener* sdx_scenes_scene2d_utils_focus_listener_construct (GType object_type) {
	sdxscenesscene2dutilsFocusListener * self = NULL;
	self = (sdxscenesscene2dutilsFocusListener*) g_object_new (object_type, NULL);
	return self;
}


static void sdx_scenes_scene2d_utils_focus_listener_class_init (sdxscenesscene2dutilsFocusListenerClass * klass) {
	sdx_scenes_scene2d_utils_focus_listener_parent_class = g_type_class_peek_parent (klass);
	((sdxscenesscene2dutilsFocusListenerClass *) klass)->keyboardFocusChanged = (void (*) (sdxscenesscene2dutilsFocusListener *, sdxscenesscene2dutilsFocusEvent*, sdxscenesscene2dActor*, gboolean)) sdx_scenes_scene2d_utils_focus_listener_real_keyboardFocusChanged;
	((sdxscenesscene2dutilsFocusListenerClass *) klass)->scrollFocusChanged = (void (*) (sdxscenesscene2dutilsFocusListener *, sdxscenesscene2dutilsFocusEvent*, sdxscenesscene2dActor*, gboolean)) sdx_scenes_scene2d_utils_focus_listener_real_scrollFocusChanged;
}


static void sdx_scenes_scene2d_utils_focus_listener_sdx_scenes_scene2d_event_listener_interface_init (sdxscenesscene2dEventListenerIface * iface) {
	sdx_scenes_scene2d_utils_focus_listener_sdx_scenes_scene2d_event_listener_parent_iface = g_type_interface_peek_parent (iface);
	iface->handle = (gboolean (*) (sdxscenesscene2dEventListener *, sdxscenesscene2dEvent*)) sdx_scenes_scene2d_utils_focus_listener_real_handle;
}


static void sdx_scenes_scene2d_utils_focus_listener_instance_init (sdxscenesscene2dutilsFocusListener * self) {
}


GType sdx_scenes_scene2d_utils_focus_listener_get_type (void) {
	static volatile gsize sdx_scenes_scene2d_utils_focus_listener_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_scenes_scene2d_utils_focus_listener_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (sdxscenesscene2dutilsFocusListenerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sdx_scenes_scene2d_utils_focus_listener_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (sdxscenesscene2dutilsFocusListener), 0, (GInstanceInitFunc) sdx_scenes_scene2d_utils_focus_listener_instance_init, NULL };
		static const GInterfaceInfo sdx_scenes_scene2d_event_listener_info = { (GInterfaceInitFunc) sdx_scenes_scene2d_utils_focus_listener_sdx_scenes_scene2d_event_listener_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType sdx_scenes_scene2d_utils_focus_listener_type_id;
		sdx_scenes_scene2d_utils_focus_listener_type_id = g_type_register_static (G_TYPE_OBJECT, "sdxscenesscene2dutilsFocusListener", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_type_add_interface_static (sdx_scenes_scene2d_utils_focus_listener_type_id, SDX_SCENES_SCENE2D_TYPE_EVENT_LISTENER, &sdx_scenes_scene2d_event_listener_info);
		g_once_init_leave (&sdx_scenes_scene2d_utils_focus_listener_type_id__volatile, sdx_scenes_scene2d_utils_focus_listener_type_id);
	}
	return sdx_scenes_scene2d_utils_focus_listener_type_id__volatile;
}



