/* Align.c generated by valac 0.34.9, the Vala compiler
 * generated from Align.gs, do not modify */


#include <glib.h>
#include <glib-object.h>


#define SDX_UTILS_TYPE_ALIGN (sdx_utils_align_get_type ())

typedef enum  {
	SDX_UTILS_ALIGN_center = 1 << 0,
	SDX_UTILS_ALIGN_top = 1 << 1,
	SDX_UTILS_ALIGN_bottom = 1 << 2,
	SDX_UTILS_ALIGN_left = 1 << 3,
	SDX_UTILS_ALIGN_right = 1 << 4,
	SDX_UTILS_ALIGN_topLeft = SDX_UTILS_ALIGN_top | SDX_UTILS_ALIGN_left,
	SDX_UTILS_ALIGN_topRight = SDX_UTILS_ALIGN_top | SDX_UTILS_ALIGN_right,
	SDX_UTILS_ALIGN_bottomLeft = SDX_UTILS_ALIGN_bottom | SDX_UTILS_ALIGN_left,
	SDX_UTILS_ALIGN_bottomRight = SDX_UTILS_ALIGN_bottom | SDX_UTILS_ALIGN_right
} sdxutilsAlign;



GType sdx_utils_align_get_type (void) G_GNUC_CONST;


GType sdx_utils_align_get_type (void) {
	static volatile gsize sdx_utils_align_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_utils_align_type_id__volatile)) {
		static const GEnumValue values[] = {{SDX_UTILS_ALIGN_center, "SDX_UTILS_ALIGN_center", "center"}, {SDX_UTILS_ALIGN_top, "SDX_UTILS_ALIGN_top", "top"}, {SDX_UTILS_ALIGN_bottom, "SDX_UTILS_ALIGN_bottom", "bottom"}, {SDX_UTILS_ALIGN_left, "SDX_UTILS_ALIGN_left", "left"}, {SDX_UTILS_ALIGN_right, "SDX_UTILS_ALIGN_right", "right"}, {SDX_UTILS_ALIGN_topLeft, "SDX_UTILS_ALIGN_topLeft", "topleft"}, {SDX_UTILS_ALIGN_topRight, "SDX_UTILS_ALIGN_topRight", "topright"}, {SDX_UTILS_ALIGN_bottomLeft, "SDX_UTILS_ALIGN_bottomLeft", "bottomleft"}, {SDX_UTILS_ALIGN_bottomRight, "SDX_UTILS_ALIGN_bottomRight", "bottomright"}, {0, NULL, NULL}};
		GType sdx_utils_align_type_id;
		sdx_utils_align_type_id = g_enum_register_static ("sdxutilsAlign", values);
		g_once_init_leave (&sdx_utils_align_type_id__volatile, sdx_utils_align_type_id);
	}
	return sdx_utils_align_type_id__volatile;
}



