/* Scaling.c generated by valac 0.34.9, the Vala compiler
 * generated from Scaling.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>


#define SDX_SCENES_SCENE2D_UI_TYPE_SCALING (sdx_scenes_scene2d_ui_scaling_get_type ())

#define SDX_MATH_TYPE_VECTOR2 (sdx_math_vector2_get_type ())
#define SDX_MATH_VECTOR2(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_MATH_TYPE_VECTOR2, sdxmathVector2))
#define SDX_MATH_VECTOR2_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_MATH_TYPE_VECTOR2, sdxmathVector2Class))
#define SDX_MATH_IS_VECTOR2(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_MATH_TYPE_VECTOR2))
#define SDX_MATH_IS_VECTOR2_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_MATH_TYPE_VECTOR2))
#define SDX_MATH_VECTOR2_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_MATH_TYPE_VECTOR2, sdxmathVector2Class))

typedef struct _sdxmathVector2 sdxmathVector2;
typedef struct _sdxmathVector2Class sdxmathVector2Class;
typedef struct _sdxmathVector2Private sdxmathVector2Private;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

typedef enum  {
	SDX_SCENES_SCENE2D_UI_SCALING_fit,
	SDX_SCENES_SCENE2D_UI_SCALING_fill,
	SDX_SCENES_SCENE2D_UI_SCALING_fillX,
	SDX_SCENES_SCENE2D_UI_SCALING_fillY,
	SDX_SCENES_SCENE2D_UI_SCALING_stretch,
	SDX_SCENES_SCENE2D_UI_SCALING_stretchX,
	SDX_SCENES_SCENE2D_UI_SCALING_stretchY,
	SDX_SCENES_SCENE2D_UI_SCALING_none
} sdxscenesscene2duiScaling;

struct _sdxmathVector2 {
	GObject parent_instance;
	sdxmathVector2Private * priv;
	gdouble x;
	gdouble y;
};

struct _sdxmathVector2Class {
	GObjectClass parent_class;
};



GType sdx_scenes_scene2d_ui_scaling_get_type (void) G_GNUC_CONST;
GType sdx_math_vector2_get_type (void) G_GNUC_CONST;
sdxmathVector2* sdx_scenes_scene2d_ui_scaling_apply (sdxscenesscene2duiScaling self, gdouble sourceWidth, gdouble sourceHeight, gdouble targetWidth, gdouble targetHeight);
sdxmathVector2* sdx_math_vector2_new (gdouble x, gdouble y);
sdxmathVector2* sdx_math_vector2_construct (GType object_type, gdouble x, gdouble y);


sdxmathVector2* sdx_scenes_scene2d_ui_scaling_apply (sdxscenesscene2duiScaling self, gdouble sourceWidth, gdouble sourceHeight, gdouble targetWidth, gdouble targetHeight) {
	sdxmathVector2* result = NULL;
	sdxmathVector2* temp = NULL;
	sdxmathVector2* _tmp0_ = NULL;
	_tmp0_ = sdx_math_vector2_new ((gdouble) 0, (gdouble) 0);
	temp = _tmp0_;
	switch (self) {
		case SDX_SCENES_SCENE2D_UI_SCALING_fit:
		{
			{
				gdouble targetRatio = 0.0;
				gdouble _tmp1_ = 0.0;
				gdouble _tmp2_ = 0.0;
				gdouble sourceRatio = 0.0;
				gdouble _tmp3_ = 0.0;
				gdouble _tmp4_ = 0.0;
				gdouble _tmp5_ = 0.0;
				gdouble _tmp6_ = 0.0;
				gdouble _tmp7_ = 0.0;
				gdouble scale = 0.0;
				sdxmathVector2* _tmp12_ = NULL;
				gdouble _tmp13_ = 0.0;
				gdouble _tmp14_ = 0.0;
				sdxmathVector2* _tmp15_ = NULL;
				gdouble _tmp16_ = 0.0;
				gdouble _tmp17_ = 0.0;
				_tmp1_ = targetHeight;
				_tmp2_ = targetWidth;
				targetRatio = _tmp1_ / _tmp2_;
				_tmp3_ = sourceHeight;
				_tmp4_ = sourceWidth;
				sourceRatio = _tmp3_ / _tmp4_;
				_tmp6_ = targetRatio;
				_tmp7_ = sourceRatio;
				if (_tmp6_ > _tmp7_) {
					gdouble _tmp8_ = 0.0;
					gdouble _tmp9_ = 0.0;
					_tmp8_ = targetWidth;
					_tmp9_ = sourceWidth;
					_tmp5_ = _tmp8_ / _tmp9_;
				} else {
					gdouble _tmp10_ = 0.0;
					gdouble _tmp11_ = 0.0;
					_tmp10_ = targetHeight;
					_tmp11_ = sourceHeight;
					_tmp5_ = _tmp10_ / _tmp11_;
				}
				scale = _tmp5_;
				_tmp12_ = temp;
				_tmp13_ = sourceWidth;
				_tmp14_ = scale;
				_tmp12_->x = _tmp13_ * _tmp14_;
				_tmp15_ = temp;
				_tmp16_ = sourceHeight;
				_tmp17_ = scale;
				_tmp15_->y = _tmp16_ * _tmp17_;
				break;
			}
		}
		case SDX_SCENES_SCENE2D_UI_SCALING_fill:
		{
			{
				gdouble targetRatio = 0.0;
				gdouble _tmp18_ = 0.0;
				gdouble _tmp19_ = 0.0;
				gdouble sourceRatio = 0.0;
				gdouble _tmp20_ = 0.0;
				gdouble _tmp21_ = 0.0;
				gdouble _tmp22_ = 0.0;
				gdouble _tmp23_ = 0.0;
				gdouble _tmp24_ = 0.0;
				gdouble scale = 0.0;
				sdxmathVector2* _tmp29_ = NULL;
				gdouble _tmp30_ = 0.0;
				gdouble _tmp31_ = 0.0;
				sdxmathVector2* _tmp32_ = NULL;
				gdouble _tmp33_ = 0.0;
				gdouble _tmp34_ = 0.0;
				_tmp18_ = targetHeight;
				_tmp19_ = targetWidth;
				targetRatio = _tmp18_ / _tmp19_;
				_tmp20_ = sourceHeight;
				_tmp21_ = sourceWidth;
				sourceRatio = _tmp20_ / _tmp21_;
				_tmp23_ = targetRatio;
				_tmp24_ = sourceRatio;
				if (_tmp23_ < _tmp24_) {
					gdouble _tmp25_ = 0.0;
					gdouble _tmp26_ = 0.0;
					_tmp25_ = targetWidth;
					_tmp26_ = sourceWidth;
					_tmp22_ = _tmp25_ / _tmp26_;
				} else {
					gdouble _tmp27_ = 0.0;
					gdouble _tmp28_ = 0.0;
					_tmp27_ = targetHeight;
					_tmp28_ = sourceHeight;
					_tmp22_ = _tmp27_ / _tmp28_;
				}
				scale = _tmp22_;
				_tmp29_ = temp;
				_tmp30_ = sourceWidth;
				_tmp31_ = scale;
				_tmp29_->x = _tmp30_ * _tmp31_;
				_tmp32_ = temp;
				_tmp33_ = sourceHeight;
				_tmp34_ = scale;
				_tmp32_->y = _tmp33_ * _tmp34_;
				break;
			}
		}
		case SDX_SCENES_SCENE2D_UI_SCALING_fillX:
		{
			{
				gdouble scale = 0.0;
				gdouble _tmp35_ = 0.0;
				gdouble _tmp36_ = 0.0;
				sdxmathVector2* _tmp37_ = NULL;
				gdouble _tmp38_ = 0.0;
				gdouble _tmp39_ = 0.0;
				sdxmathVector2* _tmp40_ = NULL;
				gdouble _tmp41_ = 0.0;
				gdouble _tmp42_ = 0.0;
				_tmp35_ = targetWidth;
				_tmp36_ = sourceWidth;
				scale = _tmp35_ / _tmp36_;
				_tmp37_ = temp;
				_tmp38_ = sourceWidth;
				_tmp39_ = scale;
				_tmp37_->x = _tmp38_ * _tmp39_;
				_tmp40_ = temp;
				_tmp41_ = sourceHeight;
				_tmp42_ = scale;
				_tmp40_->y = _tmp41_ * _tmp42_;
				break;
			}
		}
		case SDX_SCENES_SCENE2D_UI_SCALING_fillY:
		{
			{
				gdouble scale = 0.0;
				gdouble _tmp43_ = 0.0;
				gdouble _tmp44_ = 0.0;
				sdxmathVector2* _tmp45_ = NULL;
				gdouble _tmp46_ = 0.0;
				gdouble _tmp47_ = 0.0;
				sdxmathVector2* _tmp48_ = NULL;
				gdouble _tmp49_ = 0.0;
				gdouble _tmp50_ = 0.0;
				_tmp43_ = targetHeight;
				_tmp44_ = sourceHeight;
				scale = _tmp43_ / _tmp44_;
				_tmp45_ = temp;
				_tmp46_ = sourceWidth;
				_tmp47_ = scale;
				_tmp45_->x = _tmp46_ * _tmp47_;
				_tmp48_ = temp;
				_tmp49_ = sourceHeight;
				_tmp50_ = scale;
				_tmp48_->y = _tmp49_ * _tmp50_;
				break;
			}
		}
		case SDX_SCENES_SCENE2D_UI_SCALING_stretch:
		{
			sdxmathVector2* _tmp51_ = NULL;
			gdouble _tmp52_ = 0.0;
			sdxmathVector2* _tmp53_ = NULL;
			gdouble _tmp54_ = 0.0;
			_tmp51_ = temp;
			_tmp52_ = targetWidth;
			_tmp51_->x = _tmp52_;
			_tmp53_ = temp;
			_tmp54_ = targetHeight;
			_tmp53_->y = _tmp54_;
			break;
		}
		case SDX_SCENES_SCENE2D_UI_SCALING_stretchX:
		{
			sdxmathVector2* _tmp55_ = NULL;
			gdouble _tmp56_ = 0.0;
			sdxmathVector2* _tmp57_ = NULL;
			gdouble _tmp58_ = 0.0;
			_tmp55_ = temp;
			_tmp56_ = targetWidth;
			_tmp55_->x = _tmp56_;
			_tmp57_ = temp;
			_tmp58_ = sourceHeight;
			_tmp57_->y = _tmp58_;
			break;
		}
		case SDX_SCENES_SCENE2D_UI_SCALING_stretchY:
		{
			sdxmathVector2* _tmp59_ = NULL;
			gdouble _tmp60_ = 0.0;
			sdxmathVector2* _tmp61_ = NULL;
			gdouble _tmp62_ = 0.0;
			_tmp59_ = temp;
			_tmp60_ = sourceWidth;
			_tmp59_->x = _tmp60_;
			_tmp61_ = temp;
			_tmp62_ = targetHeight;
			_tmp61_->y = _tmp62_;
			break;
		}
		case SDX_SCENES_SCENE2D_UI_SCALING_none:
		{
			sdxmathVector2* _tmp63_ = NULL;
			gdouble _tmp64_ = 0.0;
			sdxmathVector2* _tmp65_ = NULL;
			gdouble _tmp66_ = 0.0;
			_tmp63_ = temp;
			_tmp64_ = sourceWidth;
			_tmp63_->x = _tmp64_;
			_tmp65_ = temp;
			_tmp66_ = sourceHeight;
			_tmp65_->y = _tmp66_;
			break;
		}
		default:
		break;
	}
	result = temp;
	return result;
}


GType sdx_scenes_scene2d_ui_scaling_get_type (void) {
	static volatile gsize sdx_scenes_scene2d_ui_scaling_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_scenes_scene2d_ui_scaling_type_id__volatile)) {
		static const GEnumValue values[] = {{SDX_SCENES_SCENE2D_UI_SCALING_fit, "SDX_SCENES_SCENE2D_UI_SCALING_fit", "fit"}, {SDX_SCENES_SCENE2D_UI_SCALING_fill, "SDX_SCENES_SCENE2D_UI_SCALING_fill", "fill"}, {SDX_SCENES_SCENE2D_UI_SCALING_fillX, "SDX_SCENES_SCENE2D_UI_SCALING_fillX", "fillx"}, {SDX_SCENES_SCENE2D_UI_SCALING_fillY, "SDX_SCENES_SCENE2D_UI_SCALING_fillY", "filly"}, {SDX_SCENES_SCENE2D_UI_SCALING_stretch, "SDX_SCENES_SCENE2D_UI_SCALING_stretch", "stretch"}, {SDX_SCENES_SCENE2D_UI_SCALING_stretchX, "SDX_SCENES_SCENE2D_UI_SCALING_stretchX", "stretchx"}, {SDX_SCENES_SCENE2D_UI_SCALING_stretchY, "SDX_SCENES_SCENE2D_UI_SCALING_stretchY", "stretchy"}, {SDX_SCENES_SCENE2D_UI_SCALING_none, "SDX_SCENES_SCENE2D_UI_SCALING_none", "none"}, {0, NULL, NULL}};
		GType sdx_scenes_scene2d_ui_scaling_type_id;
		sdx_scenes_scene2d_ui_scaling_type_id = g_enum_register_static ("sdxscenesscene2duiScaling", values);
		g_once_init_leave (&sdx_scenes_scene2d_ui_scaling_type_id__volatile, sdx_scenes_scene2d_ui_scaling_type_id);
	}
	return sdx_scenes_scene2d_ui_scaling_type_id__volatile;
}



