/* Audio.c generated by valac 0.34.9, the Vala compiler
 * generated from Audio.gs, do not modify */


#include <glib.h>
#include <glib-object.h>


#define SDX_TYPE_AUDIO (sdx_audio_get_type ())
#define SDX_AUDIO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_AUDIO, sdxAudio))
#define SDX_AUDIO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_TYPE_AUDIO, sdxAudioClass))
#define SDX_IS_AUDIO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_AUDIO))
#define SDX_IS_AUDIO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_TYPE_AUDIO))
#define SDX_AUDIO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_TYPE_AUDIO, sdxAudioClass))

typedef struct _sdxAudio sdxAudio;
typedef struct _sdxAudioClass sdxAudioClass;
typedef struct _sdxAudioPrivate sdxAudioPrivate;

#define SDX_FILES_TYPE_FILE_HANDLE (sdx_files_file_handle_get_type ())
#define SDX_FILES_FILE_HANDLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_FILES_TYPE_FILE_HANDLE, sdxfilesFileHandle))
#define SDX_FILES_FILE_HANDLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_FILES_TYPE_FILE_HANDLE, sdxfilesFileHandleClass))
#define SDX_FILES_IS_FILE_HANDLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_FILES_TYPE_FILE_HANDLE))
#define SDX_FILES_IS_FILE_HANDLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_FILES_TYPE_FILE_HANDLE))
#define SDX_FILES_FILE_HANDLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_FILES_TYPE_FILE_HANDLE, sdxfilesFileHandleClass))

typedef struct _sdxfilesFileHandle sdxfilesFileHandle;
typedef struct _sdxfilesFileHandleClass sdxfilesFileHandleClass;

#define SDX_AUDIO_TYPE_SOUND (sdx_audio_sound_get_type ())
#define SDX_AUDIO_SOUND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_AUDIO_TYPE_SOUND, sdxaudioSound))
#define SDX_AUDIO_SOUND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_AUDIO_TYPE_SOUND, sdxaudioSoundClass))
#define SDX_AUDIO_IS_SOUND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_AUDIO_TYPE_SOUND))
#define SDX_AUDIO_IS_SOUND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_AUDIO_TYPE_SOUND))
#define SDX_AUDIO_SOUND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_AUDIO_TYPE_SOUND, sdxaudioSoundClass))

typedef struct _sdxaudioSound sdxaudioSound;
typedef struct _sdxaudioSoundClass sdxaudioSoundClass;

struct _sdxAudio {
	GObject parent_instance;
	sdxAudioPrivate * priv;
};

struct _sdxAudioClass {
	GObjectClass parent_class;
};


static gpointer sdx_audio_parent_class = NULL;

GType sdx_audio_get_type (void) G_GNUC_CONST;
enum  {
	SDX_AUDIO_DUMMY_PROPERTY
};
GType sdx_files_file_handle_get_type (void) G_GNUC_CONST;
GType sdx_audio_sound_get_type (void) G_GNUC_CONST;
sdxaudioSound* sdx_audio_newSound (sdxAudio* self, sdxfilesFileHandle* file);
sdxaudioSound* sdx_audio_sound_new (sdxfilesFileHandle* file);
sdxaudioSound* sdx_audio_sound_construct (GType object_type, sdxfilesFileHandle* file);
sdxAudio* sdx_audio_new (void);
sdxAudio* sdx_audio_construct (GType object_type);


sdxaudioSound* sdx_audio_newSound (sdxAudio* self, sdxfilesFileHandle* file) {
	sdxaudioSound* result = NULL;
	sdxfilesFileHandle* _tmp0_ = NULL;
	sdxaudioSound* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (file != NULL, NULL);
	_tmp0_ = file;
	_tmp1_ = sdx_audio_sound_new (_tmp0_);
	result = _tmp1_;
	return result;
}


sdxAudio* sdx_audio_construct (GType object_type) {
	sdxAudio * self = NULL;
	self = (sdxAudio*) g_object_new (object_type, NULL);
	return self;
}


sdxAudio* sdx_audio_new (void) {
	return sdx_audio_construct (SDX_TYPE_AUDIO);
}


static void sdx_audio_class_init (sdxAudioClass * klass) {
	sdx_audio_parent_class = g_type_class_peek_parent (klass);
}


static void sdx_audio_instance_init (sdxAudio * self) {
}


GType sdx_audio_get_type (void) {
	static volatile gsize sdx_audio_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_audio_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (sdxAudioClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sdx_audio_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (sdxAudio), 0, (GInstanceInitFunc) sdx_audio_instance_init, NULL };
		GType sdx_audio_type_id;
		sdx_audio_type_id = g_type_register_static (G_TYPE_OBJECT, "sdxAudio", &g_define_type_info, 0);
		g_once_init_leave (&sdx_audio_type_id__volatile, sdx_audio_type_id);
	}
	return sdx_audio_type_id__volatile;
}



