/* Files.c generated by valac 0.36.4-dirty, the Vala compiler
 * generated from Files.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define SDX_TYPE_FILE_TYPE (sdx_file_type_get_type ())

#define SDX_TYPE_FILES (sdx_files_get_type ())
#define SDX_FILES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_FILES, sdxFiles))
#define SDX_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_TYPE_FILES, sdxFilesClass))
#define SDX_IS_FILES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_FILES))
#define SDX_IS_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_TYPE_FILES))
#define SDX_FILES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_TYPE_FILES, sdxFilesClass))

typedef struct _sdxFiles sdxFiles;
typedef struct _sdxFilesClass sdxFilesClass;
typedef struct _sdxFilesPrivate sdxFilesPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define SDX_FILES_TYPE_FILE_HANDLE (sdx_files_file_handle_get_type ())
#define SDX_FILES_FILE_HANDLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_FILES_TYPE_FILE_HANDLE, sdxfilesFileHandle))
#define SDX_FILES_FILE_HANDLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_FILES_TYPE_FILE_HANDLE, sdxfilesFileHandleClass))
#define SDX_FILES_IS_FILE_HANDLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_FILES_TYPE_FILE_HANDLE))
#define SDX_FILES_IS_FILE_HANDLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_FILES_TYPE_FILE_HANDLE))
#define SDX_FILES_FILE_HANDLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_FILES_TYPE_FILE_HANDLE, sdxfilesFileHandleClass))

typedef struct _sdxfilesFileHandle sdxfilesFileHandle;
typedef struct _sdxfilesFileHandleClass sdxfilesFileHandleClass;

typedef enum  {
	SDX_FILE_TYPE_Internal,
	SDX_FILE_TYPE_Resource,
	SDX_FILE_TYPE_External,
	SDX_FILE_TYPE_Absolute,
	SDX_FILE_TYPE_Local
} sdxFileType;

struct _sdxFiles {
	GObject parent_instance;
	sdxFilesPrivate * priv;
};

struct _sdxFilesClass {
	GObjectClass parent_class;
};

struct _sdxFilesPrivate {
	gboolean _isResource;
	gchar* _resourcePath;
};


static gpointer sdx_files_parent_class = NULL;

GType sdx_file_type_get_type (void) G_GNUC_CONST;
GType sdx_files_get_type (void) G_GNUC_CONST;
#define SDX_FILES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SDX_TYPE_FILES, sdxFilesPrivate))
enum  {
	SDX_FILES_DUMMY_PROPERTY,
	SDX_FILES_IS_RESOURCE,
	SDX_FILES_RESOURCE_PATH
};
#define SDX_FILES_separator "/"
sdxFiles* sdx_files_new (const gchar* resourcePath);
sdxFiles* sdx_files_construct (GType object_type, const gchar* resourcePath);
GType sdx_files_file_handle_get_type (void) G_GNUC_CONST;
sdxfilesFileHandle* sdx_files_getHandle (sdxFiles* self, const gchar* path, sdxFileType type);
sdxfilesFileHandle* sdx_files_file_handle_new (const gchar* fileName, sdxFileType type);
sdxfilesFileHandle* sdx_files_file_handle_construct (GType object_type, const gchar* fileName, sdxFileType type);
sdxfilesFileHandle* sdx_files_internal (sdxFiles* self, const gchar* path);
sdxfilesFileHandle* sdx_files_resource (sdxFiles* self, const gchar* path);
sdxfilesFileHandle* sdx_files_external (sdxFiles* self, const gchar* path);
sdxfilesFileHandle* sdx_files_absolute (sdxFiles* self, const gchar* path);
sdxfilesFileHandle* sdx_files_local (sdxFiles* self, const gchar* path);
gboolean sdx_files_get_isResource (sdxFiles* self);
const gchar* sdx_files_get_resourcePath (sdxFiles* self);
static void sdx_files_finalize (GObject * obj);
static void _vala_sdx_files_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);


GType sdx_file_type_get_type (void) {
	static volatile gsize sdx_file_type_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_file_type_type_id__volatile)) {
		static const GEnumValue values[] = {{SDX_FILE_TYPE_Internal, "SDX_FILE_TYPE_Internal", "internal"}, {SDX_FILE_TYPE_Resource, "SDX_FILE_TYPE_Resource", "resource"}, {SDX_FILE_TYPE_External, "SDX_FILE_TYPE_External", "external"}, {SDX_FILE_TYPE_Absolute, "SDX_FILE_TYPE_Absolute", "absolute"}, {SDX_FILE_TYPE_Local, "SDX_FILE_TYPE_Local", "local"}, {0, NULL, NULL}};
		GType sdx_file_type_type_id;
		sdx_file_type_type_id = g_enum_register_static ("sdxFileType", values);
		g_once_init_leave (&sdx_file_type_type_id__volatile, sdx_file_type_type_id);
	}
	return sdx_file_type_type_id__volatile;
}


static gint string_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gchar* _result_ = NULL;
	gint _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (needle != NULL, 0);
	_tmp0_ = start_index;
	_tmp1_ = needle;
	_tmp2_ = strstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
	_result_ = _tmp2_;
	_tmp3_ = _result_;
	if (_tmp3_ != NULL) {
		gchar* _tmp4_;
		_tmp4_ = _result_;
		result = (gint) (_tmp4_ - ((gchar*) self));
		return result;
	} else {
		result = -1;
		return result;
	}
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_;
	glong _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_;
	glong _tmp8_;
	glong _tmp14_;
	glong _tmp17_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	gchar* _tmp22_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		glong _tmp3_;
		glong _tmp4_;
		glong _tmp5_;
		_tmp3_ = offset;
		_tmp4_ = len;
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
		string_length = _tmp5_;
	} else {
		gint _tmp6_;
		gint _tmp7_;
		_tmp6_ = strlen (self);
		_tmp7_ = _tmp6_;
		string_length = (glong) _tmp7_;
	}
	_tmp8_ = offset;
	if (_tmp8_ < ((glong) 0)) {
		glong _tmp9_;
		glong _tmp10_;
		glong _tmp11_;
		_tmp9_ = string_length;
		_tmp10_ = offset;
		offset = _tmp9_ + _tmp10_;
		_tmp11_ = offset;
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
	} else {
		glong _tmp12_;
		glong _tmp13_;
		_tmp12_ = offset;
		_tmp13_ = string_length;
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
	}
	_tmp14_ = len;
	if (_tmp14_ < ((glong) 0)) {
		glong _tmp15_;
		glong _tmp16_;
		_tmp15_ = string_length;
		_tmp16_ = offset;
		len = _tmp15_ - _tmp16_;
	}
	_tmp17_ = offset;
	_tmp18_ = len;
	_tmp19_ = string_length;
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
	_tmp20_ = offset;
	_tmp21_ = len;
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
	result = _tmp22_;
	return result;
}


sdxFiles* sdx_files_construct (GType object_type, const gchar* resourcePath) {
	sdxFiles * self = NULL;
	const gchar* _tmp0_;
	gint _tmp1_;
	g_return_val_if_fail (resourcePath != NULL, NULL);
	self = (sdxFiles*) g_object_new (object_type, NULL);
	_tmp0_ = resourcePath;
	_tmp1_ = string_index_of (_tmp0_, "resource:///", 0);
	if (_tmp1_ == 0) {
		const gchar* _tmp2_;
		gchar* _tmp3_;
		self->priv->_isResource = TRUE;
		_tmp2_ = resourcePath;
		_tmp3_ = string_substring (_tmp2_, (glong) 11, (glong) -1);
		_g_free0 (self->priv->_resourcePath);
		self->priv->_resourcePath = _tmp3_;
	} else {
		const gchar* _tmp4_;
		gchar* _tmp5_;
		_tmp4_ = resourcePath;
		_tmp5_ = g_strdup (_tmp4_);
		_g_free0 (self->priv->_resourcePath);
		self->priv->_resourcePath = _tmp5_;
	}
	return self;
}


sdxFiles* sdx_files_new (const gchar* resourcePath) {
	return sdx_files_construct (SDX_TYPE_FILES, resourcePath);
}


sdxfilesFileHandle* sdx_files_getHandle (sdxFiles* self, const gchar* path, sdxFileType type) {
	sdxfilesFileHandle* result = NULL;
	const gchar* _tmp0_;
	sdxFileType _tmp1_;
	sdxfilesFileHandle* _tmp2_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = type;
	_tmp2_ = sdx_files_file_handle_new (_tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


sdxfilesFileHandle* sdx_files_internal (sdxFiles* self, const gchar* path) {
	sdxfilesFileHandle* result = NULL;
	const gchar* _tmp0_;
	sdxfilesFileHandle* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_files_file_handle_new (_tmp0_, SDX_FILE_TYPE_Internal);
	result = _tmp1_;
	return result;
}


sdxfilesFileHandle* sdx_files_resource (sdxFiles* self, const gchar* path) {
	sdxfilesFileHandle* result = NULL;
	const gchar* _tmp0_;
	sdxfilesFileHandle* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_files_file_handle_new (_tmp0_, SDX_FILE_TYPE_Resource);
	result = _tmp1_;
	return result;
}


sdxfilesFileHandle* sdx_files_external (sdxFiles* self, const gchar* path) {
	sdxfilesFileHandle* result = NULL;
	const gchar* _tmp0_;
	sdxfilesFileHandle* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_files_file_handle_new (_tmp0_, SDX_FILE_TYPE_External);
	result = _tmp1_;
	return result;
}


sdxfilesFileHandle* sdx_files_absolute (sdxFiles* self, const gchar* path) {
	sdxfilesFileHandle* result = NULL;
	const gchar* _tmp0_;
	sdxfilesFileHandle* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_files_file_handle_new (_tmp0_, SDX_FILE_TYPE_Absolute);
	result = _tmp1_;
	return result;
}


sdxfilesFileHandle* sdx_files_local (sdxFiles* self, const gchar* path) {
	sdxfilesFileHandle* result = NULL;
	const gchar* _tmp0_;
	sdxfilesFileHandle* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_files_file_handle_new (_tmp0_, SDX_FILE_TYPE_Local);
	result = _tmp1_;
	return result;
}


gboolean sdx_files_get_isResource (sdxFiles* self) {
	gboolean result;
	gboolean _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_isResource;
	result = _tmp0_;
	return result;
}


const gchar* sdx_files_get_resourcePath (sdxFiles* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_resourcePath;
	result = _tmp0_;
	return result;
}


static void sdx_files_class_init (sdxFilesClass * klass) {
	sdx_files_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (sdxFilesPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_sdx_files_get_property;
	G_OBJECT_CLASS (klass)->finalize = sdx_files_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_FILES_IS_RESOURCE, g_param_spec_boolean ("isResource", "isResource", "isResource", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_FILES_RESOURCE_PATH, g_param_spec_string ("resourcePath", "resourcePath", "resourcePath", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void sdx_files_instance_init (sdxFiles * self) {
	self->priv = SDX_FILES_GET_PRIVATE (self);
}


static void sdx_files_finalize (GObject * obj) {
	sdxFiles * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SDX_TYPE_FILES, sdxFiles);
	_g_free0 (self->priv->_resourcePath);
	G_OBJECT_CLASS (sdx_files_parent_class)->finalize (obj);
}


GType sdx_files_get_type (void) {
	static volatile gsize sdx_files_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_files_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (sdxFilesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sdx_files_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (sdxFiles), 0, (GInstanceInitFunc) sdx_files_instance_init, NULL };
		GType sdx_files_type_id;
		sdx_files_type_id = g_type_register_static (G_TYPE_OBJECT, "sdxFiles", &g_define_type_info, 0);
		g_once_init_leave (&sdx_files_type_id__volatile, sdx_files_type_id);
	}
	return sdx_files_type_id__volatile;
}


static void _vala_sdx_files_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	sdxFiles * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SDX_TYPE_FILES, sdxFiles);
	switch (property_id) {
		case SDX_FILES_IS_RESOURCE:
		g_value_set_boolean (value, sdx_files_get_isResource (self));
		break;
		case SDX_FILES_RESOURCE_PATH:
		g_value_set_string (value, sdx_files_get_resourcePath (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



