/* JsFactory.c generated by valac 0.34.7, the Vala compiler
 * generated from JsFactory.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define SDX_TYPE_JS_GAME (sdx_js_game_get_type ())
#define SDX_JS_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_JS_GAME, sdxJsGame))
#define SDX_JS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_TYPE_JS_GAME, sdxJsGameClass))
#define SDX_IS_JS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_JS_GAME))
#define SDX_IS_JS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_TYPE_JS_GAME))
#define SDX_JS_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_TYPE_JS_GAME, sdxJsGameClass))

typedef struct _sdxJsGame sdxJsGame;
typedef struct _sdxJsGameClass sdxJsGameClass;

#define SDX_GRAPHICS_S2D_TYPE_SPRITE (sdx_graphics_s2d_sprite_get_type ())
#define SDX_GRAPHICS_S2D_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_S2D_TYPE_SPRITE, sdxgraphicss2dSprite))
#define SDX_GRAPHICS_S2D_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_S2D_TYPE_SPRITE, sdxgraphicss2dSpriteClass))
#define SDX_GRAPHICS_S2D_IS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_S2D_TYPE_SPRITE))
#define SDX_GRAPHICS_S2D_IS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_S2D_TYPE_SPRITE))
#define SDX_GRAPHICS_S2D_SPRITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_S2D_TYPE_SPRITE, sdxgraphicss2dSpriteClass))

typedef struct _sdxgraphicss2dSprite sdxgraphicss2dSprite;
typedef struct _sdxgraphicss2dSpriteClass sdxgraphicss2dSpriteClass;

#define SDX_TYPE_AUDIO (sdx_audio_get_type ())
#define SDX_AUDIO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_AUDIO, sdxAudio))
#define SDX_AUDIO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_TYPE_AUDIO, sdxAudioClass))
#define SDX_IS_AUDIO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_AUDIO))
#define SDX_IS_AUDIO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_TYPE_AUDIO))
#define SDX_AUDIO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_TYPE_AUDIO, sdxAudioClass))

typedef struct _sdxAudio sdxAudio;
typedef struct _sdxAudioClass sdxAudioClass;

#define SDX_FILES_TYPE_FILE_HANDLE (sdx_files_file_handle_get_type ())
#define SDX_FILES_FILE_HANDLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_FILES_TYPE_FILE_HANDLE, sdxfilesFileHandle))
#define SDX_FILES_FILE_HANDLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_FILES_TYPE_FILE_HANDLE, sdxfilesFileHandleClass))
#define SDX_FILES_IS_FILE_HANDLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_FILES_TYPE_FILE_HANDLE))
#define SDX_FILES_IS_FILE_HANDLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_FILES_TYPE_FILE_HANDLE))
#define SDX_FILES_FILE_HANDLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_FILES_TYPE_FILE_HANDLE, sdxfilesFileHandleClass))

typedef struct _sdxfilesFileHandle sdxfilesFileHandle;
typedef struct _sdxfilesFileHandleClass sdxfilesFileHandleClass;

#define SDX_AUDIO_TYPE_SOUND (sdx_audio_sound_get_type ())
#define SDX_AUDIO_SOUND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_AUDIO_TYPE_SOUND, sdxaudioSound))
#define SDX_AUDIO_SOUND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_AUDIO_TYPE_SOUND, sdxaudioSoundClass))
#define SDX_AUDIO_IS_SOUND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_AUDIO_TYPE_SOUND))
#define SDX_AUDIO_IS_SOUND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_AUDIO_TYPE_SOUND))
#define SDX_AUDIO_SOUND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_AUDIO_TYPE_SOUND, sdxaudioSoundClass))

typedef struct _sdxaudioSound sdxaudioSound;
typedef struct _sdxaudioSoundClass sdxaudioSoundClass;

#define SDX_TYPE_FILES (sdx_files_get_type ())
#define SDX_FILES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_FILES, sdxFiles))
#define SDX_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_TYPE_FILES, sdxFilesClass))
#define SDX_IS_FILES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_FILES))
#define SDX_IS_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_TYPE_FILES))
#define SDX_FILES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_TYPE_FILES, sdxFilesClass))

typedef struct _sdxFiles sdxFiles;
typedef struct _sdxFilesClass sdxFilesClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define SDX_GRAPHICS_S2D_TYPE_FONT (sdx_graphics_s2d_font_get_type ())
#define SDX_GRAPHICS_S2D_FONT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_S2D_TYPE_FONT, sdxgraphicss2dFont))
#define SDX_GRAPHICS_S2D_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_S2D_TYPE_FONT, sdxgraphicss2dFontClass))
#define SDX_GRAPHICS_S2D_IS_FONT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_S2D_TYPE_FONT))
#define SDX_GRAPHICS_S2D_IS_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_S2D_TYPE_FONT))
#define SDX_GRAPHICS_S2D_FONT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_S2D_TYPE_FONT, sdxgraphicss2dFontClass))

typedef struct _sdxgraphicss2dFont sdxgraphicss2dFont;
typedef struct _sdxgraphicss2dFontClass sdxgraphicss2dFontClass;

#define SDX_GRAPHICS_TYPE_COLOR (sdx_graphics_color_get_type ())
#define SDX_GRAPHICS_COLOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_TYPE_COLOR, sdxgraphicsColor))
#define SDX_GRAPHICS_COLOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_TYPE_COLOR, sdxgraphicsColorClass))
#define SDX_GRAPHICS_IS_COLOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_TYPE_COLOR))
#define SDX_GRAPHICS_IS_COLOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_TYPE_COLOR))
#define SDX_GRAPHICS_COLOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_TYPE_COLOR, sdxgraphicsColorClass))

typedef struct _sdxgraphicsColor sdxgraphicsColor;
typedef struct _sdxgraphicsColorClass sdxgraphicsColorClass;

#define SDX_GRAPHICS_S2D_TYPE_TEXTURE_ATLAS (sdx_graphics_s2d_texture_atlas_get_type ())
#define SDX_GRAPHICS_S2D_TEXTURE_ATLAS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_S2D_TYPE_TEXTURE_ATLAS, sdxgraphicss2dTextureAtlas))
#define SDX_GRAPHICS_S2D_TEXTURE_ATLAS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_S2D_TYPE_TEXTURE_ATLAS, sdxgraphicss2dTextureAtlasClass))
#define SDX_GRAPHICS_S2D_IS_TEXTURE_ATLAS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_S2D_TYPE_TEXTURE_ATLAS))
#define SDX_GRAPHICS_S2D_IS_TEXTURE_ATLAS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_S2D_TYPE_TEXTURE_ATLAS))
#define SDX_GRAPHICS_S2D_TEXTURE_ATLAS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_S2D_TYPE_TEXTURE_ATLAS, sdxgraphicss2dTextureAtlasClass))

typedef struct _sdxgraphicss2dTextureAtlas sdxgraphicss2dTextureAtlas;
typedef struct _sdxgraphicss2dTextureAtlasClass sdxgraphicss2dTextureAtlasClass;



GObject* sdx_createJsGame (const gchar* name, gint height, gint width, const gchar* base);
sdxJsGame* sdx_js_game_new (const gchar* name, gint height, gint width, const gchar* base);
sdxJsGame* sdx_js_game_construct (GType object_type, const gchar* name, gint height, gint width, const gchar* base);
GType sdx_js_game_get_type (void) G_GNUC_CONST;
GObject* sdx_createSprite (const gchar* path);
sdxgraphicss2dSprite* sdx_graphics_s2d_sprite_new (const gchar* path);
sdxgraphicss2dSprite* sdx_graphics_s2d_sprite_construct (GType object_type, const gchar* path);
GType sdx_graphics_s2d_sprite_get_type (void) G_GNUC_CONST;
GObject* sdx_createSound (const gchar* path);
GType sdx_audio_get_type (void) G_GNUC_CONST;
sdxAudio* sdx_sdx_get_audio (void);
GType sdx_files_file_handle_get_type (void) G_GNUC_CONST;
GType sdx_audio_sound_get_type (void) G_GNUC_CONST;
sdxaudioSound* sdx_audio_newSound (sdxAudio* self, sdxfilesFileHandle* file);
GType sdx_files_get_type (void) G_GNUC_CONST;
sdxFiles* sdx_sdx_get_files (void);
sdxfilesFileHandle* sdx_files_resource (sdxFiles* self, const gchar* path);
GObject* sdx_createFont (const gchar* path, gint size);
sdxgraphicss2dFont* sdx_graphics_s2d_font_new (sdxfilesFileHandle* file, gint size);
sdxgraphicss2dFont* sdx_graphics_s2d_font_construct (GType object_type, sdxfilesFileHandle* file, gint size);
GType sdx_graphics_s2d_font_get_type (void) G_GNUC_CONST;
GObject* sdx_createText (const gchar* text, GObject* font, GObject* color);
GType sdx_graphics_color_get_type (void) G_GNUC_CONST;
sdxgraphicss2dSprite* sdx_graphics_s2d_sprite_new_text (const gchar* text, sdxgraphicss2dFont* font, sdxgraphicsColor* color);
sdxgraphicss2dSprite* sdx_graphics_s2d_sprite_construct_text (GType object_type, const gchar* text, sdxgraphicss2dFont* font, sdxgraphicsColor* color);
GObject* sdx_createColor (gdouble r, gdouble g, gdouble b, gdouble a);
sdxgraphicsColor* sdx_graphics_color_new_rgba (gdouble r, gdouble g, gdouble b, gdouble a);
sdxgraphicsColor* sdx_graphics_color_construct_rgba (GType object_type, gdouble r, gdouble g, gdouble b, gdouble a);
GObject* sdx_createAtlas (const gchar* path);
gboolean sdx_files_file_handle_exists (sdxfilesFileHandle* self);
sdxgraphicss2dTextureAtlas* sdx_graphics_s2d_texture_atlas_new_file (sdxfilesFileHandle* packFile, sdxfilesFileHandle* imageDir, gboolean flip);
sdxgraphicss2dTextureAtlas* sdx_graphics_s2d_texture_atlas_construct_file (GType object_type, sdxfilesFileHandle* packFile, sdxfilesFileHandle* imageDir, gboolean flip);
GType sdx_graphics_s2d_texture_atlas_get_type (void) G_GNUC_CONST;


/**
     * createGame
     *
     * @param name for title bar
     * @param height in pixels
     * @param width in pixels
     * @param base asset url
     * @return the new game
     */
GObject* sdx_createJsGame (const gchar* name, gint height, gint width, const gchar* base) {
	GObject* result = NULL;
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	const gchar* _tmp3_ = NULL;
	sdxJsGame* _tmp4_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (base != NULL, NULL);
	_tmp0_ = name;
	_tmp1_ = height;
	_tmp2_ = width;
	_tmp3_ = base;
	_tmp4_ = sdx_js_game_new (_tmp0_, _tmp1_, _tmp2_, _tmp3_);
	result = G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, G_TYPE_OBJECT, GObject);
	return result;
}


/**
     * createSprite
     *
     * @param path to asset
     * @return the new sprite
     */
GObject* sdx_createSprite (const gchar* path) {
	GObject* result = NULL;
	const gchar* _tmp0_ = NULL;
	sdxgraphicss2dSprite* _tmp1_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_graphics_s2d_sprite_new (_tmp0_);
	result = G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, G_TYPE_OBJECT, GObject);
	return result;
}


/**
     * createSound
     *
     * @param path to asset
     * @return the new sound chunk
     */
GObject* sdx_createSound (const gchar* path) {
	GObject* result = NULL;
	sdxAudio* _tmp0_ = NULL;
	sdxAudio* _tmp1_ = NULL;
	sdxFiles* _tmp2_ = NULL;
	sdxFiles* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	sdxfilesFileHandle* _tmp5_ = NULL;
	sdxfilesFileHandle* _tmp6_ = NULL;
	sdxaudioSound* _tmp7_ = NULL;
	GObject* _tmp8_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = sdx_sdx_get_audio ();
	_tmp1_ = _tmp0_;
	_tmp2_ = sdx_sdx_get_files ();
	_tmp3_ = _tmp2_;
	_tmp4_ = path;
	_tmp5_ = sdx_files_resource (_tmp3_, _tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = sdx_audio_newSound (_tmp1_, _tmp6_);
	_tmp8_ = G_TYPE_CHECK_INSTANCE_CAST (_tmp7_, G_TYPE_OBJECT, GObject);
	_g_object_unref0 (_tmp6_);
	result = _tmp8_;
	return result;
}


/**
     * createFont
     *
     * @param path to asset
     * @param size
     * @return the new font
     */
GObject* sdx_createFont (const gchar* path, gint size) {
	GObject* result = NULL;
	sdxFiles* _tmp0_ = NULL;
	sdxFiles* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	sdxfilesFileHandle* _tmp3_ = NULL;
	sdxfilesFileHandle* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	sdxgraphicss2dFont* _tmp6_ = NULL;
	GObject* _tmp7_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = sdx_sdx_get_files ();
	_tmp1_ = _tmp0_;
	_tmp2_ = path;
	_tmp3_ = sdx_files_resource (_tmp1_, _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = size;
	_tmp6_ = sdx_graphics_s2d_font_new (_tmp4_, _tmp5_);
	_tmp7_ = G_TYPE_CHECK_INSTANCE_CAST (_tmp6_, G_TYPE_OBJECT, GObject);
	_g_object_unref0 (_tmp4_);
	result = _tmp7_;
	return result;
}


/**
     * createText
     *
     * @param text
     * @param font
     * @param color
     * @return the new text sprite
     */
GObject* sdx_createText (const gchar* text, GObject* font, GObject* color) {
	GObject* result = NULL;
	const gchar* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	sdxgraphicss2dSprite* _tmp3_ = NULL;
	g_return_val_if_fail (text != NULL, NULL);
	g_return_val_if_fail (font != NULL, NULL);
	g_return_val_if_fail (color != NULL, NULL);
	_tmp0_ = text;
	_tmp1_ = font;
	_tmp2_ = color;
	_tmp3_ = sdx_graphics_s2d_sprite_new_text (_tmp0_, G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, SDX_GRAPHICS_S2D_TYPE_FONT, sdxgraphicss2dFont), G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, SDX_GRAPHICS_TYPE_COLOR, sdxgraphicsColor));
	result = G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, G_TYPE_OBJECT, GObject);
	return result;
}


/**
     * createColor
     *
     * @param r
     * @param g
     * @param b
     * @param a
     * @return the new color
     */
GObject* sdx_createColor (gdouble r, gdouble g, gdouble b, gdouble a) {
	GObject* result = NULL;
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	sdxgraphicsColor* _tmp4_ = NULL;
	_tmp0_ = r;
	_tmp1_ = g;
	_tmp2_ = b;
	_tmp3_ = a;
	_tmp4_ = sdx_graphics_color_new_rgba (_tmp0_, _tmp1_, _tmp2_, _tmp3_);
	result = G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, G_TYPE_OBJECT, GObject);
	return result;
}


GObject* sdx_createAtlas (const gchar* path) {
	GObject* result = NULL;
	sdxfilesFileHandle* file = NULL;
	sdxFiles* _tmp0_ = NULL;
	sdxFiles* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	sdxfilesFileHandle* _tmp3_ = NULL;
	sdxfilesFileHandle* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
	sdxfilesFileHandle* _tmp6_ = NULL;
	sdxgraphicss2dTextureAtlas* _tmp7_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = sdx_sdx_get_files ();
	_tmp1_ = _tmp0_;
	_tmp2_ = path;
	_tmp3_ = sdx_files_resource (_tmp1_, _tmp2_);
	file = _tmp3_;
	_tmp4_ = file;
	_tmp5_ = sdx_files_file_handle_exists (_tmp4_);
	if (!_tmp5_) {
		result = NULL;
		_g_object_unref0 (file);
		return result;
	}
	_tmp6_ = file;
	_tmp7_ = sdx_graphics_s2d_texture_atlas_new_file (_tmp6_, NULL, FALSE);
	result = (GObject*) _tmp7_;
	_g_object_unref0 (file);
	return result;
}



