/* JsGame.c generated by valac 0.34.9, the Vala compiler
 * generated from JsGame.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL2/SDL_render.h>
#include <SDL2/SDL_video.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <SDL2/SDL_events.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_hints.h>
#include <SDL2/SDL_ttf.h>
#include <SDL2/SDL_mixer.h>
#include <SDL2/SDL_audio.h>
#include <SDL2/SDL_keyboard.h>
#include <SDL2/SDL_rect.h>


#define SDX_TYPE_IAPPLICATION (sdx_iapplication_get_type ())
#define SDX_IAPPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_IAPPLICATION, sdxIApplication))
#define SDX_IS_IAPPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_IAPPLICATION))
#define SDX_IAPPLICATION_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SDX_TYPE_IAPPLICATION, sdxIApplicationIface))

typedef struct _sdxIApplication sdxIApplication;
typedef struct _sdxIApplicationIface sdxIApplicationIface;

#define SDX_TYPE_JS_GAME (sdx_js_game_get_type ())
#define SDX_JS_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_JS_GAME, sdxJsGame))
#define SDX_JS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_TYPE_JS_GAME, sdxJsGameClass))
#define SDX_IS_JS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_JS_GAME))
#define SDX_IS_JS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_TYPE_JS_GAME))
#define SDX_JS_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_TYPE_JS_GAME, sdxJsGameClass))

typedef struct _sdxJsGame sdxJsGame;
typedef struct _sdxJsGameClass sdxJsGameClass;
typedef struct _sdxJsGamePrivate sdxJsGamePrivate;

#define SDX_GRAPHICS_S2D_TYPE_SPRITE (sdx_graphics_s2d_sprite_get_type ())
#define SDX_GRAPHICS_S2D_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_S2D_TYPE_SPRITE, sdxgraphicss2dSprite))
#define SDX_GRAPHICS_S2D_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_S2D_TYPE_SPRITE, sdxgraphicss2dSpriteClass))
#define SDX_GRAPHICS_S2D_IS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_S2D_TYPE_SPRITE))
#define SDX_GRAPHICS_S2D_IS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_S2D_TYPE_SPRITE))
#define SDX_GRAPHICS_S2D_SPRITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_S2D_TYPE_SPRITE, sdxgraphicss2dSpriteClass))

typedef struct _sdxgraphicss2dSprite sdxgraphicss2dSprite;
typedef struct _sdxgraphicss2dSpriteClass sdxgraphicss2dSpriteClass;

#define SDX_GRAPHICS_S2D_TYPE_FONT (sdx_graphics_s2d_font_get_type ())
#define SDX_GRAPHICS_S2D_FONT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_S2D_TYPE_FONT, sdxgraphicss2dFont))
#define SDX_GRAPHICS_S2D_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_S2D_TYPE_FONT, sdxgraphicss2dFontClass))
#define SDX_GRAPHICS_S2D_IS_FONT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_S2D_TYPE_FONT))
#define SDX_GRAPHICS_S2D_IS_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_S2D_TYPE_FONT))
#define SDX_GRAPHICS_S2D_FONT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_S2D_TYPE_FONT, sdxgraphicss2dFontClass))

typedef struct _sdxgraphicss2dFont sdxgraphicss2dFont;
typedef struct _sdxgraphicss2dFontClass sdxgraphicss2dFontClass;

#define SDX_TYPE_APPLICATION_LISTENER (sdx_application_listener_get_type ())
#define SDX_APPLICATION_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_APPLICATION_LISTENER, sdxApplicationListener))
#define SDX_IS_APPLICATION_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_APPLICATION_LISTENER))
#define SDX_APPLICATION_LISTENER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SDX_TYPE_APPLICATION_LISTENER, sdxApplicationListenerIface))

typedef struct _sdxApplicationListener sdxApplicationListener;
typedef struct _sdxApplicationListenerIface sdxApplicationListenerIface;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _SDL_DestroyWindow0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyWindow (var), NULL)))
#define _SDL_DestroyRenderer0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyRenderer (var), NULL)))

#define SDX_TYPE_SDX (sdx_sdx_get_type ())
#define SDX_SDX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_SDX, sdxSdx))
#define SDX_SDX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_TYPE_SDX, sdxSdxClass))
#define SDX_IS_SDX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_SDX))
#define SDX_IS_SDX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_TYPE_SDX))
#define SDX_SDX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_TYPE_SDX, sdxSdxClass))

typedef struct _sdxSdx sdxSdx;
typedef struct _sdxSdxClass sdxSdxClass;

#define SDX_FILES_TYPE_FILE_HANDLE (sdx_files_file_handle_get_type ())
#define SDX_FILES_FILE_HANDLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_FILES_TYPE_FILE_HANDLE, sdxfilesFileHandle))
#define SDX_FILES_FILE_HANDLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_FILES_TYPE_FILE_HANDLE, sdxfilesFileHandleClass))
#define SDX_FILES_IS_FILE_HANDLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_FILES_TYPE_FILE_HANDLE))
#define SDX_FILES_IS_FILE_HANDLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_FILES_TYPE_FILE_HANDLE))
#define SDX_FILES_FILE_HANDLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_FILES_TYPE_FILE_HANDLE, sdxfilesFileHandleClass))

typedef struct _sdxfilesFileHandle sdxfilesFileHandle;
typedef struct _sdxfilesFileHandleClass sdxfilesFileHandleClass;

#define SDX_TYPE_FILES (sdx_files_get_type ())
#define SDX_FILES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_FILES, sdxFiles))
#define SDX_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_TYPE_FILES, sdxFilesClass))
#define SDX_IS_FILES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_FILES))
#define SDX_IS_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_TYPE_FILES))
#define SDX_FILES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_TYPE_FILES, sdxFilesClass))

typedef struct _sdxFiles sdxFiles;
typedef struct _sdxFilesClass sdxFilesClass;

#define SDX_TYPE_GRAPHICS (sdx_graphics_get_type ())
#define SDX_GRAPHICS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_GRAPHICS, sdxGraphics))
#define SDX_GRAPHICS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_TYPE_GRAPHICS, sdxGraphicsClass))
#define SDX_IS_GRAPHICS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_GRAPHICS))
#define SDX_IS_GRAPHICS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_TYPE_GRAPHICS))
#define SDX_GRAPHICS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_TYPE_GRAPHICS, sdxGraphicsClass))

typedef struct _sdxGraphics sdxGraphics;
typedef struct _sdxGraphicsClass sdxGraphicsClass;

#define SDX_GRAPHICS_TYPE_COLOR (sdx_graphics_color_get_type ())
#define SDX_GRAPHICS_COLOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_TYPE_COLOR, sdxgraphicsColor))
#define SDX_GRAPHICS_COLOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_TYPE_COLOR, sdxgraphicsColorClass))
#define SDX_GRAPHICS_IS_COLOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_TYPE_COLOR))
#define SDX_GRAPHICS_IS_COLOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_TYPE_COLOR))
#define SDX_GRAPHICS_COLOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_TYPE_COLOR, sdxgraphicsColorClass))

typedef struct _sdxgraphicsColor sdxgraphicsColor;
typedef struct _sdxgraphicsColorClass sdxgraphicsColorClass;

struct _sdxIApplicationIface {
	GTypeInterface parent_iface;
	gint (*get_width) (sdxIApplication* self);
	void (*set_width) (sdxIApplication* self, gint value);
	gint (*get_height) (sdxIApplication* self);
	void (*set_height) (sdxIApplication* self, gint value);
	SDL_Renderer* (*get_renderer) (sdxIApplication* self);
};

struct _sdxJsGame {
	GObject parent_instance;
	sdxJsGamePrivate * priv;
	SDL_Window* window;
	guint8* keys;
	gint keys_length1;
	gint frames;
	gdouble scale;
	gdouble pixelFactor;
	gchar* defaultFont;
	GeeArrayList* sprites;
	GeeArrayList* onetime;
	gint k;
	gdouble t;
	gdouble t1;
	gdouble t2;
	gdouble t3;
};

struct _sdxJsGameClass {
	GObjectClass parent_class;
};

struct _sdxApplicationListenerIface {
	GTypeInterface parent_iface;
	void (*create) (sdxApplicationListener* self);
	void (*resize) (sdxApplicationListener* self, gint width, gint height);
	void (*render) (sdxApplicationListener* self);
	void (*pause) (sdxApplicationListener* self);
	void (*resume) (sdxApplicationListener* self);
	void (*dispose) (sdxApplicationListener* self);
};

struct _sdxJsGamePrivate {
	gint _yieldForEventsMs;
	gboolean _profile;
	gboolean _mouseDown;
	gint _mouseX;
	gint _mouseY;
	gboolean _running;
	gchar* _name;
	gchar* _base;
	gint _fps;
	gboolean _showFps;
	gdouble _deltaTime;
	gint _width;
	gint _height;
	sdxgraphicss2dFont* _font;
	SDL_Renderer* _renderer;
	SDL_Event evt;
	sdxgraphicss2dSprite* fpsSprite;
	sdxApplicationListener* app;
	gdouble lastTime;
	gdouble currentTime;
	gdouble elapsed;
};


static gpointer sdx_js_game_parent_class = NULL;
static sdxIApplicationIface* sdx_js_game_sdx_iapplication_parent_iface = NULL;

GType sdx_iapplication_get_type (void) G_GNUC_CONST;
GType sdx_js_game_get_type (void) G_GNUC_CONST;
GType sdx_graphics_s2d_sprite_get_type (void) G_GNUC_CONST;
GType sdx_graphics_s2d_font_get_type (void) G_GNUC_CONST;
GType sdx_application_listener_get_type (void) G_GNUC_CONST;
#define SDX_JS_GAME_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SDX_TYPE_JS_GAME, sdxJsGamePrivate))
enum  {
	SDX_JS_GAME_DUMMY_PROPERTY,
	SDX_JS_GAME_YIELD_FOR_EVENTS_MS,
	SDX_JS_GAME_PROFILE,
	SDX_JS_GAME_MOUSE_DOWN,
	SDX_JS_GAME_MOUSE_X,
	SDX_JS_GAME_MOUSE_Y,
	SDX_JS_GAME_RUNNING,
	SDX_JS_GAME_NAME,
	SDX_JS_GAME_BASE,
	SDX_JS_GAME_FPS,
	SDX_JS_GAME_SHOW_FPS,
	SDX_JS_GAME_DELTA_TIME,
	SDX_JS_GAME_WIDTH,
	SDX_JS_GAME_HEIGHT,
	SDX_JS_GAME_FONT,
	SDX_JS_GAME_RENDERER
};
sdxJsGame* sdx_js_game_new (const gchar* name, gint height, gint width, const gchar* base);
sdxJsGame* sdx_js_game_construct (GType object_type, const gchar* name, gint height, gint width, const gchar* base);
sdxSdx* sdx_sdx_new (sdxIApplication* app, gint width, gint height, const gchar* base);
sdxSdx* sdx_sdx_construct (GType object_type, sdxIApplication* app, gint width, gint height, const gchar* base);
GType sdx_sdx_get_type (void) G_GNUC_CONST;
void sdx_js_game_set_name (sdxJsGame* self, const gchar* value);
void sdx_iapplication_set_width (sdxIApplication* self, gint value);
void sdx_iapplication_set_height (sdxIApplication* self, gint value);
void sdx_js_game_set_base (sdxJsGame* self, const gchar* value);
void sdx_js_game_initialize (sdxJsGame* self);
void sdx_js_game_addSprite (sdxJsGame* self, GObject* sprite);
gint sdx_graphics_s2d_sprite_get_layer (sdxgraphicss2dSprite* self);
void sdx_js_game_addOnce (sdxJsGame* self, GObject* sprite);
void sdx_js_game_removeSprite (sdxJsGame* self, GObject* sprite);
void sdx_js_game_setApplicationListener (sdxJsGame* self, sdxApplicationListener* listener);
void sdx_sdlFailIf (gboolean cond, const gchar* reason);
const gchar* sdx_js_game_get_name (sdxJsGame* self);
gint sdx_iapplication_get_width (sdxIApplication* self);
gint sdx_iapplication_get_height (sdxIApplication* self);
GType sdx_files_file_handle_get_type (void) G_GNUC_CONST;
GType sdx_files_get_type (void) G_GNUC_CONST;
sdxFiles* sdx_sdx_get_files (void);
sdxfilesFileHandle* sdx_files_resource (sdxFiles* self, const gchar* path);
sdxgraphicss2dFont* sdx_graphics_s2d_font_new (sdxfilesFileHandle* file, gint size);
sdxgraphicss2dFont* sdx_graphics_s2d_font_construct (GType object_type, sdxfilesFileHandle* file, gint size);
void sdx_js_game_set_font (sdxJsGame* self, sdxgraphicss2dFont* value);
sdxgraphicss2dFont* sdx_js_game_get_font (sdxJsGame* self);
void sdx_js_game_set_showFps (sdxJsGame* self, gboolean value);
void sdx_js_game_start (sdxJsGame* self);
void sdx_js_game_set_running (sdxJsGame* self, gboolean value);
gint sdx_js_game_getKey (sdxJsGame* self, gint code);
gint sdx_js_game_handleEvents (sdxJsGame* self);
GType sdx_graphics_get_type (void) G_GNUC_CONST;
sdxGraphics* sdx_sdx_get_graphics (void);
void sdx_graphics_updateTime (sdxGraphics* self);
gdouble sdx_graphics_get_deltaTime (sdxGraphics* self);
gint sdx_graphics_get_fps (sdxGraphics* self);
gboolean sdx_js_game_get_profile (sdxJsGame* self);
void sdx_js_game_draw (sdxJsGame* self);
SDL_Renderer* sdx_iapplication_get_renderer (sdxIApplication* self);
void sdx_graphics_s2d_sprite_render (sdxgraphicss2dSprite* self, SDL_Renderer* renderer, gint x, gint y, SDL_Rect* clip);
gint sdx_graphics_s2d_sprite_get_x (sdxgraphicss2dSprite* self);
gint sdx_graphics_s2d_sprite_get_y (sdxgraphicss2dSprite* self);
gboolean sdx_js_game_get_showFps (sdxJsGame* self);
gint sdx_js_game_get_yieldForEventsMs (sdxJsGame* self);
GType sdx_graphics_color_get_type (void) G_GNUC_CONST;
sdxgraphicsColor* sdx_graphics_color_get_AntiqueWhite (void);
sdxgraphicss2dSprite* sdx_graphics_s2d_sprite_new_text (const gchar* text, sdxgraphicss2dFont* font, sdxgraphicsColor* color);
sdxgraphicss2dSprite* sdx_graphics_s2d_sprite_construct_text (GType object_type, const gchar* text, sdxgraphicss2dFont* font, sdxgraphicsColor* color);
void sdx_graphics_s2d_sprite_set_centered (sdxgraphicss2dSprite* self, gboolean value);
void sdx_js_game_set_yieldForEventsMs (sdxJsGame* self, gint value);
void sdx_js_game_set_profile (sdxJsGame* self, gboolean value);
gboolean sdx_js_game_get_mouseDown (sdxJsGame* self);
void sdx_js_game_set_mouseDown (sdxJsGame* self, gboolean value);
gint sdx_js_game_get_mouseX (sdxJsGame* self);
void sdx_js_game_set_mouseX (sdxJsGame* self, gint value);
gint sdx_js_game_get_mouseY (sdxJsGame* self);
void sdx_js_game_set_mouseY (sdxJsGame* self, gint value);
gboolean sdx_js_game_get_running (sdxJsGame* self);
const gchar* sdx_js_game_get_base (sdxJsGame* self);
gint sdx_js_game_get_fps (sdxJsGame* self);
void sdx_js_game_set_fps (sdxJsGame* self, gint value);
gdouble sdx_js_game_get_deltaTime (sdxJsGame* self);
void sdx_js_game_set_deltaTime (sdxJsGame* self, gdouble value);
static void sdx_js_game_finalize (GObject* obj);
static void _vala_sdx_js_game_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_sdx_js_game_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


sdxJsGame* sdx_js_game_construct (GType object_type, const gchar* name, gint height, gint width, const gchar* base) {
	sdxJsGame * self = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	const gchar* _tmp2_ = NULL;
	sdxSdx* _tmp3_ = NULL;
	sdxSdx* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	const gchar* _tmp8_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (base != NULL, NULL);
	self = (sdxJsGame*) g_object_new (object_type, NULL);
	_tmp0_ = width;
	_tmp1_ = height;
	_tmp2_ = base;
	_tmp3_ = sdx_sdx_new ((sdxIApplication*) self, _tmp0_, _tmp1_, _tmp2_);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp4_);
	_tmp5_ = name;
	sdx_js_game_set_name (self, _tmp5_);
	_tmp6_ = width;
	sdx_iapplication_set_width ((sdxIApplication*) self, _tmp6_);
	_tmp7_ = height;
	sdx_iapplication_set_height ((sdxIApplication*) self, _tmp7_);
	_tmp8_ = base;
	sdx_js_game_set_base (self, _tmp8_);
	sdx_js_game_initialize (self);
	return self;
}


sdxJsGame* sdx_js_game_new (const gchar* name, gint height, gint width, const gchar* base) {
	return sdx_js_game_construct (SDX_TYPE_JS_GAME, name, height, width, base);
}


/**
         * addSprite
         * @param sprite to add
         *
         * Insert a sprite in layer order
         */
static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void sdx_js_game_addSprite (sdxJsGame* self, GObject* sprite) {
	gint ordinal = 0;
	GObject* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	GeeArrayList* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sprite != NULL);
	_tmp0_ = sprite;
	_tmp1_ = sdx_graphics_s2d_sprite_get_layer (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, SDX_GRAPHICS_S2D_TYPE_SPRITE, sdxgraphicss2dSprite));
	_tmp2_ = _tmp1_;
	ordinal = _tmp2_;
	_tmp3_ = self->sprites;
	_tmp4_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp3_);
	_tmp5_ = _tmp4_;
	if (_tmp5_ == 0) {
		GeeArrayList* _tmp6_ = NULL;
		GObject* _tmp7_ = NULL;
		_tmp6_ = self->sprites;
		_tmp7_ = sprite;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp6_, G_TYPE_CHECK_INSTANCE_CAST (_tmp7_, SDX_GRAPHICS_S2D_TYPE_SPRITE, sdxgraphicss2dSprite));
	} else {
		gint i = 0;
		GeeArrayList* _tmp27_ = NULL;
		GObject* _tmp28_ = NULL;
		i = 0;
		{
			GeeArrayList* _s_list = NULL;
			GeeArrayList* _tmp8_ = NULL;
			GeeArrayList* _tmp9_ = NULL;
			gint _s_size = 0;
			GeeArrayList* _tmp10_ = NULL;
			gint _tmp11_ = 0;
			gint _tmp12_ = 0;
			gint _s_index = 0;
			_tmp8_ = self->sprites;
			_tmp9_ = _g_object_ref0 (_tmp8_);
			_s_list = _tmp9_;
			_tmp10_ = _s_list;
			_tmp11_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp10_);
			_tmp12_ = _tmp11_;
			_s_size = _tmp12_;
			_s_index = -1;
			while (TRUE) {
				gint _tmp13_ = 0;
				gint _tmp14_ = 0;
				gint _tmp15_ = 0;
				sdxgraphicss2dSprite* s = NULL;
				GeeArrayList* _tmp16_ = NULL;
				gint _tmp17_ = 0;
				gpointer _tmp18_ = NULL;
				gint _tmp19_ = 0;
				sdxgraphicss2dSprite* _tmp20_ = NULL;
				gint _tmp21_ = 0;
				gint _tmp22_ = 0;
				_tmp13_ = _s_index;
				_s_index = _tmp13_ + 1;
				_tmp14_ = _s_index;
				_tmp15_ = _s_size;
				if (!(_tmp14_ < _tmp15_)) {
					break;
				}
				_tmp16_ = _s_list;
				_tmp17_ = _s_index;
				_tmp18_ = gee_abstract_list_get ((GeeAbstractList*) _tmp16_, _tmp17_);
				s = (sdxgraphicss2dSprite*) _tmp18_;
				_tmp19_ = ordinal;
				_tmp20_ = s;
				_tmp21_ = sdx_graphics_s2d_sprite_get_layer (_tmp20_);
				_tmp22_ = _tmp21_;
				if (_tmp19_ <= _tmp22_) {
					GeeArrayList* _tmp23_ = NULL;
					gint _tmp24_ = 0;
					GObject* _tmp25_ = NULL;
					_tmp23_ = self->sprites;
					_tmp24_ = i;
					_tmp25_ = sprite;
					gee_abstract_list_insert ((GeeAbstractList*) _tmp23_, _tmp24_, G_TYPE_CHECK_INSTANCE_CAST (_tmp25_, SDX_GRAPHICS_S2D_TYPE_SPRITE, sdxgraphicss2dSprite));
					_g_object_unref0 (s);
					_g_object_unref0 (_s_list);
					return;
				} else {
					gint _tmp26_ = 0;
					_tmp26_ = i;
					i = _tmp26_ + 1;
				}
				_g_object_unref0 (s);
			}
			_g_object_unref0 (_s_list);
		}
		_tmp27_ = self->sprites;
		_tmp28_ = sprite;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp27_, G_TYPE_CHECK_INSTANCE_CAST (_tmp28_, SDX_GRAPHICS_S2D_TYPE_SPRITE, sdxgraphicss2dSprite));
	}
}


void sdx_js_game_addOnce (sdxJsGame* self, GObject* sprite) {
	GeeArrayList* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sprite != NULL);
	_tmp0_ = self->onetime;
	_tmp1_ = sprite;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, SDX_GRAPHICS_S2D_TYPE_SPRITE, sdxgraphicss2dSprite));
}


/**
         * removeSprite
         * @param sprite to remove
         */
void sdx_js_game_removeSprite (sdxJsGame* self, GObject* sprite) {
	GeeArrayList* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sprite != NULL);
	_tmp0_ = self->sprites;
	_tmp1_ = sprite;
	gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp0_, G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, SDX_GRAPHICS_S2D_TYPE_SPRITE, sdxgraphicss2dSprite));
}


void sdx_js_game_setApplicationListener (sdxJsGame* self, sdxApplicationListener* listener) {
	sdxApplicationListener* _tmp0_ = NULL;
	sdxApplicationListener* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (listener != NULL);
	_tmp0_ = listener;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->app);
	self->priv->app = _tmp1_;
}


/**
         * initialize SDL
         */
void sdx_js_game_initialize (sdxJsGame* self) {
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gboolean _tmp2_ = FALSE;
	const gchar* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	SDL_Window* _tmp8_ = NULL;
	SDL_Window* _tmp9_ = NULL;
	SDL_Window* _tmp10_ = NULL;
	SDL_Renderer* _tmp11_ = NULL;
	SDL_Renderer* _tmp12_ = NULL;
	SDL_Renderer* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	const gchar* _tmp15_ = NULL;
	gint _tmp29_ = 0;
	guint8* _tmp30_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = SDL_Init ((guint32) ((SDL_INIT_VIDEO | SDL_INIT_TIMER) | SDL_INIT_EVENTS));
	sdx_sdlFailIf (_tmp0_ < 0, "SDL could not initialize! SDL Error: %s");
	_tmp1_ = IMG_Init ((gint) IMG_INIT_PNG);
	sdx_sdlFailIf (_tmp1_ < 0, "SDL_image could not initialize!");
	_tmp2_ = SDL_SetHint (SDL_HINT_RENDER_SCALE_QUALITY, "1");
	sdx_sdlFailIf (!_tmp2_, "Warning: Linear texture filtering not enabled!!");
	_tmp3_ = self->priv->_name;
	_tmp4_ = sdx_iapplication_get_width ((sdxIApplication*) self);
	_tmp5_ = _tmp4_;
	_tmp6_ = sdx_iapplication_get_height ((sdxIApplication*) self);
	_tmp7_ = _tmp6_;
	_tmp8_ = SDL_CreateWindow (_tmp3_, (gint) SDL_WINDOWPOS_CENTERED_MASK, (gint) SDL_WINDOWPOS_CENTERED_MASK, _tmp5_, _tmp7_, (guint32) SDL_WINDOW_SHOWN);
	_SDL_DestroyWindow0 (self->window);
	self->window = _tmp8_;
	_tmp9_ = self->window;
	sdx_sdlFailIf (_tmp9_ == NULL, "Window could not be created!");
	_tmp10_ = self->window;
	_tmp11_ = SDL_CreateRenderer (_tmp10_, -1, (guint32) (SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC));
	_SDL_DestroyRenderer0 (self->priv->_renderer);
	self->priv->_renderer = _tmp11_;
	_tmp12_ = self->priv->_renderer;
	sdx_sdlFailIf (_tmp12_ == NULL, "Renderer could not be created!");
	_tmp13_ = self->priv->_renderer;
	SDL_SetRenderDrawColor (_tmp13_, (guint8) 0xFF, (guint8) 0xFF, (guint8) 0xFF, (guint8) 0);
	_tmp14_ = TTF_Init ();
	sdx_sdlFailIf (_tmp14_ == (-1), "SDL_ttf could not initialize!");
	_tmp15_ = self->defaultFont;
	if (g_strcmp0 (_tmp15_, "") != 0) {
		sdxfilesFileHandle* f = NULL;
		sdxFiles* _tmp16_ = NULL;
		sdxFiles* _tmp17_ = NULL;
		const gchar* _tmp18_ = NULL;
		sdxfilesFileHandle* _tmp19_ = NULL;
		sdxFiles* _tmp20_ = NULL;
		sdxFiles* _tmp21_ = NULL;
		const gchar* _tmp22_ = NULL;
		sdxfilesFileHandle* _tmp23_ = NULL;
		sdxfilesFileHandle* _tmp24_ = NULL;
		sdxgraphicss2dFont* _tmp25_ = NULL;
		sdxgraphicss2dFont* _tmp26_ = NULL;
		sdxgraphicss2dFont* _tmp27_ = NULL;
		_tmp16_ = sdx_sdx_get_files ();
		_tmp17_ = _tmp16_;
		_tmp18_ = self->defaultFont;
		_tmp19_ = sdx_files_resource (_tmp17_, _tmp18_);
		f = _tmp19_;
		_tmp20_ = sdx_sdx_get_files ();
		_tmp21_ = _tmp20_;
		_tmp22_ = self->defaultFont;
		_tmp23_ = sdx_files_resource (_tmp21_, _tmp22_);
		_tmp24_ = _tmp23_;
		_tmp25_ = sdx_graphics_s2d_font_new (_tmp24_, 16);
		_tmp26_ = _tmp25_;
		sdx_js_game_set_font (self, _tmp26_);
		_g_object_unref0 (_tmp26_);
		_g_object_unref0 (_tmp24_);
		_tmp27_ = self->priv->_font;
		if (_tmp27_ == NULL) {
			const gchar* _tmp28_ = NULL;
			sdx_js_game_set_showFps (self, FALSE);
			_tmp28_ = SDL_GetError ();
			g_print ("Failed to load font, show_fps set to false. SDL Error: %s\n", _tmp28_);
		} else {
			sdx_js_game_set_showFps (self, TRUE);
		}
		_g_object_unref0 (f);
	}
	_tmp29_ = Mix_OpenAudio (22050, AUDIO_S16LSB, 2, 4096);
	sdx_sdlFailIf (_tmp29_ == (-1), "SDL_mixer unable to initialize!");
	_tmp30_ = g_new0 (guint8, 255);
	self->keys = (g_free (self->keys), NULL);
	self->keys = _tmp30_;
	self->keys_length1 = 255;
	g_print ("Game Initialized \n");
}


/**
         * start
         */
void sdx_js_game_start (sdxJsGame* self) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	sdx_js_game_set_running (self, TRUE);
	_tmp0_ = g_get_real_time ();
	self->priv->lastTime = ((gdouble) _tmp0_) / 1000000.0;
}


/**
         * getKey
         *
         * @param code of key (ascii)
         * @return 1 - pressed | 0 - not pressed
         */
gint sdx_js_game_getKey (sdxJsGame* self, gint code) {
	gint result = 0;
	guint8* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp1_ = 0;
	guint8 _tmp2_ = 0U;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->keys;
	_tmp0__length1 = self->keys_length1;
	_tmp1_ = code;
	_tmp2_ = _tmp0_[_tmp1_];
	result = (gint) _tmp2_;
	return result;
}


/**
         * handleEvents
         *
         * collect the event information for this frame
         * also update time info
         */
gint sdx_js_game_handleEvents (sdxJsGame* self) {
	gint result = 0;
	sdxGraphics* _tmp30_ = NULL;
	sdxGraphics* _tmp31_ = NULL;
	sdxGraphics* _tmp32_ = NULL;
	sdxGraphics* _tmp33_ = NULL;
	gdouble _tmp34_ = 0.0;
	gdouble _tmp35_ = 0.0;
	gdouble _tmp36_ = 0.0;
	sdxGraphics* _tmp37_ = NULL;
	sdxGraphics* _tmp38_ = NULL;
	gint _tmp39_ = 0;
	gint _tmp40_ = 0;
	gboolean _tmp41_ = FALSE;
	SDL_Event _tmp43_ = {0};
	SDL_EventType _tmp44_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	while (TRUE) {
		SDL_Event _tmp0_ = {0};
		gint _tmp1_ = 0;
		SDL_Event _tmp2_ = {0};
		SDL_EventType _tmp3_ = 0;
		_tmp1_ = SDL_PollEvent (&_tmp0_);
		 (self->priv->evt);
		self->priv->evt = _tmp0_;
		if (!(_tmp1_ != 0)) {
			break;
		}
		_tmp2_ = self->priv->evt;
		_tmp3_ = _tmp2_.type;
		switch (_tmp3_) {
			case SDL_KEYDOWN:
			{
				{
					SDL_Event _tmp4_ = {0};
					SDL_KeyboardEvent _tmp5_ = {0};
					SDL_Keysym _tmp6_ = {0};
					SDL_Keycode _tmp7_ = 0;
					_tmp4_ = self->priv->evt;
					_tmp5_ = _tmp4_.key;
					_tmp6_ = _tmp5_.keysym;
					_tmp7_ = _tmp6_.sym;
					if (_tmp7_ < 256) {
						guint8* _tmp8_ = NULL;
						gint _tmp8__length1 = 0;
						SDL_Event _tmp9_ = {0};
						SDL_KeyboardEvent _tmp10_ = {0};
						SDL_Keysym _tmp11_ = {0};
						SDL_Keycode _tmp12_ = 0;
						guint8 _tmp13_ = 0U;
						_tmp8_ = self->keys;
						_tmp8__length1 = self->keys_length1;
						_tmp9_ = self->priv->evt;
						_tmp10_ = _tmp9_.key;
						_tmp11_ = _tmp10_.keysym;
						_tmp12_ = _tmp11_.sym;
						_tmp8_[_tmp12_] = (guint8) 1;
						_tmp13_ = _tmp8_[_tmp12_];
					}
				}
				break;
			}
			case SDL_KEYUP:
			{
				{
					SDL_Event _tmp14_ = {0};
					SDL_KeyboardEvent _tmp15_ = {0};
					SDL_Keysym _tmp16_ = {0};
					SDL_Keycode _tmp17_ = 0;
					_tmp14_ = self->priv->evt;
					_tmp15_ = _tmp14_.key;
					_tmp16_ = _tmp15_.keysym;
					_tmp17_ = _tmp16_.sym;
					if (_tmp17_ < 256) {
						guint8* _tmp18_ = NULL;
						gint _tmp18__length1 = 0;
						SDL_Event _tmp19_ = {0};
						SDL_KeyboardEvent _tmp20_ = {0};
						SDL_Keysym _tmp21_ = {0};
						SDL_Keycode _tmp22_ = 0;
						guint8 _tmp23_ = 0U;
						_tmp18_ = self->keys;
						_tmp18__length1 = self->keys_length1;
						_tmp19_ = self->priv->evt;
						_tmp20_ = _tmp19_.key;
						_tmp21_ = _tmp20_.keysym;
						_tmp22_ = _tmp21_.sym;
						_tmp18_[_tmp22_] = (guint8) 0;
						_tmp23_ = _tmp18_[_tmp22_];
					}
				}
				break;
			}
			case SDL_MOUSEMOTION:
			{
				{
					SDL_Event _tmp24_ = {0};
					SDL_MouseMotionEvent _tmp25_ = {0};
					gint32 _tmp26_ = 0;
					SDL_Event _tmp27_ = {0};
					SDL_MouseMotionEvent _tmp28_ = {0};
					gint32 _tmp29_ = 0;
					_tmp24_ = self->priv->evt;
					_tmp25_ = _tmp24_.motion;
					_tmp26_ = _tmp25_.x;
					self->priv->_mouseX = (gint) _tmp26_;
					_tmp27_ = self->priv->evt;
					_tmp28_ = _tmp27_.motion;
					_tmp29_ = _tmp28_.y;
					self->priv->_mouseY = (gint) _tmp29_;
				}
				break;
			}
			case SDL_MOUSEBUTTONDOWN:
			{
				{
					self->priv->_mouseDown = TRUE;
				}
				break;
			}
			case SDL_MOUSEBUTTONUP:
			{
				{
					self->priv->_mouseDown = FALSE;
				}
				break;
			}
			case SDL_QUIT:
			{
				{
					self->priv->_running = FALSE;
				}
				break;
			}
			default:
			break;
		}
	}
	_tmp30_ = sdx_sdx_get_graphics ();
	_tmp31_ = _tmp30_;
	sdx_graphics_updateTime (_tmp31_);
	_tmp32_ = sdx_sdx_get_graphics ();
	_tmp33_ = _tmp32_;
	_tmp34_ = sdx_graphics_get_deltaTime (_tmp33_);
	_tmp35_ = _tmp34_;
	self->priv->_deltaTime = _tmp35_;
	_tmp36_ = self->priv->_deltaTime;
	if (_tmp36_ > ((gdouble) 1)) {
		self->priv->_deltaTime = 1.0 / 60.0;
	}
	_tmp37_ = sdx_sdx_get_graphics ();
	_tmp38_ = _tmp37_;
	_tmp39_ = sdx_graphics_get_fps (_tmp38_);
	_tmp40_ = _tmp39_;
	self->priv->_fps = _tmp40_;
	_tmp41_ = self->priv->_profile;
	if (_tmp41_) {
		gint64 _tmp42_ = 0LL;
		_tmp42_ = g_get_real_time ();
		self->t1 = ((gdouble) _tmp42_) / 1000000.0;
	}
	_tmp43_ = self->priv->evt;
	_tmp44_ = _tmp43_.type;
	result = (gint) _tmp44_;
	return result;
}


/**
         * draw
         *
         * draw the frame
         * do profiling
         */
void sdx_js_game_draw (sdxJsGame* self) {
	gboolean _tmp0_ = FALSE;
	SDL_Renderer* _tmp10_ = NULL;
	SDL_Renderer* _tmp11_ = NULL;
	SDL_Renderer* _tmp12_ = NULL;
	SDL_Renderer* _tmp13_ = NULL;
	gboolean _tmp33_ = FALSE;
	gboolean _tmp34_ = FALSE;
	GeeArrayList* _tmp57_ = NULL;
	gint _tmp58_ = 0;
	gboolean _tmp60_ = FALSE;
	SDL_Renderer* _tmp73_ = NULL;
	SDL_Renderer* _tmp74_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_profile;
	if (_tmp0_) {
		gint64 _tmp1_ = 0LL;
		gdouble _tmp2_ = 0.0;
		gdouble _tmp3_ = 0.0;
		gdouble _tmp4_ = 0.0;
		gdouble _tmp5_ = 0.0;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp1_ = g_get_real_time ();
		self->t2 = ((gdouble) _tmp1_) / 1000000.0;
		_tmp2_ = self->t2;
		_tmp3_ = self->t1;
		self->t3 = _tmp2_ - _tmp3_;
		_tmp4_ = self->t;
		_tmp5_ = self->t3;
		self->t = _tmp4_ + _tmp5_;
		_tmp6_ = self->k;
		self->k = _tmp6_ + 1;
		_tmp7_ = self->k;
		if (_tmp7_ == 1000) {
			gdouble _tmp8_ = 0.0;
			gdouble _tmp9_ = 0.0;
			self->k = 0;
			_tmp8_ = self->t;
			self->t = _tmp8_ / 1000.0;
			_tmp9_ = self->t;
			g_print ("%f\n", _tmp9_);
			self->t = (gdouble) 0;
		}
	}
	_tmp10_ = sdx_iapplication_get_renderer ((sdxIApplication*) self);
	_tmp11_ = _tmp10_;
	SDL_SetRenderDrawColor (_tmp11_, (guint8) 0x0, (guint8) 0x0, (guint8) 0x0, (guint8) 0x0);
	_tmp12_ = sdx_iapplication_get_renderer ((sdxIApplication*) self);
	_tmp13_ = _tmp12_;
	SDL_RenderClear (_tmp13_);
	{
		GeeArrayList* _sprite_list = NULL;
		GeeArrayList* _tmp14_ = NULL;
		GeeArrayList* _tmp15_ = NULL;
		gint _sprite_size = 0;
		GeeArrayList* _tmp16_ = NULL;
		gint _tmp17_ = 0;
		gint _tmp18_ = 0;
		gint _sprite_index = 0;
		_tmp14_ = self->sprites;
		_tmp15_ = _g_object_ref0 (_tmp14_);
		_sprite_list = _tmp15_;
		_tmp16_ = _sprite_list;
		_tmp17_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp16_);
		_tmp18_ = _tmp17_;
		_sprite_size = _tmp18_;
		_sprite_index = -1;
		while (TRUE) {
			gint _tmp19_ = 0;
			gint _tmp20_ = 0;
			gint _tmp21_ = 0;
			sdxgraphicss2dSprite* sprite = NULL;
			GeeArrayList* _tmp22_ = NULL;
			gint _tmp23_ = 0;
			gpointer _tmp24_ = NULL;
			sdxgraphicss2dSprite* _tmp25_ = NULL;
			SDL_Renderer* _tmp26_ = NULL;
			sdxgraphicss2dSprite* _tmp27_ = NULL;
			gint _tmp28_ = 0;
			gint _tmp29_ = 0;
			sdxgraphicss2dSprite* _tmp30_ = NULL;
			gint _tmp31_ = 0;
			gint _tmp32_ = 0;
			_tmp19_ = _sprite_index;
			_sprite_index = _tmp19_ + 1;
			_tmp20_ = _sprite_index;
			_tmp21_ = _sprite_size;
			if (!(_tmp20_ < _tmp21_)) {
				break;
			}
			_tmp22_ = _sprite_list;
			_tmp23_ = _sprite_index;
			_tmp24_ = gee_abstract_list_get ((GeeAbstractList*) _tmp22_, _tmp23_);
			sprite = (sdxgraphicss2dSprite*) _tmp24_;
			_tmp25_ = sprite;
			_tmp26_ = self->priv->_renderer;
			_tmp27_ = sprite;
			_tmp28_ = sdx_graphics_s2d_sprite_get_x (_tmp27_);
			_tmp29_ = _tmp28_;
			_tmp30_ = sprite;
			_tmp31_ = sdx_graphics_s2d_sprite_get_y (_tmp30_);
			_tmp32_ = _tmp31_;
			sdx_graphics_s2d_sprite_render (_tmp25_, _tmp26_, _tmp29_, _tmp32_, NULL);
			_g_object_unref0 (sprite);
		}
		_g_object_unref0 (_sprite_list);
	}
	_tmp34_ = self->priv->_showFps;
	if (_tmp34_) {
		sdxgraphicss2dSprite* _tmp35_ = NULL;
		_tmp35_ = self->priv->fpsSprite;
		_tmp33_ = _tmp35_ != NULL;
	} else {
		_tmp33_ = FALSE;
	}
	if (_tmp33_) {
		sdxgraphicss2dSprite* _tmp36_ = NULL;
		SDL_Renderer* _tmp37_ = NULL;
		_tmp36_ = self->priv->fpsSprite;
		_tmp37_ = self->priv->_renderer;
		sdx_graphics_s2d_sprite_render (_tmp36_, _tmp37_, 0, 0, NULL);
	}
	{
		GeeArrayList* _sprite_list = NULL;
		GeeArrayList* _tmp38_ = NULL;
		GeeArrayList* _tmp39_ = NULL;
		gint _sprite_size = 0;
		GeeArrayList* _tmp40_ = NULL;
		gint _tmp41_ = 0;
		gint _tmp42_ = 0;
		gint _sprite_index = 0;
		_tmp38_ = self->onetime;
		_tmp39_ = _g_object_ref0 (_tmp38_);
		_sprite_list = _tmp39_;
		_tmp40_ = _sprite_list;
		_tmp41_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp40_);
		_tmp42_ = _tmp41_;
		_sprite_size = _tmp42_;
		_sprite_index = -1;
		while (TRUE) {
			gint _tmp43_ = 0;
			gint _tmp44_ = 0;
			gint _tmp45_ = 0;
			sdxgraphicss2dSprite* sprite = NULL;
			GeeArrayList* _tmp46_ = NULL;
			gint _tmp47_ = 0;
			gpointer _tmp48_ = NULL;
			sdxgraphicss2dSprite* _tmp49_ = NULL;
			SDL_Renderer* _tmp50_ = NULL;
			sdxgraphicss2dSprite* _tmp51_ = NULL;
			gint _tmp52_ = 0;
			gint _tmp53_ = 0;
			sdxgraphicss2dSprite* _tmp54_ = NULL;
			gint _tmp55_ = 0;
			gint _tmp56_ = 0;
			_tmp43_ = _sprite_index;
			_sprite_index = _tmp43_ + 1;
			_tmp44_ = _sprite_index;
			_tmp45_ = _sprite_size;
			if (!(_tmp44_ < _tmp45_)) {
				break;
			}
			_tmp46_ = _sprite_list;
			_tmp47_ = _sprite_index;
			_tmp48_ = gee_abstract_list_get ((GeeAbstractList*) _tmp46_, _tmp47_);
			sprite = (sdxgraphicss2dSprite*) _tmp48_;
			_tmp49_ = sprite;
			_tmp50_ = self->priv->_renderer;
			_tmp51_ = sprite;
			_tmp52_ = sdx_graphics_s2d_sprite_get_x (_tmp51_);
			_tmp53_ = _tmp52_;
			_tmp54_ = sprite;
			_tmp55_ = sdx_graphics_s2d_sprite_get_y (_tmp54_);
			_tmp56_ = _tmp55_;
			sdx_graphics_s2d_sprite_render (_tmp49_, _tmp50_, _tmp53_, _tmp56_, NULL);
			_g_object_unref0 (sprite);
		}
		_g_object_unref0 (_sprite_list);
	}
	_tmp57_ = gee_array_list_new (SDX_GRAPHICS_S2D_TYPE_SPRITE, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->onetime);
	self->onetime = _tmp57_;
	_tmp58_ = self->priv->_yieldForEventsMs;
	if (_tmp58_ > 0) {
		gint _tmp59_ = 0;
		_tmp59_ = self->priv->_yieldForEventsMs;
		g_usleep ((gulong) _tmp59_);
	}
	_tmp60_ = self->priv->_showFps;
	if (_tmp60_) {
		sdxgraphicss2dSprite* _tmp61_ = NULL;
		sdxGraphics* _tmp62_ = NULL;
		sdxGraphics* _tmp63_ = NULL;
		gint _tmp64_ = 0;
		gint _tmp65_ = 0;
		gchar* _tmp66_ = NULL;
		gchar* _tmp67_ = NULL;
		sdxgraphicss2dFont* _tmp68_ = NULL;
		sdxgraphicsColor* _tmp69_ = NULL;
		sdxgraphicsColor* _tmp70_ = NULL;
		sdxgraphicss2dSprite* _tmp71_ = NULL;
		sdxgraphicss2dSprite* _tmp72_ = NULL;
		_tmp61_ = self->priv->fpsSprite;
		if (_tmp61_ != NULL) {
			_g_object_unref0 (self->priv->fpsSprite);
			self->priv->fpsSprite = NULL;
		}
		_tmp62_ = sdx_sdx_get_graphics ();
		_tmp63_ = _tmp62_;
		_tmp64_ = sdx_graphics_get_fps (_tmp63_);
		_tmp65_ = _tmp64_;
		_tmp66_ = g_strdup_printf ("%2.2f", (gdouble) _tmp65_);
		_tmp67_ = _tmp66_;
		_tmp68_ = self->priv->_font;
		_tmp69_ = sdx_graphics_color_get_AntiqueWhite ();
		_tmp70_ = _tmp69_;
		_tmp71_ = sdx_graphics_s2d_sprite_new_text (_tmp67_, _tmp68_, _tmp70_);
		_g_object_unref0 (self->priv->fpsSprite);
		self->priv->fpsSprite = _tmp71_;
		_g_free0 (_tmp67_);
		_tmp72_ = self->priv->fpsSprite;
		sdx_graphics_s2d_sprite_set_centered (_tmp72_, FALSE);
	}
	_tmp73_ = sdx_iapplication_get_renderer ((sdxIApplication*) self);
	_tmp74_ = _tmp73_;
	SDL_RenderPresent (_tmp74_);
}


gint sdx_js_game_get_yieldForEventsMs (sdxJsGame* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_yieldForEventsMs;
	result = _tmp0_;
	return result;
}


void sdx_js_game_set_yieldForEventsMs (sdxJsGame* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_yieldForEventsMs = _tmp0_;
	g_object_notify ((GObject *) self, "yieldForEventsMs");
}


gboolean sdx_js_game_get_profile (sdxJsGame* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_profile;
	result = _tmp0_;
	return result;
}


void sdx_js_game_set_profile (sdxJsGame* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_profile = _tmp0_;
	g_object_notify ((GObject *) self, "profile");
}


gboolean sdx_js_game_get_mouseDown (sdxJsGame* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_mouseDown;
	result = _tmp0_;
	return result;
}


void sdx_js_game_set_mouseDown (sdxJsGame* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_mouseDown = _tmp0_;
	g_object_notify ((GObject *) self, "mouseDown");
}


gint sdx_js_game_get_mouseX (sdxJsGame* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_mouseX;
	result = _tmp0_;
	return result;
}


void sdx_js_game_set_mouseX (sdxJsGame* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_mouseX = _tmp0_;
	g_object_notify ((GObject *) self, "mouseX");
}


gint sdx_js_game_get_mouseY (sdxJsGame* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_mouseY;
	result = _tmp0_;
	return result;
}


void sdx_js_game_set_mouseY (sdxJsGame* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_mouseY = _tmp0_;
	g_object_notify ((GObject *) self, "mouseY");
}


gboolean sdx_js_game_get_running (sdxJsGame* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_running;
	result = _tmp0_;
	return result;
}


void sdx_js_game_set_running (sdxJsGame* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_running = _tmp0_;
	g_object_notify ((GObject *) self, "running");
}


const gchar* sdx_js_game_get_name (sdxJsGame* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}


void sdx_js_game_set_name (sdxJsGame* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp1_;
	g_object_notify ((GObject *) self, "name");
}


const gchar* sdx_js_game_get_base (sdxJsGame* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_base;
	result = _tmp0_;
	return result;
}


void sdx_js_game_set_base (sdxJsGame* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_base);
	self->priv->_base = _tmp1_;
	g_object_notify ((GObject *) self, "base");
}


gint sdx_js_game_get_fps (sdxJsGame* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_fps;
	result = _tmp0_;
	return result;
}


void sdx_js_game_set_fps (sdxJsGame* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_fps = _tmp0_;
	g_object_notify ((GObject *) self, "fps");
}


gboolean sdx_js_game_get_showFps (sdxJsGame* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_showFps;
	result = _tmp0_;
	return result;
}


void sdx_js_game_set_showFps (sdxJsGame* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_showFps = _tmp0_;
	g_object_notify ((GObject *) self, "showFps");
}


gdouble sdx_js_game_get_deltaTime (sdxJsGame* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->priv->_deltaTime;
	result = _tmp0_;
	return result;
}


void sdx_js_game_set_deltaTime (sdxJsGame* self, gdouble value) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_deltaTime = _tmp0_;
	g_object_notify ((GObject *) self, "deltaTime");
}


static gint sdx_js_game_real_get_width (sdxIApplication* base) {
	gint result;
	sdxJsGame* self;
	gint _tmp0_ = 0;
	self = (sdxJsGame*) base;
	_tmp0_ = self->priv->_width;
	result = _tmp0_;
	return result;
}


static void sdx_js_game_real_set_width (sdxIApplication* base, gint value) {
	sdxJsGame* self;
	gint _tmp0_ = 0;
	self = (sdxJsGame*) base;
	_tmp0_ = value;
	self->priv->_width = _tmp0_;
	g_object_notify ((GObject *) self, "width");
}


static gint sdx_js_game_real_get_height (sdxIApplication* base) {
	gint result;
	sdxJsGame* self;
	gint _tmp0_ = 0;
	self = (sdxJsGame*) base;
	_tmp0_ = self->priv->_height;
	result = _tmp0_;
	return result;
}


static void sdx_js_game_real_set_height (sdxIApplication* base, gint value) {
	sdxJsGame* self;
	gint _tmp0_ = 0;
	self = (sdxJsGame*) base;
	_tmp0_ = value;
	self->priv->_height = _tmp0_;
	g_object_notify ((GObject *) self, "height");
}


sdxgraphicss2dFont* sdx_js_game_get_font (sdxJsGame* self) {
	sdxgraphicss2dFont* result;
	sdxgraphicss2dFont* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_font;
	result = _tmp0_;
	return result;
}


void sdx_js_game_set_font (sdxJsGame* self, sdxgraphicss2dFont* value) {
	sdxgraphicss2dFont* _tmp0_ = NULL;
	sdxgraphicss2dFont* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_font);
	self->priv->_font = _tmp1_;
	g_object_notify ((GObject *) self, "font");
}


static SDL_Renderer* sdx_js_game_real_get_renderer (sdxIApplication* base) {
	SDL_Renderer* result;
	sdxJsGame* self;
	SDL_Renderer* _tmp0_ = NULL;
	self = (sdxJsGame*) base;
	_tmp0_ = self->priv->_renderer;
	result = _tmp0_;
	return result;
}


static void sdx_js_game_class_init (sdxJsGameClass * klass) {
	sdx_js_game_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (sdxJsGamePrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_sdx_js_game_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_sdx_js_game_set_property;
	G_OBJECT_CLASS (klass)->finalize = sdx_js_game_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_YIELD_FOR_EVENTS_MS, g_param_spec_int ("yieldForEventsMs", "yieldForEventsMs", "yieldForEventsMs", G_MININT, G_MAXINT, 1000, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_PROFILE, g_param_spec_boolean ("profile", "profile", "profile", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_MOUSE_DOWN, g_param_spec_boolean ("mouseDown", "mouseDown", "mouseDown", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_MOUSE_X, g_param_spec_int ("mouseX", "mouseX", "mouseX", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_MOUSE_Y, g_param_spec_int ("mouseY", "mouseY", "mouseY", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_RUNNING, g_param_spec_boolean ("running", "running", "running", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_BASE, g_param_spec_string ("base", "base", "base", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_FPS, g_param_spec_int ("fps", "fps", "fps", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_SHOW_FPS, g_param_spec_boolean ("showFps", "showFps", "showFps", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_DELTA_TIME, g_param_spec_double ("deltaTime", "deltaTime", "deltaTime", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_WIDTH, g_param_spec_int ("width", "width", "width", G_MININT, G_MAXINT, 800, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_HEIGHT, g_param_spec_int ("height", "height", "height", G_MININT, G_MAXINT, 640, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_FONT, g_param_spec_object ("font", "font", "font", SDX_GRAPHICS_S2D_TYPE_FONT, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SDX_JS_GAME_RENDERER, g_param_spec_pointer ("renderer", "renderer", "renderer", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void sdx_js_game_sdx_iapplication_interface_init (sdxIApplicationIface * iface) {
	sdx_js_game_sdx_iapplication_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_width = sdx_js_game_real_get_width;
	iface->set_width = sdx_js_game_real_set_width;
	iface->get_height = sdx_js_game_real_get_height;
	iface->set_height = sdx_js_game_real_set_height;
	iface->get_renderer = sdx_js_game_real_get_renderer;
}


static void sdx_js_game_instance_init (sdxJsGame * self) {
	gchar* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	GeeArrayList* _tmp2_ = NULL;
	self->priv = SDX_JS_GAME_GET_PRIVATE (self);
	self->priv->_yieldForEventsMs = 1000;
	self->priv->_profile = FALSE;
	self->priv->_mouseX = 0;
	self->priv->_mouseY = 0;
	self->priv->_running = FALSE;
	self->priv->_showFps = FALSE;
	self->priv->_width = 800;
	self->priv->_height = 640;
	self->scale = 1.0;
	self->pixelFactor = 1.0;
	_tmp0_ = g_strdup ("fonts/OpenDyslexic-Bold.otf");
	self->defaultFont = _tmp0_;
	_tmp1_ = gee_array_list_new (SDX_GRAPHICS_S2D_TYPE_SPRITE, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
	self->sprites = _tmp1_;
	_tmp2_ = gee_array_list_new (SDX_GRAPHICS_S2D_TYPE_SPRITE, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
	self->onetime = _tmp2_;
	self->priv->currentTime = (gdouble) 0;
	self->priv->elapsed = (gdouble) 0;
	self->t1 = 0.0;
	self->t2 = 0.0;
	self->t3 = 0.0;
}


static void sdx_js_game_finalize (GObject* obj) {
	sdxJsGame * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SDX_TYPE_JS_GAME, sdxJsGame);
	_g_free0 (self->priv->_name);
	_g_free0 (self->priv->_base);
	_g_object_unref0 (self->priv->_font);
	_SDL_DestroyWindow0 (self->window);
	_SDL_DestroyRenderer0 (self->priv->_renderer);
	self->keys = (g_free (self->keys), NULL);
	 (self->priv->evt);
	_g_object_unref0 (self->priv->fpsSprite);
	_g_free0 (self->defaultFont);
	_g_object_unref0 (self->sprites);
	_g_object_unref0 (self->onetime);
	_g_object_unref0 (self->priv->app);
	G_OBJECT_CLASS (sdx_js_game_parent_class)->finalize (obj);
}


GType sdx_js_game_get_type (void) {
	static volatile gsize sdx_js_game_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_js_game_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (sdxJsGameClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sdx_js_game_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (sdxJsGame), 0, (GInstanceInitFunc) sdx_js_game_instance_init, NULL };
		static const GInterfaceInfo sdx_iapplication_info = { (GInterfaceInitFunc) sdx_js_game_sdx_iapplication_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType sdx_js_game_type_id;
		sdx_js_game_type_id = g_type_register_static (G_TYPE_OBJECT, "sdxJsGame", &g_define_type_info, 0);
		g_type_add_interface_static (sdx_js_game_type_id, SDX_TYPE_IAPPLICATION, &sdx_iapplication_info);
		g_once_init_leave (&sdx_js_game_type_id__volatile, sdx_js_game_type_id);
	}
	return sdx_js_game_type_id__volatile;
}


static void _vala_sdx_js_game_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	sdxJsGame * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SDX_TYPE_JS_GAME, sdxJsGame);
	switch (property_id) {
		case SDX_JS_GAME_YIELD_FOR_EVENTS_MS:
		g_value_set_int (value, sdx_js_game_get_yieldForEventsMs (self));
		break;
		case SDX_JS_GAME_PROFILE:
		g_value_set_boolean (value, sdx_js_game_get_profile (self));
		break;
		case SDX_JS_GAME_MOUSE_DOWN:
		g_value_set_boolean (value, sdx_js_game_get_mouseDown (self));
		break;
		case SDX_JS_GAME_MOUSE_X:
		g_value_set_int (value, sdx_js_game_get_mouseX (self));
		break;
		case SDX_JS_GAME_MOUSE_Y:
		g_value_set_int (value, sdx_js_game_get_mouseY (self));
		break;
		case SDX_JS_GAME_RUNNING:
		g_value_set_boolean (value, sdx_js_game_get_running (self));
		break;
		case SDX_JS_GAME_NAME:
		g_value_set_string (value, sdx_js_game_get_name (self));
		break;
		case SDX_JS_GAME_BASE:
		g_value_set_string (value, sdx_js_game_get_base (self));
		break;
		case SDX_JS_GAME_FPS:
		g_value_set_int (value, sdx_js_game_get_fps (self));
		break;
		case SDX_JS_GAME_SHOW_FPS:
		g_value_set_boolean (value, sdx_js_game_get_showFps (self));
		break;
		case SDX_JS_GAME_DELTA_TIME:
		g_value_set_double (value, sdx_js_game_get_deltaTime (self));
		break;
		case SDX_JS_GAME_WIDTH:
		g_value_set_int (value, sdx_iapplication_get_width ((sdxIApplication*) self));
		break;
		case SDX_JS_GAME_HEIGHT:
		g_value_set_int (value, sdx_iapplication_get_height ((sdxIApplication*) self));
		break;
		case SDX_JS_GAME_FONT:
		g_value_set_object (value, sdx_js_game_get_font (self));
		break;
		case SDX_JS_GAME_RENDERER:
		g_value_set_pointer (value, sdx_iapplication_get_renderer ((sdxIApplication*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_sdx_js_game_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	sdxJsGame * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SDX_TYPE_JS_GAME, sdxJsGame);
	switch (property_id) {
		case SDX_JS_GAME_YIELD_FOR_EVENTS_MS:
		sdx_js_game_set_yieldForEventsMs (self, g_value_get_int (value));
		break;
		case SDX_JS_GAME_PROFILE:
		sdx_js_game_set_profile (self, g_value_get_boolean (value));
		break;
		case SDX_JS_GAME_MOUSE_DOWN:
		sdx_js_game_set_mouseDown (self, g_value_get_boolean (value));
		break;
		case SDX_JS_GAME_MOUSE_X:
		sdx_js_game_set_mouseX (self, g_value_get_int (value));
		break;
		case SDX_JS_GAME_MOUSE_Y:
		sdx_js_game_set_mouseY (self, g_value_get_int (value));
		break;
		case SDX_JS_GAME_RUNNING:
		sdx_js_game_set_running (self, g_value_get_boolean (value));
		break;
		case SDX_JS_GAME_NAME:
		sdx_js_game_set_name (self, g_value_get_string (value));
		break;
		case SDX_JS_GAME_BASE:
		sdx_js_game_set_base (self, g_value_get_string (value));
		break;
		case SDX_JS_GAME_FPS:
		sdx_js_game_set_fps (self, g_value_get_int (value));
		break;
		case SDX_JS_GAME_SHOW_FPS:
		sdx_js_game_set_showFps (self, g_value_get_boolean (value));
		break;
		case SDX_JS_GAME_DELTA_TIME:
		sdx_js_game_set_deltaTime (self, g_value_get_double (value));
		break;
		case SDX_JS_GAME_WIDTH:
		sdx_iapplication_set_width ((sdxIApplication*) self, g_value_get_int (value));
		break;
		case SDX_JS_GAME_HEIGHT:
		sdx_iapplication_set_height ((sdxIApplication*) self, g_value_get_int (value));
		break;
		case SDX_JS_GAME_FONT:
		sdx_js_game_set_font (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



